gwpy/gwpy

- gwpy/timeseries/core.py
This PR fixes the TimeSeries band-pass-related filter functions to use Butterworth IIR filters, and updates the `TimeSeries.filter` method to use scipy's upcoming second-order-sections.
This PR will fix #29
> Improved filtering methods for TimeSeries

- gwpy/plotter/__init__.py
This PR fixes #40 by setting the `axes.formatter.limits` setting in `rcParams`.
> Set rcParams['axes.formatter.limits'] = (-3, 4)

- gwpy/cli/cliproduct.py
- gwpy/cli/coherencegram.py
- gwpy/cli/spectrogram.py
- gwpy/cli/timeseries.py
latest (and last change) has the option for GPS labels for time axis and removes the word "log" from Spectrogram colorbar label.
When this is merged we are ready to release ldvw.
2 minor pep8 issues fixed.
This fixes #41.
> Version for gwpy release

- gwpy/cli/spectrogram.py
Fixed #61 Long durations spectrograms were setting stride wrong in the cli program
> Long dur specgram

- gwpy/cli/spectrogram.py
Reverts gwpy/gwpy#62
These changes introduced SyntaxErrors due to unresolved git conflicts.
> Revert "Long dur specgram"

- gwpy/cli/spectrogram.py
> Revert "Revert "Long dur specgram""

- gwpy/cli/coherence.py
- gwpy/cli/spectrogram.py
Fixes #68 Failure in building documentation examles
Fixes #67 The revert on previous pull
Fixes #65 Merge conflict 
Fixes #63 Labels with wrong UTC time
All were minor changes
Main issue is to choose between the two Spectrogram implementations.
> Long dur specgram - fixes merge conflics, labels with wrong time, bug in building docs and uses warn not pring

- .gitignore
- docs/Makefile
- docs/conf.py
- gwpy/io/cache.py
- gwpy/spectrogram/spectrogram.py
- gwpy/spectrum/core.py
- gwpy/spectrum/lal_.py
- gwpy/spectrum/psd.py
- gwpy/timeseries/core.py
- gwpy/timeseries/io/cache.py
- gwpy/timeseries/io/losc.py
- gwpy/utils/lal.py
This PR fixes the doxygen links between the LALSuite packages and GWpy. The first commit fixes the link in the sphinx `Makefile` and `conf.py`, and the second changes the tags throughout the source code from `:lalsuite:` to `:lal:`.
> Fixed LALSuite doxylink

- gwpy/plotter/segments.py
This PR introduces a few improvements to the way `SegmentAxes` handles collections, mainly to allow for inset labeling.
The changes are fairly minimal, but add a few bits of functionality.
> Improvements to SegmentAxes collections

- .gitignore
- .travis.yml
This PR enables coveralls.io test checking.
> Enable coveralls test checking

- gwpy/timeseries/io/gwf/framecpp.py
> StateVector.read: fixed bug in framecpp dtype

- .travis.yml
- gwpy/tests/__init__.py
- gwpy/tests/timeseries.py
- gwpy/timeseries/common.py
- gwpy/timeseries/core.py
- gwpy/timeseries/io/__init__.py
This PR works to improve the unit tests in `/gwpy/tests/`.
Multiple commits will be made and pushed, testing the travis-ci build and coveralls updates. Please don't merge until I think this work is done.
Additionally, any new bugs uncovered by new tests will be fixed inline.
> Improved unit tests

- gwpy/segments/io/ligolw.py
This PR introduces a single commit to fix a bug in reading segments from `LIGO_LW` XML.
We needed to read all segment_definer rows with the same name as a single flag, since ligolw_add doesn't combine multiple definitions into one, so otherwise we would just read one of them.
> Fixed bug in LIGO_LW segment reading

- gwpy/timeseries/io/gwf/__init__.py
- gwpy/timeseries/statevector.py
This PR improves the functionality of `StateVectorDict.read` and the documentation of that method and of `StateVector.read`. The changes are mainly related to the `bits` keyword argument.
> Improvements to StateVector{Dict}.read

- docs/detector/channel.rst
- gwpy/data/array.py
- gwpy/data/array2d.py
- gwpy/data/series.py
- gwpy/detector/channel.py
- gwpy/segments/flag.py
- gwpy/segments/segments.py
- gwpy/spectrogram/core.py
- gwpy/spectrum/core.py
- gwpy/time/_tconvert.py
- gwpy/timeseries/core.py
- gwpy/timeseries/statevector.py
- gwpy/timeseries/timeseries.py
- gwpy/utils/__init__.py
- gwpy/utils/docstring.py
This PR improves the way the docstring interpolation system works, replacing the `@update_docstrings` class decorator with a more general `@interpolate_docstring` decorator for classes and/or methods.
> Improved docstring interpolation

- .travis.yml
- gwpy/io/cache.py
- gwpy/tests/test_io.py
- setup.py
This PR fixes #117 by cleaning up the `gwpy.io.cache.cache_segments` function, and adding a new unit test for that method.
> Fixed bug in gwpy.io.cache.cache_segments

- gwpy/plotter/axes.py
- gwpy/plotter/gps.py
- gwpy/plotter/segments.py
- gwpy/plotter/utils.py
- gwpy/tests/test_plotter.py
This PR introduces a new test suite for the `gwpy.plotter` module.
The subsequent commits fix bugs detected by the new unit tests.
> New unittest module for gwpy.plotter

- gwpy/segments/flag.py
- gwpy/tests/test_segments.py
This PR implements support for the cascaded versionless query using the dqsegdb client.
> New versionless dqsegdb query

- .travis.yml
- gwpy/detector/__init__.py
- gwpy/detector/channel.py
- gwpy/detector/io/__init__.py
- gwpy/detector/io/clf.py
- gwpy/detector/io/omega.py
This PR introduces the `ChannelList.read` and `ChannelList.write` methods, with two new formats
- `ini`: the Channel List File format used by LIGO for O1
- `omega-scan`: the configuration file format use by the Omega-pipeline scan tool
> New ChannelList input /output methods

- gwpy/table/lsctables.py
This PR fixes #150 by using the `filt` kwarg of `Table.read` to return only those events that lie within the given `[start, end)` segment.
> Table.fetch: use filt kwarg to restrict events to input segment

- .gitignore
- .travis.yml
- .travis/build-with-autotools.sh
- docs/install.rst
- gwpy/io/datafind.py
- gwpy/tests/test_detector.py
- requirements.txt
- setup.py
This PR upgrades the automated build-and-test setup for travis-ci.org to use the new container infrastructure, and adds a requirements.txt file for pip installing the dependencies of GWpy.
> Upgrade to new travis-ci.org containers

- examples/spectrogram/plot.py
This PR fixes a bug in the `spectrogram/plot` example [ci skip].
> Fixed bug in example

- gwpy/spectrum/scipy_.py
- gwpy/tests/test_timeseries.py
- gwpy/timeseries/timeseries.py
Adding support for calculating cross spectral densities using new `csd` method, as well as in spectrograms using the `cross` keyword argument.
> Cross spectral density

- gwpy/plotter/spectrum.py
- gwpy/plotter/timeseries.py
`TimeSeriesAxes.plot_timeseries_mmm` and `SpectrumAxes.plot_spectrum_mmm` now support rasterized as a kwarg.
> Added rasterized support for two plotting methods

- gwpy/timeseries/timeseries.py
This PR adds a new `asd` keyword-argument to the `TimeSeries.whiten` method to allow whitened against a fixed ASD `Spectrum`.
> TimeSeries.whiten: added support for fixed asd

- gwpy/cli/cliproduct.py
- gwpy/spectrum/utils.py
- gwpy/tests/test_cli.py
- gwpy/tests/test_plotter.py
This PR introduces an expanded set of unit tests for the `gwpy.cli` module that powers the `gwpy-plot` command-line script.
> Improved unit tests for cli module

- gwpy/timeseries/io/gwf/framecpp.py
This commit improved the error reporting from `frameCPP` `IndexError`s a little.
> Minor improvement to frameCPP error reporting

- gwpy/tests/test_timeseries.py
- gwpy/timeseries/io/losc.py
This PR improves the reading of LOSC files using `TimeSeries.read`.
> Updated LOSC TimeSeries reading

- gwpy/segments/flag.py
- gwpy/tests/test_segments.py
This PR fixes #223 by patching `DataQualityDict.populate`. Also added a regression test.
> Fixed bug in DataQualityDict.populate

- gwpy/io/__init__.py
- gwpy/tests/test_timeseries.py
- gwpy/timeseries/core.py
- gwpy/timeseries/io/gwf/__init__.py
- gwpy/timeseries/io/gwf/framecpp.py
- gwpy/timeseries/statevector.py
- gwpy/timeseries/timeseries.py
This PR adds functionality to allow writing GWF files using the frameCPP python bindings.
> Added support for writing GWF files with frameCPP

- gwpy/segments/flag.py
This PR fixes #222 by improving the docstring for the aforementioned method.
> Update docstring for DataQualityDict.from_veto_definer_file

- gwpy/detector/channel.py
- gwpy/segments/flag.py
- gwpy/tests/test_detector.py
- gwpy/tests/test_segments.py
- gwpy/tests/test_timeseries.py
- gwpy/timeseries/core.py
This PR introduces a number of new unit tests that improve the test coverage (ideally).
> Added some more unit tests

- gwpy/io/datafind.py
- gwpy/io/kerberos.py
- gwpy/timeseries/core.py
- gwpy/utils/shell.py
This PR introduces a few improvements in code used to find the best-matched frametype for a given channel.
Further optimisations might include finding multiple channels in one go...
> Improvements to finding best frametype

- gwpy/timeseries/timeseries.py
This PR fixes #237 by introducing an overlap between neighbouring PSDs.
> Overlap PSDs in TimeSeries.spectrogram

- gwpy/data/series.py
- gwpy/frequencyseries/core.py
- gwpy/plotter/frequencyseries.py
- gwpy/plotter/segments.py
- gwpy/plotter/timeseries.py
- gwpy/spectrogram/core.py
- gwpy/tests/test_array.py
- gwpy/tests/test_cli.py
- gwpy/tests/test_io.py
- gwpy/tests/test_plotter.py
- gwpy/tests/test_spectrogram.py
- gwpy/tests/test_timeseries.py
- gwpy/timeseries/core.py
- gwpy/timeseries/statevector.py
- gwpy/timeseries/timeseries.py
This PR improves the coverage of the test suite.
> Improved test coverage

- gwpy/table/io/ligolw.py
This PR fixes a bug in the way keyword arguments are handed in the reader for `GWRecArray` with a LIGO_LW format.
> Fixed bug in kwarg handling for GWRecArray.read from LIGO_LW

- gwpy/tests/test_array.py
- gwpy/types/array.py
- gwpy/types/series.py
This PR improves the test suite for gwpy via directly increased coverage and use of mock.
> Improved test suite

- gwpy/types/__init__.py
- gwpy/types/array.py
- gwpy/types/array2d.py
- gwpy/types/index.py
- gwpy/types/io/hdf5.py
- gwpy/types/series.py
This PR introduces the `Index`, a thin sub-class of `Quantity` that provides a test of regularity.
> New Index array

- gwpy/tests/test_segments.py
- gwpy/tests/test_timeseries.py
This PR improves the handling of missing 'optional' dependencies when running the test suite.
> Improved error handling in tests suite

- gwpy/frequencyseries/core.py
- gwpy/frequencyseries/hist.py
- gwpy/frequencyseries/scipy_.py
- gwpy/io/hdf5.py
- gwpy/io/ligolw.py
- gwpy/io/nds.py
- gwpy/io/utils.py
- gwpy/plotter/core.py
- gwpy/plotter/filter.py
- gwpy/plotter/frequencyseries.py
- gwpy/plotter/segments.py
- gwpy/plotter/spectrogram.py
- gwpy/plotter/table.py
- gwpy/plotter/timeseries.py
- gwpy/plotter/utils.py
- gwpy/segments/flag.py
- gwpy/segments/io/segwizard.py
- gwpy/spectrogram/coherence.py
- gwpy/table/io/cwb.py
- gwpy/table/io/omega.py
- gwpy/table/lsctables.py
- gwpy/timeseries/io/cache.py
- gwpy/timeseries/io/gwf/framecpp.py
- gwpy/timeseries/io/gwf/lalframe.py
- gwpy/timeseries/statevector.py
- gwpy/timeseries/timeseries.py
- gwpy/types/array.py
This PR corrects a number of complaints from `pyflakes`, mainly unused `import`s and variable assignments.
> Fixed myriad complaints from pyflakes

- .gitignore
- docs/_static/gwpy-sphinx.css
- docs/conf.py
- docs/segments/index.rst
- docs/spectrogram/index.rst
- docs/spectrum/index.rst
- docs/table/index.rst
- docs/timeseries/index.rst
- docs/timeseries/statevector.rst
This PR adds a number of improvements to documentation.
> Myriad improvements to documentation

- gwpy/tests/compat.py
- gwpy/tests/mockutils.py
- gwpy/tests/test_segments.py
- gwpy/tests/test_timeseries.py
- gwpy/timeseries/core.py
This PR introduces use of `mock` to the test suite to increase test coverage.
> Use mock to fake tests

- gwpy/io/datafind.py
- gwpy/tests/common.py
- gwpy/tests/test_io.py
This PR improves the methods for parsing a GWF file table-of-conents within `gwpy.io.datafind`.
> Improved framefile TOC parsing methods

- docs/install.rst
This commit fixes #198 by adding installation documentation for gwpysoft.
> Added install notes for GWpySoft [ci-skip]

- .codeclimate.yml
- gwpy/io/cache.py
- gwpy/tests/test_array.py
- gwpy/tests/test_io.py
- gwpy/tests/test_timeseries.py
- gwpy/timeseries/io/cache.py
- gwpy/timeseries/io/lalframe.py
This PR improves the handling or gaps and padding gaps for the new lalframe API.
> Improved handling of gaps/padding for new lalframe API

- gwpy/table/io/root.py
- gwpy/tests/test_table.py
This PR improves reading and writing ROOT tables, including the addition of unit tests.
> Improved read/write for ROOT tables, including tests

- gwpy/table/io/ligolw.py
- gwpy/tests/test_table.py
This PR implements writing `Table` and `EventTable` objects to LIGO_LW-format files.
> Added writer for Table to ligolw formats

- gwpy/detector/io/clf.py
This PR updates the channel list file (CLF) reader to parse the new O2/2017-format files, which include safety and fidelity columns.
> Updated channel list file syntax to include new columns

- docs/timeseries/io.rst
- gwpy/io/hdf5.py
- gwpy/segments/io/hdf5.py
- gwpy/tests/test_array.py
- gwpy/tests/test_frequencyseries.py
- gwpy/tests/test_timeseries.py
- gwpy/timeseries/core.py
- gwpy/timeseries/io/hdf5.py
- gwpy/timeseries/statevector.py
- gwpy/timeseries/timeseries.py
- gwpy/types/io/hdf5.py
This PR simplifies the definitions of `read()` and write()` for the `gwpy.timeseries` classes, including allowing HDF5 to accept `start` and `end` keywords.
> Improved TimeSeries read() and write() definitions

- gwpy/tests/test_astro.py
This PR exists to allow testing on travis-ci to try and fix the failing gwpy.astro tests.
> Attempt to fix failing gwpy.astro tests

- .travis.yml
- requirements-dev.txt
- requirements-extra.txt
- requirements.txt
- setup.py
This PR cleans up the pip requirements files and the related build commands in the travis-ci configuration file. There are no functional changes to the gwpy package.
> Cleaned up requirements files and build steps

- docs/table/io.rst
- gwpy/io/gwf.py
- gwpy/io/mp.py
- gwpy/table/io/__init__.py
- gwpy/table/io/gwf.py
- gwpy/table/table.py
- gwpy/tests/test_table.py
- gwpy/timeseries/io/gwf/__init__.py
- gwpy/timeseries/io/gwf/framecpp.py
This PR implements `Table`/`EventTable` I/O for GWF FrEvents. To enable this I have added some generic frame writing utilities to `gwpy.io.gwf` (adapted from `gwpy.timeseries.io.gwf.framecpp`).
> Added I/O utilities for GWF FrEvents

- .travis/build-src-dependencies.sh
- .travis/build-with-autotools.sh
This PR attempts to speed up frameCPP builds to prevent 50 minute timeouts.
> Attempt to optimise frameCPP builds

- .travis.yml
- gwpy/detector/channel.py
- gwpy/tests/test_table.py
- gwpy/tests/test_utils.py
- gwpy/timeseries/statevector.py
- gwpy/types/series.py
- gwpy/utils/shell.py
This PR fixes a few bugs thrown up by the minimal python3 test suite, either in the tests themselves, or in the package code. The minimal python3 test suite should now pass.
> Fixed bugs related to python3

- .travis/find-latest-releases.sh
- requirements-dev.txt
This PR removes two packages that glue doesn't require those any more, so they don't need to be installed during CI testing.
> Removed m2crypto and cjson from requirements-dev.txt

- docs/Makefile
- docs/ex2rst.py
- docs/references.txt
- docs/table/io.rst
- examples/spectrogram/ratio.py
- examples/timeseries/pycbc-snr.py
- gwpy/timeseries/timeseries.py
This PR improves a few random aspects of the documentation generated using sphinx, mainly by fixing bugs that caused warnings on the command line.
> Fixed a few sphinx warnings for documentation

- docs/timeseries/io.rst
- gwpy/tests/test_array.py
- gwpy/tests/test_timeseries.py
- gwpy/timeseries/io/__init__.py
- gwpy/timeseries/io/wav.py
This PR implements reading/writing WAV files using the `TimeSeries` object.
> Added unified I/O for reading/writing TimeSeries in WAV format

- docs/table/index.rst
This PR fixes a trivial issue with the sphinx documentation
> Fixed reference to astropy Data Tables in docs

- gwpy/types/array2d.py
This PR improves the handling of 1D output (`Series`) in `Array2D._wrap_function`, by simplifying the logic to only pass the necessary metadata, without duplicating metadata that will generate warnings.
> Fixed UserWarnings in Array2D._wrap_function

- gwpy/detector/io/omega.py
- gwpy/tests/test_detector.py
This PR adds unit tests for `ChannelList.read()` and `ChannelList.write()` I/O with Omega scan configuration files.
> Added tests for ChannelList I/O with omega scan configuration files

- gwpy/table/filter.py
- gwpy/table/io/hacr.py
- gwpy/tests/test_table.py
- requirements-dev.txt
- setup.py
This PR improves the implementation of HACR event fetching via SQL queries:
- [a5dd303] removed unused imports/variables
- [f6a2635] perform selections (filtering) as part of SQL query (not after-the-fact)
> Improvements to HACR event fetching

- gwpy/segments/flag.py
- gwpy/tests/mocks.py
- gwpy/tests/test_segments.py
This PR makes a few improvements to the `gwpy.segments.flag` module, mainly by adding more unit tests to improve the coverage, and then fixing the bugs uncovered by the new tests.
> Improvements to gwpy.segments.flag (mainly tests)

- gwpy/tests/test_cli.py
This PR simply adds a unit test of `gwpy.cli.CliProduct.makePlot`.
> Added a test of CliProduct.makePlot

- gwpy/cli/__init__.py
- gwpy/cli/cliproduct.py
- gwpy/cli/coherence.py
- gwpy/cli/coherencegram.py
- gwpy/cli/spectrogram.py
- gwpy/cli/spectrum.py
- gwpy/cli/timeseries.py
This PR makes some pedantic changes to the style/syntax used in the `gwpy.cli` module, mainly to bring it inline with the visual style used in the rest of the package.
There are (should be) no functional changes to any part of the module.
> Pedantic changes to the style/syntax in gwpy.cli

- gwpy/io/kerberos.py
- gwpy/tests/test_io.py
This PR adds unit tests for the `gwpy.io.kerberos` module, and fixes a few bugs uncovered during testing (mainly for python3).
> Added tests for gwpy.io.kerberos module

- gwpy/table/io/gravityspy.py
This PR improves the 'gravityspy' `EventTable.fetch` interface to allow filtering based on columns and selections.
I also included a small improvement in the error handling when the table does not exist.
[@scottcoughlin2014]
> Added column and selection filters for gravityspy queries

- gwpy/io/datafind.py
- gwpy/tests/test_timeseries.py
- gwpy/timeseries/core.py
This PR makes some incremental improvements to `TimeSeries{Dict}.find` and the underlying code in `gwpy.io.datafind`, including fixing some errors in the unit tests.
> Improvements to TimeSeries.find, including tests

- gwpy/segments/flag.py
- gwpy/table/io/gwf.py
This commit removes some `print()` calls that were presumably left over from debugging.
> Removed some debugging print statements

- gwpy/io/hdf5.py
- gwpy/tests/test_timeseries.py
- gwpy/timeseries/io/hdf5.py
- gwpy/types/io/hdf5.py
This PR implements HDF5 unified I/O operations for the `TimeSeriesDict` class, and associates. Fixes #347.
> Added HDF5 read/write for TimeSeriesDict

- gwpy/plotter/core.py
- gwpy/plotter/html.py
- gwpy/plotter/segments.py
- gwpy/plotter/timeseries.py
- gwpy/tests/test_plotter.py
- requirements-dev.txt
- setup.py
This PR improves the unit tests for `gwpy.plotter` and modules therein. Some module code has been restructured mainly to clean up the modules, with no functional changes.
> Improved testing of gwpy.plotter

- examples/timeseries/blrms.py
This PR fixes some text display issues with the `blrms.py` example script.
> Fixed two text issues with blrms.py example

- docs/examples/index.rst
- examples/miscellaneous/index.rst
- examples/miscellaneous/range-timeseries.py
This PR adds a new example demonstrating how to generate an inspiral range `TimeSeries` using LOSC data.
> New inspiral_range timeseries example

- docs/conf.py
- docs/table/filter.rst
- docs/table/index.rst
- gwpy/table/filter.py
- gwpy/table/filters.py
- gwpy/table/io/gwf.py
- gwpy/table/io/sql.py
- gwpy/table/io/utils.py
- gwpy/table/table.py
- gwpy/tests/test_table.py
This PR introduces an improvement to the way filtering is done for `gwpy.table.EventTable` objects, including expansions to the documentation.
The main change is a new way to define and apply filters using functions, see the new docs for details.
> Improvements to filtering tables

- .travis.yml
- ci/docker-install.sh
- ci/install-debian.sh
- ci/install-el.sh
- ci/install.sh
- ci/lib.sh
- ci/test.sh
This PR fixes a few more build problems using the ligo/software images on python3.
> Fixes to build problems for ligo/software images and python3

- examples/frequencyseries/hoff.py
This PR fixes a bug in one of the examples.
> Fixed bug in example script

- setup.py
This PR cleans up the `setup.py` build script by removing some unused imports, and generally appeasing `pylint`.
> Cleaned up setup.py

- .travis.yml
- Portfile.template
- ci/install-macos.sh
- ci/install.sh
- ci/lib.sh
- ci/test.sh
- setup.py
This PR adds a macports build to the CI configuration for Travis.
Fixes #205.
> Added macports build to travis CI configuration

- .travis.yml
- ci/install-el.sh
- ci/install.sh
- debian/rules
This PR resolves a few bugs in build-and-test on LDG docker images.
> A few fixes for CI tests on LDG docker images

- examples/timeseries/whiten.py
This PR makes a few improvements to the whitening example plot.
> Minor improvements to whitening example [ci skip]

- docs/_static/gwpy-sphinx.css
This PR includes a trivial improvement to the stylesheet for the sphinx docs.
> Minor improvement to CSS [ci skip]

- docs/plotter/colors.rst
- gwpy/timeseries/core.py
This PR corrects two sphinx errors, there are no functional changes.
> Fixed a couple of sphinx warnings/errors [ci skip]

- gwpy/cli/coherence.py
- gwpy/cli/coherencegram.py
- gwpy/cli/qtransform.py
- gwpy/cli/spectrogram.py
- gwpy/cli/spectrum.py
- gwpy/cli/timeseries.py
This PR supersedes #570 with a clean history.
cc: @areeda.
> Update docstrings in gwpy.cli

- ci/install-debian.sh
- ci/install-el.sh
- ci/install-macos.sh
- ci/install.sh
This PR modifies debian and el7 builds to install root and root_numpy, and all builds to install from `requirements-dev.txt` in an attempt to increase the coverage.
> Install more packages during CI

- gwpy/tests/test_array.py
- gwpy/tests/test_cli.py
This PR adds unit tests for the new `gwpy.cli.qtransform` product, and updates the other `gwpy.cli` tests to call the new `post_arg` method used in argument parsing.
cc: @areeda
> Added unit tests for CliQtransform

- docs/dev/release.rst
- docs/index.rst
This PR adds a documentation page for the release process.
> Added documentation of release process

- etc/Portfile.template
- setup_utils.py
This PR implements feedback from macports maintainers regarding the formatting of the `Portfile`, see https://github.com/macports/macports-ports/pull/1233#issuecomment-359194777.
> Minor improvements to Portfile format

- .travis.yml
This PR fixes a bug in the pypi deployment configuration for travis-ci.
> Fixed bug in pypi deploy for CI

- .travis.yml
This PR is a fixed copy of [#655], fixing pypi deploying in CI.
> Fixed bug in pypi deploy conditions (again)

- gwpy/segments/flag.py
- gwpy/tests/test_segments.py
This PR duplicates some of the work of #665 onto the `DataQualityDict.query` method, for consistency.
> Improved method selection in DataQualityDict.query

- gwpy/cli/cliproduct.py
Detect units of '*' and override so we can calculate spectra
> Handle unit of '*' from NDS2

- gwpy/detector/channel.py
- gwpy/segments/flag.py
- gwpy/tests/test_detector.py
- gwpy/tests/test_segments.py
- gwpy/types/array.py
- gwpy/utils/misc.py
This PR fixes a bunch of complaints from codeclimate, which should have zero (or negligible) impact on the code functionality.
> Improvements based on codeclimate complaints

- gwpy/frequencyseries/hist.py
- gwpy/spectrogram/core.py
- gwpy/tests/test_array.py
- gwpy/tests/test_frequencyseries.py
- gwpy/types/array.py
- gwpy/types/array2d.py
- gwpy/types/series.py
- gwpy/types/sliceutils.py
- gwpy/types/utils.py
This PR fixes #683 by rewriting `Array2D.__getitem__` to work properly.
> Fixed bug in Array2D slicing

- .codeclimate.yml
- .pep8speaks.yml
- gwpy/io/kerberos.py
- gwpy/signal/fft/basic.py
- gwpy/signal/fft/ui.py
- gwpy/table/io/omega.py
- gwpy/tests/mocks.py
- gwpy/tests/test_array.py
- gwpy/tests/test_frequencyseries.py
- gwpy/tests/test_signal.py
- gwpy/tests/test_timeseries.py
- gwpy/tests/utils.py
- gwpy/time/_tconvert.py
- gwpy/timeseries/io/gwf/__init__.py
- gwpy/timeseries/io/gwf/lalframe.py
- gwpy/utils/sphinx/numpydoc.py
This PR fixes a bunch of pep8 issues, with no changes to functionality, build, or documentation.
> Fixed a number of PEP-0008 related issues

- examples/frequencyseries/percentiles.py
- gwpy/plotter/axes.py
- gwpy/plotter/core.py
- gwpy/plotter/frequencyseries.py
- gwpy/plotter/series.py
- gwpy/plotter/timeseries.py
This PR adds two new base classes, SeriesAxes and SeriesPlot to reduce duplication between the TimeSeries and FrequencySeries plotters.
This is a simplified version of #694, which included too many other changes.
> Added new SeriesAxes and SeriesPlot base classes

- gwpy/frequencyseries/core.py
- gwpy/frequencyseries/hist.py
- gwpy/table/table.py
- gwpy/timeseries/core.py
- gwpy/timeseries/statevector.py
- gwpy/timeseries/timeseries.py
This PR improves the docstrings for a bunch of `Array` sub-class `.plot()` methods.
> Improved docstrings for Array plot() methods

- gwpy/detector/channel.py
- gwpy/plotter/frequencyseries.py
- gwpy/plotter/gps.py
- gwpy/plotter/segments.py
- gwpy/plotter/timeseries.py
- gwpy/segments/flag.py
This PR updates the comment lines that separate blocks of code to all use the same standard.
> Updated all comment lines to standard [ci skip]

- gwpy/plotter/timeseries.py
- gwpy/plotter/utils.py
- gwpy/tests/test_spectrogram.py
This PR fixes bugs in the overloading of `SeriesAxes` methods as part of the `TimeSeriesAxes` class.
> Fixed some bugs in TimeSeriesAxes overloading of SeriesAxes

- gwpy/table/io/sql.py
This allows them to be save with astropy `.write` with first needed to convert the rows yourself
>  Modified sql.py to convert unicode columns to strings.

- .travis.yml
- ci/install-macos.sh
- gwpy/tests/test_segments.py
This PR supercedes #777 with a simpler fix for the CI issue on macos.
> Fixed python version for macos CI builds

- .codebeatignore
This PR adds `.codebeatignore` to remove unwanted files from the codebeat analysis.
> Added codebeat ignore file [ci skip]

- .circleci/config.yml
- ci/test.sh
This PR improves the CircleCI configuration to something that should work. This is mainly to stop PRs getting spammed by circleci and the current bogus config, but does pave the way for a more productive CircleCI usage in the future.
> Improved circle configuration to something that will work

- gwpy/plot/plot.py
This PR fixes a bug in `Plot.add_segments_bar` whereby the X-axis of the original `Axes` would be autoscaled regardless of whether it had `autoscalex_on` or not.
> Fixed autoscaling of parent X-axis in Plot.add_segments_bar

- gwpy/cli/cliproduct.py
- gwpy/cli/spectrogram.py
Fixes #815, unrecognized units `Counts.` and adds logging of the color table limits for debugging a different issue. Both are trivial changes.
> Bad unit plot fix

- gwpy/plot/plot.py
This PR makes a tiny adjustment to the default height of the segments bar - just a little thinner is a little nicer on the eye.
> Made segments bar smaller in Plot.add_segments_bar

- docs/_static/css/gwpy-sphinx.css
- docs/segments/index.rst
- docs/table/plot.rst
This PR fixes 3 small issues in the documentation.
> Some trivial improvements to documentation

- examples/segments/open-data.py
- examples/table/rate.py
- examples/table/rate_binned.py
- examples/timeseries/blrms.py
- examples/timeseries/pycbc-snr.py
- examples/timeseries/qscan.py
- examples/timeseries/whiten.py
- gwpy/timeseries/core.py
This PR adds a few minor improvements to the examples, and in the mean time adds a new `TimeSeriesBaseDict.step` method.
> A few minor improvements to examples

- gwpy/cli/cliproduct.py
Addresses issue #881 if epoch is small it is relative to min start time
> Relative epoch

- README.md
This PR adds build status badges for appveyor to the README file.
> Added appveyor badges to README

- gwpy/cli/qtransform.py
Data type of qrange and frange changed from  str  to float because of labeling issues
> Formatting qrange problem fixed

- docs/overview.rst
- docs/plot/gps.rst
- docs/spectrogram/index.rst
- docs/spectrum/index.rst
- docs/table/rate.rst
- docs/timeseries/plot.rst
- docs/timeseries/statevector.rst
This PR introduces a few more trivial documentation fixes to be included in the 0.12.1 release.
> More documentation fixes for 0.12.1

- ci/install-el.sh
- gwpy/io/nds2.py
- gwpy/timeseries/io/nds2.py
This PR fixes a few bugs in fetching data using the `nds2` client from an **NDS1** server.
> Fixed fetching data with nds1

- docs/timeseries/io.rst
- gwpy/detector/units.py
- gwpy/timeseries/io/gwf/framecpp.py
- gwpy/types/tests/test_array.py
This PR introduces a refactoring of the `gwpy.timeseries.io.gwf.framecpp` module, and introduces support for applying (or not) the bias/slope calibration when reading ADC data from GWF files (fixes #749.
> Refactored frameCPP timeseries I/O module

- gwpy/timeseries/io/gwf/framecpp.py
This PR fixes a significant speed regression introduced by #924.
> Fixed optimisation regression in framecpp.py

- gwpy/io/nds2.py
This PR improves the `gwpy.io.nds2.get_availability` wrapper by calling out to `find_channels` to map the users names to real names in the NDS database.
> Fixed nds2 get_availability name mapping using find_channels

- gwpy/utils/mp.py
This PR works around an apparent bug in (old versions of) tqdm that would cause errors like the following when querying for segments:
```pytb
File "/home/duncan.macleod/opt/gwpysoft-2.7/lib/python2.7/site-packages/gwpy/segments/flag.py", line 1601, in populate
on_error=on_error, **kwargs)
File "/home/duncan.macleod/opt/gwpysoft-2.7/lib/python2.7/site-packages/gwpy/segments/flag.py", line 1087, in query
return query_(flags, *args, **kwargs)
File "/home/duncan.macleod/opt/gwpysoft-2.7/lib/python2.7/site-packages/gwpy/segments/flag.py", line 1241, in query_dqsegdb
raise result
AttributeError: 'tqdm' object has no attribute 'pos' [H1:DCH-PSL_ISS_OMICRON_SNR_GT_45:1]
```
I think this has something to do with the fact that both gwpy and tqdm are threading at …
> Only actually use tqdm in verbose mode

- gwpy/detector/units.py
- gwpy/timeseries/io/gwf/framecpp.py
This PR fixes some bugs when reading GWF with/without ADC scaling (see #924).
> Fixed errors applying ADC calibration when reading GWF

- gwpy/io/cache.py
- gwpy/io/datafind.py
- gwpy/io/tests/test_cache.py
- gwpy/io/tests/test_datafind.py
- gwpy/timeseries/core.py
- gwpy/timeseries/io/cache.py
This PR adds support for auto-discovery of data on the Virgo file system (Cascina) by supporting reading FFL files, and auto-discovery of those files under the `/virgoData` partition.
Fixes #748.
cc @basswinkels
> Added support for discovering and reading Virgo FFL files

- gwpy/table/io/gravityspy.py
- gwpy/table/io/sql.py
> Fixing both the scraping of env at load and the error you get if you perform a sql query that returns an empty result

- gwpy/plot/plot.py
> Fixed bug in Plot.show

- gwpy/timeseries/io/gwf/framecpp.py
This PR fixes #1004 by patching `gwpy.timeseries.io.gwf.framecpp` to remove calls to `FrTOC.GetADC` and friends. Simple testing suggests ~30% speed up in reading one channel from one `L1_R` file, which is nice.
In practice, it should mean that using the `type` keyword argument, which used to be a necessary extra to minimise memory overhead, should be unnecessary.
> Use brute force frdata structure access with frameCPP

- gwpy/io/datafind.py
This PR fixes a bug in the aforementioned function which meant trend types weren't prioritised properly (or at all).
> Fixed bug in gwpy.io.datafind.find_frametype

- gwpy/cli/cliproduct.py
- gwpy/cli/spectrum.py
- gwpy/cli/timeseries.py
The argument has been defined but not used. This fix is implemented in the make-plot method in each derived product class that has time on the X-axis.  Trying to do it in the base class had weird side effects
> Implement --legends arguments in gwpy-plot

- gwpy/timeseries/io/gwf/framecpp.py
This PR fixes a bug where `TimeSeries` read from GWF would be returned with an empty `name` attribute, because the `FrVect` structure is not required to have that populated.
The fix is to take the name from the `FrAdcData` (or similar) structure, which is the canonical location for that string anyway.
cc: @alurban
> Take series name from FrData structure when reading from GWF

- gwpy/detector/io/clf.py
This PR implements a minor improvement to the `read` function for LIGO Channel List Files (CLFs).
> Minor improvement to reading channel list files

- ci/install-conda.sh
- gwpy/timeseries/tests/test_timeseries.py
- requirements-dev.txt
This PR fixes a couple of issues in testing
- fixed one bug in the test suite
- added some more dev dependencies
These should help test coverage.
> Fixed a few misc issues with the CI tests

- .circleci/config.yml
- .travis.yml
- ci/install-conda.sh
- ci/install-pip.sh
- ci/test.sh
- gwpy/io/tests/test_cache.py
- gwpy/plot/tests/test_plot.py
- gwpy/plot/tests/test_segments.py
- gwpy/signal/tests/test_spectral_median_mean.py
- gwpy/table/tests/test_table.py
- gwpy/timeseries/tests/test_timeseries.py
- gwpy/utils/tests/test_mp.py
This PR moves all linux-based CI jobs onto circle-ci; the use of docker images on that platform should speed things up.
> Moved all Linux CI jobs over to CircleCI

- .travis.yml
- ci/install-conda.sh
- ci/parse-conda-requirements.py
- requirements-dev.txt
- requirements-doc.txt
This PR attempts to fix the broken conda builds on macOS, related to package conflicts.
> Fix issues with macOS conda builds

- gwpy/table/gravityspy.py
- gwpy/table/tests/test_gravityspy.py
Also I correct some egregious use of camel case. This is not critical for O3 release as old column names will exist in new table and vice versa. But it is better and more up to date.
Scotty
> This allows downloaded images based on new table column naming scheme

- gwpy/timeseries/io/losc.py
- gwpy/timeseries/tests/test_statevector.py
- gwpy/timeseries/tests/test_timeseries.py
- requirements.txt
- setup.py
This PR updates gwpy to match gwosc-0.4.0, which implements a new API for open data.
> Updates for gwosc-0.4.0

- gwpy/timeseries/io/losc.py
This PR fixes an annoying bug in printing verbose messages during `fetch_open_data`.
> Fixed annoying bug in verbose message

- gwpy/timeseries/core.py
- gwpy/timeseries/io/losc.py
This PR fixes two small things related to the gwosc API:
- updated default host to pull from API
- added 'dataset' to the list of kwargs passed to find_urls
> Minor updates to gwosc API

- gwpy/io/mp.py
- gwpy/segments/io/hdf5.py
- gwpy/segments/tests/test_flag.py
- gwpy/segments/tests/test_segments.py
This PR fixes one bug, and one 'feature':
- [440943b] fixed bugs in format discovery in `gwpy.io.mp.read_multi`
- [245d030] enabled reading `DataQualityFlag` directly from `h5py.Group` object
> Fixed some corner cases with I/O

- .appveyor.yml
- gwpy/plot/gps.py
- gwpy/plot/tests/test_gps.py
This PR fixes issues with dynamic scaling when plotting GPS scales (again).
| Before | After |
| ------ | ----- |
| ![before](https://user-images.githubusercontent.com/1618530/55417374-7c302300-5568-11e9-96b9-199d3cee0a7a.png) | ![after](https://user-images.githubusercontent.com/1618530/55417377-7d615000-5568-11e9-8ed9-9b1d7bb40c33.png) |
> Fixed GPS scaling issue again

- docs/spectrum/io.rst
- gwpy/frequencyseries/frequencyseries.py
- gwpy/frequencyseries/tests/test_frequencyseries.py
- gwpy/types/io/ligolw.py
This PR fixes the `LIGO_LW` XML `<Array>` element reader for `Series`
- fixed understanding of how the format is structured
- improved documentation of kwargs
- improved testing
> Updated LIGO_LW XML <Array> reader

- docs/dev/release.rst
This PR updates the `/dev/release.html` docs page for the new stable mainline branching model.
> Updated release guide for stable mainline

- .circleci/config.yml
- gwpy/__init__.py
- gwpy/detector/channel.py
- gwpy/frequencyseries/frequencyseries.py
- gwpy/io/datafind.py
- gwpy/io/tests/test_datafind.py
- gwpy/plot/axes.py
- gwpy/plot/bode.py
- gwpy/plot/rc.py
- gwpy/plot/segments.py
- gwpy/plot/tests/test_bode.py
- gwpy/segments/io/hdf5.py
- gwpy/segments/segments.py
- gwpy/timeseries/core.py
- gwpy/timeseries/io/gwf/__init__.py
- requirements-test.txt
This PR restructures some module-level imports in an attempt to speed up loading modules.
Fixes #1118 (sort of) - any remaining slow loading is unfortunately a consequence of heavy dependency on numpy, scipy, astropy, and matplotlib, each of which are a bit slow to load resulting in an overall large overhead for gwpy.
> Optimised imports to speed up module loading

- .appveyor.yml
- ci/install-conda.sh
- ci/parse-conda-requirements.py
- gwpy/timeseries/tests/test_timeseries.py
- gwpy/utils/tests/test_decorators.py
- requirements-dev.txt
- requirements-test.txt
This PR fixes a few issues related to the release of pytest-5.0.0, which is python3 only, and exposes a couple of bugs in some test code to do with error message handling.
> A few compatibility fixes for pytest-5

- .circleci/config.yml
- docs/install/index.rst
- gwpy/table/tests/test_table.py
- requirements-dev.txt
- setup.py
This PR fixes up some test failures when running with `numpy-1.17.0rc1`, see astropy/astropy#8976.
> Update gwpy.table test code for numpy-1.17

- .appveyor.yml
- .circleci/config.yml
- docs/_static/css/gwpy-sphinx.css
- docs/conf.py
- gwpy/astro/range.py
- gwpy/frequencyseries/_fdcommon.py
- gwpy/frequencyseries/frequencyseries.py
- gwpy/frequencyseries/hist.py
- gwpy/plot/axes.py
- gwpy/plot/plot.py
- gwpy/plot/segments.py
- gwpy/segments/flag.py
- gwpy/signal/filter_design.py
- gwpy/signal/qtransform.py
- gwpy/spectrogram/spectrogram.py
- gwpy/table/io/gwf.py
- gwpy/table/io/ligolw.py
- gwpy/table/table.py
- gwpy/timeseries/core.py
- gwpy/timeseries/statevector.py
- gwpy/timeseries/timeseries.py
- gwpy/types/array.py
- gwpy/types/series.py
- gwpy/types/sliceutils.py
This PR improvements docs builds by fixing a few small issues, most notably the usage of `See also` sections in docstrings.
> Small fixes to the documentation

- gwpy/signal/qtransform.py
- gwpy/timeseries/tests/test_timeseries.py
> Raise exception on a corner case in Q-transforms

- gwpy/conftest.py
- gwpy/testing/fixtures.py
This PR improves the detection of a working LaTeX configuration by generating an empty figure with matplotlib and usetex when setting up the test suite.
> Improve detection of working usetex

- debian/copyright
- setup.py
This PR just updates some package metadata in `setup.py` and `debian/copyright`. The `setup.py` stuff is just to embellish make the PyPI page for GWpy (see [matplotlib](https://pypi.org/project/matplotlib/) for an example of the extra `project_urls`).
> Some metadata updates

- gwpy/timeseries/timeseries.py
> Fix typo in TimeSeries.asd docs

- gwpy/signal/spectral/_lal.py
- gwpy/signal/spectral/_ui.py
- gwpy/signal/tests/test_spectral_ui.py
This PR fixes at least two critical issues with handling windows passed to functions in `gwpy.signal`, mainly related to passing windows as arrays.
> Fix bugs in gwpy.signal related to window handling

- ci/test.sh
- gwpy/table/tests/test_table.py
This PR fixes test failures relating to mocking of SQL outputs using `sqlparse-0.3.1`.
> Fix test mocks for sqlparse-0.3.1

- .appveyor.yml
- .circleci/config.yml
- .travis.yml
- CONTRIBUTING.md
- debian/control
- debian/rules
- etc/spec.template
- gwpy/detector/tests/test_channel.py
- gwpy/io/tests/test_nds2.py
- gwpy/utils/tests/test_enum.py
- requirements.txt
- setup.py
- setup_utils.py
This PR removes python2 package definitions and CI jobs.
Fixes #1168.
> Remove python2 packages and builds

- .circleci/config.yml
This PR adds a circleci test job for python3.8.
> Add python3.8 test job

- gwpy/io/tests/test_datafind.py
- gwpy/timeseries/tests/test_timeseries.py
This PR introduces a few updates to the tests of `gwpy.io.datafind`, with no functional changes.
> Update to datafind tests

- gwpy/conftest.py
- gwpy/table/io/utils.py
This PR fixes two code style issues that are only exposed with (the newly released) `flake8 >=3.8.0`.
> Fix two lint issues

- .circleci/config.yml
- docs/install/index.rst
- gwpy/conftest.py
- gwpy/plot/plot.py
- gwpy/plot/tests/test_axes.py
- gwpy/table/tests/test_table.py
- gwpy/timeseries/core.py
- gwpy/types/series.py
- requirements.txt
- setup.py
This PR merges the latest changes from `master` onto the 2.0.x release branch, in preparation for the 2.0.1 release.
> Merge master into 2.0.x release branch

- gwpy/detector/tests/test_channel.py
- gwpy/utils/tests/test_mp.py
This PR fixes a [test failure](https://travis-ci.com/github/gwpy/gwpy/jobs/394114669) by mocking out another URL request.
> Fix test failure by adding another mock

- gwpy/detector/tests/test_channel.py
- gwpy/io/datafind.py
- gwpy/io/gwf.py
- gwpy/plot/axes.py
- gwpy/plot/tests/test_axes.py
- gwpy/table/io/ligolw.py
- gwpy/table/tests/test_table.py
- gwpy/timeseries/tests/test_timeseries.py
- gwpy/types/io/ligolw.py
- gwpy/utils/tests/test_mp.py
This PR cherry-picks the changes from #1269, #1270, #1278, #1279, and #1281 to update the release/2.0.x branch ready for a 2.0.2 release.
> Update 2.0.x release branch for 2.0.2

- gwpy/timeseries/tests/test_timeseries.py
This PR hardcodes the PSD `method` argument in all appropriate `TimeSeries` test functions, mainly to resolve deprecation warnings, but also so that the tests are a bit more robust.
cc @alurban
> Hardcode PSD method in all TimeSeries tests

- gwpy/table/io/losc.py
This PR improves the auto-parsing of units in event tables downloaded from GWOSC as part of `EventTable.fetch_open_data`. In practice this means that the `_lower` and `_upper` columns now share the same unit as the main column for the relevant parameter, previously those columns didn't have a unit.
> Improve unit parsing for GWOSC tables

- docs/plot/filter.rst
This PR updates the documentation example for the `BodePlot` to something that actually works.
> Update documentation example code for `BodePlot`

- .github/workflows/dependencies.yml
- gwpy/io/gwf.py
- gwpy/io/kerberos.py
- gwpy/io/registry.py
- gwpy/io/tests/test_kerberos.py
- gwpy/plot/tests/test_tex.py
- gwpy/plot/tex.py
- gwpy/table/io/fetch.py
- gwpy/timeseries/core.py
- gwpy/timeseries/io/gwf/framel.py
- gwpy/timeseries/statevector.py
- gwpy/timeseries/tests/test_timeseries.py
- gwpy/utils/shell.py
- gwpy/utils/tests/test_shell.py
- setup.cfg
This PR merges the changes from the following PRs onto the release/2.1.x branch to finalise the [2.1.2](https://github.com/gwpy/gwpy/milestone/53?closed=1) release:
- #1411
- #1423
- #1425 
- #1433
- #1435
> Update 2.1.x release branch for 2.1.2

- gwpy/table/io/ligolw.py
This PR restructures the way that the myriad `ilwdchar` type objects are imported, mainly to fix compatibility with python-ligo-lw 1.8.0; the latest version of that library doesn't include any ilwd stuff at all, so we need import protections.
> Restructure imports of ilwdchar

- gwpy/segments/tests/test_flag.py
- gwpy/table/tests/test_table.py
This PR improves the test suite (IMO) by replacing some usage of `tempfile.NamedTemporaryFile` with the `tmp_path` fixture from pytest. This is intended to make the tests more readable.
In the process I ended up refactoring the monolithic I/O tests for the `hdf5.pycbc_live` and `hdf5.snax` I/O formats.
cc @myNameIsPatrick for a review of the `hdf5.snax` test changes.
> Use pytest's tmp_path fixture instead of tempfile.NamedTemporaryFile

- examples/test_examples.py
- pyproject.toml
This PR improves the pytest harness for the examples (`examples/test_examples.py`)
> Improvements to the pytest harness for the examples

- gwpy/types/series.py
> Resolve "Bug in Series index comparison"

- gwpy/table/io/gravityspy.py
Updating the name of the gravity spy server that hosts the glitch tables
> Updating the name of the gravity spy server that hosts the glitch tables

- .codecov.yml
This PR cleans up the codecov configuration, mainly adding comments in the config file itself.
> Improve the codecov configuration

- examples/frequencyseries/percentiles.py
- gwpy/frequencyseries/frequencyseries.py
- gwpy/signal/filter_design.py
- gwpy/signal/spectral/_pycbc.py
- gwpy/signal/tests/test_window.py
- gwpy/signal/window.py
- gwpy/table/tests/test_table.py
- gwpy/timeseries/io/losc.py
- gwpy/timeseries/tests/test_timeseries.py
- gwpy/timeseries/timeseries.py
- gwpy/utils/misc.py
- gwpy/utils/tests/test_misc.py
This PR merges the changes from the following PRs onto the release/2.1.x branch to finalise the [2.1.5](https://github.com/gwpy/gwpy/milestone/57) release:
- #1521 
- #1523
- #1530
> Update 2.1.x release branch for 2.1.5

- docs/detector/channel.rst
- docs/segments/index.rst
- docs/table/io.rst
> Minor doc changes

- gwpy/cli/cliproduct.py
- gwpy/cli/gwpy_plot.py
- gwpy/cli/tests/base.py
- gwpy/cli/tests/test_transferfunction.py
- gwpy/cli/transferfunction.py
Replace a simple Plot with BodePlot for plotting the magnitude and phase of a transfer function measurement
Closes #1526
> Fix plotting of transfer function from command line

- .github/workflows/conda.yml
- .github/workflows/dist.yml
- pyproject.toml
This PR test jobs for Python 3.11.
> Add CI tests for Python 3.11

- .github/workflows/conda.yml
- .github/workflows/dist.yml
- gwpy/cli/cliproduct.py
- gwpy/io/ligolw.py
- gwpy/io/tests/test_ligolw.py
- pyproject.toml
This PR cherry picks the changes from the following PRs onto the `release/3.0.x` branch to finalise the [3.0.2](https://github.com/gwpy/gwpy/milestone/62) release:
- #1555
- #1568 
- #1570
> Update 3.0.x release branch for 3.0.2

- .github/workflows/lint.yml
This PR adds some debugging information for the `rstcheck` CI job.
> Print installed packages in rstcheck env

- gwpy/timeseries/core.py
- gwpy/timeseries/io/losc.py
This PR cherry picks the changes from the following PRs onto the release/3.0.x branch to finalise the [3.0.4](https://github.com/gwpy/gwpy/milestone/64) release:
- #1606
> Update 3.0.x release branch for 3.0.4

- gwpy/frequencyseries/_fdcommon.py
- gwpy/plot/bode.py
- gwpy/signal/filter_design.py
- gwpy/signal/tests/test_filter_design.py
- gwpy/timeseries/timeseries.py
parse_filter previously converted analog filters to digital. This MR extracts this responsibility out into a separate function.
> Extract analog to digital filter conversion out of parse_filter 

- gwpy/types/series.py
- gwpy/types/tests/test_series.py
see https://github.com/gwpy/gwpy/issues/1659
> raise an exception if xindex has different length to data

- gwpy/timeseries/core.py
- gwpy/timeseries/tests/test_timeseries.py
This PR resolves a failing test of `TimeSeriesDict.find` by updating the tests of that method. I also include a second commit that improves the docstring for the method and improves the layout of that code to make it more readable.
The resulting change should introduce no API changes, and only minor behavioural changes (different exception type for failing to parse the IFO from some channels names, which is basically legacy code now anyway).
> Improve tests of TimeSeriesDict.find error handling

- gwpy/io/cache.py
This PR silences annoying LAL debug warnings related to attempting to parse a cache as either Virgo-style FFL or LAL format.
The new contextmanager function may be useful more generally, but I haven't found a use case for that _right now_ so left the implementation in the current overly-specific place.
Closes #1681.
> Silence LAL LIGOTimeGPS warnings when parsing a cache

- .github/workflows/dist.yml
- pyproject.toml
This PR adds CI/metadata support for Python 3.12.
Depends on #1715, #1716, #1719.
> Add support for Python 3.12

- gwpy/io/ffldatafind.py
- gwpy/io/tests/test_ffldatafind.py
This PR addresses https://git.ligo.org/computing/helpdesk/-/issues/3841 by adding support for parsing multiple FFLs for a single dataset at Virgo.
cc @dethodav
> Add support for parsing multiple FFL files for a given dataset

- gwpy/timeseries/core.py
> Fix bug in `TimeSeriesDict.find`

- docs/citing.rst.in
- docs/conf.py
- docs/timeseries/datafind.rst
This PR replaces the use of `sphinx-panels` for tabbed documentation content with the equivalent solution from `sphinx-immaterial`.
> Replace sphinx-panels tabs with sphinx-immaterial tabs

- gwpy/cli/qtransform.py
Another try to deal with this change necessary because tests for thuthiness are more strict.
> Quick fix reuse of whiten argument issue #1652

- gwpy/utils/tests/test_sphinx_zenodo.py
This PR adds a handler for tests of `gwpy.utils` that fail because they hit a Zenodo rate limit, since those are not indicative of an actionable failure in the code itself.
> Skip tests that fail on Zenodo rate limit

- gwpy/spectrogram/tests/test_spectrogram.py
- gwpy/testing/utils.py
- gwpy/timeseries/tests/test_timeseries.py
- gwpy/types/array.py
- gwpy/types/index.py
This PR fixes issues with copying arrays as needed in numpy 2.0.
> Fix array copy compatibility with numpy 2

- gwpy/astro/range.py
- gwpy/astro/tests/test_range.py
- gwpy/cli/qtransform.py
- gwpy/detector/units.py
- gwpy/io/datafind.py
- gwpy/io/ffldatafind.py
- gwpy/io/tests/test_ffldatafind.py
- gwpy/plot/tex.py
- gwpy/signal/filter_design.py
- gwpy/signal/tests/test_filter_design.py
- gwpy/spectrogram/tests/test_spectrogram.py
- gwpy/testing/fixtures.py
- gwpy/testing/utils.py
- gwpy/timeseries/io/cache.py
- gwpy/timeseries/io/gwf/lalframe.py
- gwpy/timeseries/tests/test_io_cache.py
- gwpy/timeseries/tests/test_timeseries.py
- gwpy/types/array.py
- gwpy/types/index.py
- gwpy/utils/tests/test_sphinx_zenodo.py
- pyproject.toml
This PR updates the 3.0.x series release branch to finalise [3.0.9](https://github.com/gwpy/gwpy/milestone/69):
- #1616
- #1637
- #1641 
- #1747 
- #1749 
- #1753
- #1755
- #1760 
- #1762 
- NOTE: this is only partially applied, as part of the changes build upon #1632 which is scheduled for 3.1.0.
- #1763 
- #1764 
- #1765
> Update release branch for 3.0.9
