.travis.yml, gwpy/tests/detector.py, gwpy/tests/segments.py, gwpy/tests/timeseries.py, setup.py
This PR adds the backport `unittest2` module as a `tests_require` dependency in `setup.py`.
This should fix #34.
=> Fix unittests on python2.6

.travis.yml, gwpy/detector/channel.py, gwpy/tests/detector.py
Old LIGO FMCS channels have odd prefixes, but are still valid channels, e.g.
```
'LVE-EX:X3_810BTORR.mean,m-trend'
```
This PR introduces a unittest to make sure these channels can be parsed, and amends the `Channel.MATCH` regular expression to allow custom prefixes.
This should fix #31.
=> Allow custom IFO prefix for Channels

gwpy/io/nds.py, gwpy/tests/io.py, gwpy/timeseries/core.py
This PR introduces the `epoch` keyword argument to the NDS2 server selection algorithm (`gwpy.io.nds.host_resolution_order`). Additionally, this introduces a series of related unittests.
This fixes #27.
=> GPS epoch-based server selection

gwpy/cli/cliproduct.py
The linked commit hacks around bug #37 by catching the `NotImplementedError` raised by mpl < 1.4 and simply hiding the legend instead. I've tested generating the examples for the documentation, and things look fine.
@areeda, without thorough testing, can you tell me whether this is good enough. I'd rather not place a hard requirement on matplotlib >= 1.4 just yet.
This PR fixes #37.
=> Fix for legend.remove() bug with matplotlib < 1.4

gwpy/io/cache.py, gwpy/table/io/ascii.py, gwpy/table/io/omega.py, gwpy/table/utils.py
This PR introduces a new generic ASCII row reader method, which is registered to read white-space delimiter ASCII and comma-separated csv files for all `LIGO_LW` tables.
This PR fixes #42.
=> New generic ASCII reader for LIGO_LW tables

gwpy/cli/coherence.py, gwpy/cli/timeseries.py
This PR fixes a python2.6/matplotlib bug where astropy Quantities are pushed through the matplotlib units interface, resulting in a `SystemError`.
This single commit just makes sure a couple of `set_ylim` calls receive float-like objects, and not Quantities.
=> cli: fixes for matplotlib units error on py26

examples/spectrogram/spectrogram2.py, gwpy/timeseries/core.py
This PR introduces a new over-dense spectrogram method for calculating and displaying short-duration spectrograms. Also included is a new example, with the following code:
```python
from gwpy.timeseries import TimeSeries
gwdata = TimeSeries.fetch('L1:OAF-CAL_DARM_DQ', 'Feb 28 2015 06:02:05', 'Feb 28 2015 06:02:10')
specgram = gwdata.spectrogram2(fftlength=0.15, overlap=0.14) ** (1/2.)
medratio = specgram.ratio('median')
plot = medratio.plot(norm='log', vmin=0.5, vmax=10)
plot.set_yscale('log')
plot.set_ylim(40, 8192)
plot.add_colorbar(label='Amplitude relative to median')
plot.set_title('L1 $h(t)$ with noise interference')
plot.show()
```
which produces the following output:
There are minor problems with precision errors making their way up to determine the length of the spectrogram, but …
=> New over-dense spectrogram method (TimeSeries.spectrogram2)

gwpy/cli/spectrogram.py
This PR fixes bugs in the usage of `numpy.min` and `numpy.max` by using the python builtin functions or the `numpy.ndarray` instance methods instead.
This fixes #48.
=> cli.spectrogram: fix usage of numpy.{min,max}

gwpy/timeseries/core.py
This PR fixes #30 by adding sanity checks on stride, fftlength, and overlap in the `TimeSeries.spectrogram{2}` methods.
=> TimeSeries.spectrogram{2}: added parameter check

docs/ex2rst.py, docs/timeseries/filtering.rst, examples/timeseries/filter.py, gwpy/spectrogram/core.py, gwpy/spectrum/core.py, gwpy/timeseries/core.py
The current `TimeSeries.filter` time-domain filtering requires the user to give digital, Z-domain filter components. This PR implements a `TimeSeries.zpk` method which translates real zpk components in Hertz into S-domain then Z-domain and passes to `TimeSeries.filter`.
I have also included the relevant changes to documentation, and a new example for time-domain filtering.
=> Improvements to time-domain filtering

gwpy/tests/detector.py
This PR introduces a catch to the `Channel` `test_query` test, which would fail whenever the CIS host (`cis.ligo.org`) is unavailable.
=> Fix for tests failing when CIS fails to respond

gwpy/cli/spectrogram.py
This uses median for normalization and chooses between spectrogram and spectrogram2 based on the number of FFTs calculated
=> cli/spectrogram.py: add option for high time res spectrograms

gwpy/plotter/segments.py
This PR changes the default colours for the `SegmentAxes.plot_dqflag` method to `active` = 'green', and `known' = 'red'.
This fixes #53.
=> Set default colours for SegmentAxes.plot_dqflag

gwpy/segments/flag.py
This PR implements a new unified `DataQuality{Dict,Flag}.query()` method.
The old `query()` method is renamed to `query_segdb()`, and the new method selects either `query_segdb()` or `query_dqsegdb` depending on the value of the `url` kwarg.
This fixes #54.
=> Unified DataQuality{Dict,Flag}.query method

gwpy/cli/coherence.py
This implements the reference channel parameter.
Before we depended on ldvw to put the reference channel first but Marissa noticed that wasn't working prperly sometimes.  So instead of fixing ldvw first.  I thought it best to implement it in the command line program since that is probably the way people will expect when using the command line programs outside of ldvw.
=> Cli coh ref chan

docs/Makefile, docs/conf.py, gwpy/spectrum/core.py, gwpy/timeseries/core.py
This PR introduces two new methods for each of the `TimeSeries` and `Spectrum` objects:
- `to_pycbc` convert to the relevant PyCBC objects
- `from_pycbc` convert from the relevant PyCBC objects
This includes the relevant links to the PyCBC sphinx documentation.
=> First steps in PyCBC integration

gwpy/cli/spectrogram.py
I missed one the last time.  This one is with the labeling of
normalized as releative to median.
=> cli/spectrogram.py: another merge conflict,

examples/spectrogram/coherence.py, examples/spectrum/coherence.py
This PR introduces two new examples, one for `TimeSeries.coherence` and the other for `TimeSeries.coherence_spectrogram`.
All choices for data and times were ruthlessly copied from Joe's CLI examples.
=> Two new examples: coherence and coherence_spectrogram

gwpy/astro/range.py, gwpy/cli/coherence.py, gwpy/cli/coherencegram.py, gwpy/cli/spectrogram.py, gwpy/cli/spectrum.py, gwpy/cli/timeseries.py, gwpy/data/array.py, gwpy/data/array2d.py, gwpy/data/series.py, gwpy/io/ascii.py, gwpy/plotter/filter.py, gwpy/plotter/histogram.py, gwpy/plotter/html.py, gwpy/plotter/spectrum.py, gwpy/plotter/timeseries.py, gwpy/spectrogram/coherence.py, gwpy/spectrogram/core.py, gwpy/spectrogram/spectrogram.py, gwpy/spectrum/core.py, gwpy/spectrum/hist.py, gwpy/spectrum/psd.py, gwpy/spectrum/scipy_.py, gwpy/tests/array.py, gwpy/tests/astro.py, gwpy/tests/timeseries.py, gwpy/timeseries/common.py, gwpy/timeseries/core.py, gwpy/timeseries/io/gwf/framecpp.py, gwpy/timeseries/statevector.py, gwpy/utils/lal.py
This PR introduces a complete re-build of the `Array` class and all sub-classes, including `TimeSeries`, `Spectrum`, and `Spectrogram`. The changes are (at least) as follows:
- `Array` now inherits from `astropy.units.Quantity` rather than from `numpy.ndarray`,
- all unit handing is now much easier, with most of it handled directly by `Quantity`,
- the `unit` property cannot be set for an array that already has a unit, a notice has been added to the exception message to ask the user to use the `Array.to()` method, which properly converts between units,
- the `data` property has been removed in favour of the `Quantity.value` property. `data` was a bad choice to begin with as it overrode a `numpy.ndarray` property,
- `Array2D` now inherits from `Series`,
- the `times` and `frequencies` …
=> Rebuild of Array and sub-classes

gwpy/timeseries/common.py, gwpy/timeseries/statevector.py
This PR fixes some bugs with the new `Quantity`-based `StateVector`.
Astropy doesn't like setting `Quantity` array values via slices with `uint32`, so we can circumvent that for now.
=> Statevector fixes

gwpy/timeseries/core.py
This PR fixes bugs in the `TimeSeries.resample` and `TimeSeries.pad` methods where the metadata `__dict__` isn't copied over to the new array after a `view` is performed on a `numpy.ndarray`.
=> Copy TimeSeries.__dict__ after view()

gwpy/data/series.py, gwpy/spectrum/core.py, gwpy/timeseries/core.py
This PR fixes problems with passing the `xindex` kwarg to a `Series`, or equivalently `frequencies` to a `Spectrum` or `times` to a `TimeSeries.
=> Bug fixes in Series xindex setting

examples/timeseries/statevector.py, gwpy/data/array2d.py, gwpy/data/series.py, gwpy/detector/channel.py, gwpy/spectrum/core.py, gwpy/spectrum/lal_.py, gwpy/time/__init__.py, gwpy/timeseries/__init__.py, gwpy/timeseries/common.py, gwpy/timeseries/core.py, gwpy/timeseries/io/cache.py, gwpy/timeseries/io/gwf/framecpp.py, gwpy/timeseries/statevector.py
This PR introduces a number of critical optimisations for routines in GWpy. The summary is as follows:
- `gwpy.segments` is now only imported at the function level for `Channel` objects and all `Array` sub-classes (include, e.g, `TimeSeries`) - this import is slow because it relies on `gwpy.table.ligolw` imports
- `TimeSeries.read(format='framecpp') now intelligently handles accessing the TOC for a frame, and does it as seldom as possible
- `TimeSeries.spectrogram` now calculates a single window function up-front, rather than passing the default argument and having `scipy` recalculate the window function every time `welch` is called
- `TimeSeries.read(cache)` will now try to use `lalframe`-based serial access for up to 4 channels since `lalframe` is much faster than `frameCPP.py` - this …
=> Multiple optimisations for TimeSeries methods

gwpy/plotter/core.py
This PR fixes #85 whereby calling `Plot.add_timeseries` or similar on a `Plot` with axes that weren't subplots (e.g. colorbars) raised an exception.
Additionally, this PR implements `sharex` and `sharey` kwargs to the `Plot.add_*` methods.
=> Fixed problem adding new axes to figures with colorbars

gwpy/timeseries/io/gwf/__init__.py, gwpy/timeseries/io/gwf/framecpp.py, gwpy/timeseries/io/gwf/lalfr.py, gwpy/timeseries/io/gwf/lalframe.py, gwpy/utils/lal.py
This PR refactors the LALFrame wrappers to be much more similar to those for frameCPP.
Recent LALFrame updates allow for multi-channel reading, meaning the interface for LALFrame can be identical to that of frameCPP.
As a result the independent content of the two sets of wrappers has been greatly reduced, providing only a method to read a `TImeSeriesDict`. Conversions to other datatypes (e.g. `StateVector`) is now handled by a factory method.
=> Reworking of LALFrame wrappers

gwpy/timeseries/io/gwf/framecpp.py
This PR adds a workaround to failures when frameCPP fails to find the `numpy/arrayobject.h` headers. In this case `FrVect.GetDataArray()` just returns a raw `buffer` so we need to convert into an `ndarray` by hand.
This PR adds the following:
- `FrVect` -> `numpy` type mapping `dict`
- `isinstance` check for output of `GetDataArray` and subsequent call to `numpy.frombuffer`
=> Workaround frameCPP not picking up numpy headers

gwpy/io/cache.py, gwpy/timeseries/io/cache.py, gwpy/timeseries/io/gwf/__init__.py, gwpy/timeseries/io/gwf/identify.py
This PR introduces two enhancements to the `TimeSeries.read()` functionality for GWF input
- added the `format` kwarg to the `timeseries.io.cache.read_cache` method, allowing the frame library readers to call back to the cache reader when a user specifies `nproc > 1`
- re-enabled auto-identification of GWF files, the order of library imports means frameCPP will be used by default for GWF reading
=> Improvements to GWF reading

gwpy/timeseries/common.py
This PR fixes #95 by correcting a problem with integer division `//` used in the `timeseries.common.crop` operation.
=> Fixed bug in TimeSeries.crop

gwpy/table/io/trigfind.py, gwpy/table/lsctables.py
This PR adds an error condition to `table.io.trigfind.find_trigger_urls` (used by `SnglBurstTable.fetch`) when a channel-level directory is not found, meaning this channel has never been processed by the given ETG.
This fixes #72.
=> table.io.trigfind: raise exception if no channel directory

gwpy/time/_tconvert.py
This PR improves the functionality of `gwpy.time.to_gps` by allowing conversions from `str` to `float`, rather than passing into `dateutil`.
=> time.to_gps: convert str to float if possible

gwpy/timeseries/core.py, gwpy/timeseries/io/cache.py, gwpy/timeseries/io/gwf/__init__.py, gwpy/timeseries/statevector.py
This PR introduces an extension to the `TimeSeries.read()` cache methods to pad gaps in the cache with a given value.
This PR fixes #69 and fixes #97.
=> Patched TimeSeries.read to pad gaps in cache

gwpy/table/io/ascii.py, gwpy/table/lsctables.py
This update corrects the handling of keyword arguments for reading LIGO_LW tables from ASCII. This fixes #71.
=> table.io: correctly handle numpy.loadtxt kwargs

.travis.yml, MANIFEST.in, gwpy/__init__.py, gwpy/_version_helper.py, setup.py
This commit moves the vcs.py version generator into a package module, which means it's now importable by other packages
=> vcs.py: moved to module gwpy._version_helper

gwpy/io/ligolw.py, gwpy/segments/flag.py, gwpy/tests/segments.py
This PR fixes a few problems with parsing and operating on veto definer files via the `DataQualityDict` object.
Most of the changes are to enable handling infinities in the query methods, by default a `veto_definer` entry may have an `end_time` of 0 meaning 'endless definition', but the segment logic will always reverse that, which is a bit annoying.
=> Fixes for DataQualityDict.from_veto_definer_file

gwpy/io/ligolw.py, gwpy/io/utils.py, gwpy/segments/io/ligolw.py, gwpy/table/io/__init__.py, gwpy/table/io/ascii.py, gwpy/table/io/cwb.py, gwpy/table/lsctables.py, gwpy/tests/table.py
This PR introduces a new 'cwb-ascii' I/O format for the `SnglBurstTable` to read `EVENTS.txt`-format files from the coherent waveburst analysis.
Attached are some improvements to the associated `gwpy.table` module, and a new test case.
=> New cWB->SnglBurstTable ASCII parser

gwpy/segments/flag.py, gwpy/tests/test_segments.py
This PR fixes a critical bug in `DataQualityFlag.query_dqsegdb` where the results for a multi-segment query would only return those for the final segment.
This PR includes a simple unit test to protect against regression.
=> Bug fix for multisegment dqsegdb query

gwpy/table/io/cwb.py
This commit adds a new generic 'cwb' I/O format for the SnglBurstTable, which will intelligently select 'cwb-ascii' or 'cwb-root' (notimplementerror) based on the file extensions given
=> New generic 'cwb' SnglBurstTable format

gwpy/plotter/table.py
This PR fixes a problem with the `EventTableAxes` class whereby it would inherit all defaults from `TimeSeriesAxes`, even if not being displayed on a `TimeSeriesPlot`.
=> Improved default handling for EventTableAxes

gwpy/io/nds.py, gwpy/segments/flag.py, gwpy/spectrum/registry.py, gwpy/timeseries/core.py, gwpy/timeseries/timeseries.py, gwpy/utils/compat.py
This PR introduces the `gwpy.utils.compat` module to help package objects that are incompatible between python versions.
The only content at this time is the `OrderedDict`, which requires an `ImportError` check for python2.6. All other modules have been modified to import `OrderedDict` from this new module, rather than checking the import themselves.
=> New utils.compat module

.travis.yml, docs/install.rst, setup.py
This PR bumps the minimum required scipy version to 0.16, and astropy to 1.0.
[Scipy 0.16](https://pypi.python.org/pypi/scipy/) is the first version to support second-order-section filter decomposition, so is critical for proper time-domain filtering.
@areeda: can you please review the implications for LDVW and let me know if this change is ok?
=> Bump SciPy requirement to 0.16.0

gwpy/segments/flag.py, gwpy/tests/test_segments.py
This PR introduces the `DataQualityFlag.pad` method, and an associated test case.
This method applies either a `(start, end)` tuple, or reads such a tuple from the `DataQualityFlag.padding` property.
=> New DataQualityFlag.pad method

gwpy/segments/flag.py
This PR improves the automagic segment query method selection based on the url of the segment URL. This is done in two parts
- improve the logic on method selection to use dqsegdb methods for `*.ligo.org` URLs [https://github.com/gwpy/gwpy/commit/5b7d0fe625245b76a9cdb822bb31e4cacf063594]
- move the default server to `https://segments.ligo.org` [https://github.com/gwpy/gwpy/commit/480213ab720920c6609c7e5b4d4fc162ef9f80ac]
=> Segment query selection improvements

gwpy/segments/flag.py
This PR removes all `coalesce()` operations from the `DataQualityFlag` and `DataQualityDict` query methods.
This means that the result of the query should be an ideal representation of the data in the database, and users can manually coalesce things if they want.
=> segments.query: do not coalesce anything

gwpy/plotter/core.py
This PR adds an explicit call to `ax.cla()` for each `Axes` in a given `Plot` when the `Plot.close()` method is called, this might fix a memory leak seen through `gwsumm`.
=> Plot.close: add cla() for each set of axes

gwpy/plotter/gps.py
This PR improves the auto-location of ticks on a calendar time axis as follows
- week scale uses day as minor separator
- day scale uses 4 divisions at whatever major tick scale
=> plotter.gps: improved auto-tick location

gwpy/plotter/gps.py
This PR improves the auto-location of ticks on a calendar time axis as follows
- multiple weeks are now handles intelligently
- months now use 6 minor divisions if major tick is <= 1 months
We should probably rethink the hacky nature of the GPS scaling and look into using matplotlibs built-in date support.
=> plotter.gps: improved auto-tick location [2]

gwpy/segments/flag.py
The `Segment` object will re-order the padding components in increasing order, so we just want to use a simple tuple.
=> DataQualityFlag.padding: don't use Segment as container

gwpy/timeseries/io/cache.py
This PR fixes a bug meaning `StateVector.read` would crash when the `nproc` argument was applied.
=> StateVector.read: fixed bug using nproc

gwpy/segments/io/ligolw.py
This PR fixes a missing import for writing a `DataQualityFlag` to a file-like object with `format='ligolw'`.
=> DataQualityFlag.write: fixed missing import for format='ligolw'

examples/timeseries/whiten.py, gwpy/tests/test_timeseries.py, gwpy/timeseries/timeseries.py
This PR introduces two new methods for the `TimeSeries`:
- `TimeSeries.detrend`: a simple wrapper around `scipy.signal.detrend` to return a `TimeSeries`
- `TimeSeries.whiten`: a function to whiten a `TimeSeries` against its own ASD
The new methods are accompanied by unit tests and a new example for whitening a `TimeSeries` to see glitches at higher frequency.
The example reads in some data from NDS, and whitens it to show two glitches at high frequency, the resulting image is:
=> TimeSeries.whiten: new method

gwpy/tests/test_timeseries.py, gwpy/timeseries/io/gwf/lalframe.py
This PR improves the unit tests for `TimeSeries.read()` to check that each GWF format works with and without the `format` keyword argument being given.
Given that this test currently fails for `format='lalframe'`, subsequent commits will fix the problems with that format.
Thanks to @mattpitkin for his patience in reporting and helping me diagnose the problem.
=> TimeSeries.read: fix bug in reading with default GWF format lalframe

gwpy/spectrogram/core.py
This PR fixes #143 by patching `Spectrogram.crop_frequencies` to reference the correct bandwidth property.
=> Fix bugs in Spectrogram.crop_frequencies

gwpy/data/array.py, gwpy/data/io/__init__.py, gwpy/data/io/hdf5.py, gwpy/segments/io/hdf5.py, gwpy/spectrogram/io/hdf5.py, gwpy/spectrum/io/hdf5.py, gwpy/tests/test_array.py, gwpy/tests/test_timeseries.py, gwpy/timeseries/io/hdf5.py
This PR improves the HDF5-based I/O of `Array` types, mainly by moving the worker code into the new `data.io` module similar to how these things are done for higher-level types.
The subclass types have been modified to import their HDF5 I/O method from this new location, and DeprecationWarnings have been added to the old `Array.to_hdf5` and `Array.from_hdf5` methods.
Finally, the HDF5 I/O tests for the `TimeSeries` have been moved to the `Array` test suite for inheritance by all Array subclasses.
=> Improvements to HDF5-based data I/O

.travis.yml, gwpy/tests/test_detector.py
This PR adds the `dqsegdb` package to the travis build, and updates the URLs for lscsoft packages to point to http://software.ligo.org.
Also included are some trivial travis build changes
=> Added DQSegDB install to travis build

gwpy/data/series.py, gwpy/tests/test_array.py
This PR fixes a bug in the treatment of `Series.xindex` when calling `Series.append`. Fixes were made to the method, and the test suite.
This fixes #148.
=> Fixed bug in Series.append treatment of xindex

gwpy/segments/io/ligolw.py, gwpy/tests/test_segments.py
This PR fixes #160 by patching the method underneath `DataQualityFlag.write` to check against `six.string_types`, not just `str`, allowing `unicode` file names to pass.
There are some `test_segments.py` improvements included to check against future regression.
=> Fixed bug in DataQualityFlag.write(u'<filename>')

gwpy/data/series.py, gwpy/tests/test_array.py
This PR implements an override of `Quantity.diff` in the `Series` class to correctly set the `x0` attribute for the returned array, and so fixes #159, and adds a test of the new method.
=> Added new Series.diff method to correctly set metadata

gwpy/segments/flag.py
This PR fixes the behaviour of coalesce when working with overlapping segments in a list.
=> DataQualityFlag.coalesce: coalesce each list before &

gwpy/timeseries/core.py
This commit fixes a bug whereby a multi-segment fetch (via `pad=xxx`) would raise a ValueError
=> TimeSeriesBaseDict.fetch: fixed bug in pad segments

gwpy/tests/test_timeseries.py, gwpy/timeseries/io/gwf/__init__.py
This PR fixes #163 by adding an explicit exception when encountering an empty `Cache` or `list` in `TimeSeries.read` and friends.
=> Raise ValueError for empty cache in TimeSeries.read and friends

.travis.yml, gwpy/tests/test_time.py, gwpy/time/_tconvert.py
This PR fixes #164 by supporting conversion of `astropy.units.Quantity` objects into floats in seconds before casting to `LIGOTimeGPS`.
I also added new tests for this error, and a bunch of other test lines to improve coverage.
=> Handle Quantities in gwpy.time.tconvert

docs/timeseries/index.rst, examples/spectrogram/coherence.py, examples/spectrogram/plot.py, examples/spectrogram/ratio.py, examples/spectrogram/rayleigh.py, examples/spectrogram/spectrogram2.py, examples/spectrum/coherence.py, examples/spectrum/compare.py, examples/spectrum/hoff.py, examples/spectrum/rayleigh.py, examples/spectrum/transfer_function.py, examples/spectrum/variance.py, examples/timeseries/blrms.py, examples/timeseries/filter.py, examples/timeseries/statevector.py, examples/timeseries/whiten.py, gwpy/detector/channel.py, gwpy/io/datafind.py, gwpy/tests/test_timeseries.py, gwpy/timeseries/core.py
This PR introduces two new data access methods for the `TimeSeries`, `TimeSeriesDict`, and friends:
- `.find()`: use the datafind server to locate frame files containing this channel, then `.read()` them
- `.get()`: intelligently select between `.find()` and `.fetch()` to retrieve the relevant data however possible
Included are tests for these new methods (for the series classes, not the dict classes), and an associated method for the `Channel` class: `Channel.find_frametype` to return those available frametypes that represent the channel.
=> New TimeSeries.{find,get} methods

gwpy/timeseries/timeseries.py
This PR fixes #168 by simplifying the logic in the `TimeSeries.average_fft` method. This is likely only a problem with python2.6 and astropy compatibility.
=> Fixed bug in TimeSeries.average_fft

gwpy/plotter/__init__.py, gwpy/plotter/segments.py, gwpy/plotter/spectrum.py, gwpy/plotter/table.py, gwpy/plotter/timeseries.py
Matplotlib 1.5 introduces a bunch of new colormaps, and some other changes to setting colors. This PR removes all explicit references to the 'jet' colormap in favour of whatever the default is in the `rcParams` structure ('jet' for mpl 1.x, 'viridis' for mpl 2.0).
This PR also fixes a quirk in the `SegmentAxes.draw` meaning mpl 1.5 would draw blue boxes around tick labels.
=> Improved compatibility with matplotlib 1.5

gwpy/io/nds.py, gwpy/tests/test_io.py
This just removes the polling of the default host list from the conditional that checks for the `$NDSSERVER` environment variable, to fix #170.
I think this should be harmless to other users, but I could be wrong.
=> Return more default hosts

gwpy/spectrogram/coherence.py
This commit fixes #179 by fixing a bug in `gwpy.spectrogram.coherence.from_timeseries`.
=> TimeSeries.coherence_spectrogram: fixed bug for nproc

.landscape.yml, gwpy/cli/coherence.py
This PR modifies the landscape.io configuration to ignore errors it doesn't understand in the code.
=> .landscape.yml: added ignore for super-on-old-class

gwpy/spectrum/scipy_.py, gwpy/tests/test_timeseries.py
Fixes #186 which would raise a TypeError when using the bartlett window to make a spectrogram.
=> Bug in bartlett window for spectrograms

gwpy/timeseries/core.py
This commit adds minimal parsing of some `find()`/`read()`-only kwargs when moving to `fetch()` within `TimeSeries.get()`. This allows lazy passing of kwargs.
=> TimeSeries.get: remove known find()-only kwargs for fetch() attempt

gwpy/plotter/spectrum.py, gwpy/plotter/timeseries.py, gwpy/timeseries/core.py, gwpy/timeseries/io/cache.py, gwpy/timeseries/io/gwf/framecpp.py, gwpy/timeseries/timeseries.py
This PR introduces a few optimisations mainly to do with frame reading and spectrogram visualisation:
- `copy()` arrays only when necessary
- use `sparse=True` for meshgrid to save memory
=> Miscellaneous optimisations

gwpy/data/array2d.py, gwpy/data/series.py
This PR introduces two fixes to the `Series` and `Array2D` objects related to handling the index arrays, mainly to support discontiguous indices.
=> Series xindex fixes

gwpy/table/io/omicron.py
This tries to fix a bug in the code that reads triggers from Omicron's ROOT format. The GetEntry method in ROOT needs to be given an index. As it is now, it just gets the same trigger (probably the first, by default) repeatedly.
The fix is simple, but I don't have a good development install of gwpy so I haven't been able to test it.
=> table/io/omicron: Fix bug reading triggers in ROOT file

gwpy/timeseries/core.py, gwpy/timeseries/timeseries.py
This PR removes unnecessary copies of the `TimeSeriesBase.{to,from}_pycbc` methods present in the `TimeSeries` class, and fixes the properties used to extract metadata from the `pycbc.types.TimeSeries` object.
=> Fixed PyCBC TimeSeries conversion

gwpy/tests/test_timeseries.py, gwpy/timeseries/filter.py, gwpy/timeseries/timeseries.py
This PR adds a new module for filtering utilies under the `timeseries` namespace for generating filters, and a new `TimeSeries.notch` instance method to notch out a specific frequency (in Hertz).
=> New TimeSeries.notch method

.travis.yml, gwpy/tests/test_timeseries.py, gwpy/timeseries/timeseries.py
This PR fixes a corner-case bug in the `TimeSeries.spectrogram` function raised when `cross` is used and `method` is not 'welch'.
=> Fixed bug in `TimeSeries.spectrogram`

gwpy/time/_tconvert.py
This method should use LAL routines if available to present 1-second precision loss in the myriad conversions used inside `astropy.time`.
=> time.from_gps: use LAL if available

gwpy/data/array.py, gwpy/detector/channel.py, gwpy/detector/units.py, gwpy/tests/test_array.py, gwpy/tests/test_detector.py, gwpy/timeseries/io/losc.py
This PR introduces an improvement to unit parsing via `astropy.units`. The main addition is a new method `detector.units.parse_unit` which attempts to create a `~astropy.units.Unit` as follows
- as is,
- if it looks like a plural, use the singular
- otherwise attempt to create an `UnrecognizedUnit`
This fixes #176.
=> Improved unit parsing

gwpy/data/__init__.py, gwpy/data/array.py, gwpy/data/array2d.py, gwpy/data/series.py, gwpy/tests/test_array.py
This PR introduces a new method for 1- and 2-d arrays, `value_to`, designed to extract a value at a given index value, e.g. get the value of a `TimeSeries` at a given time.
To make that work, a small set of bug fixes have been made, with improvements to the unit tests. The biggest chance introduced is that the _default_ unit for an `Array` is now `dimensionless`, not `None`.
This fixes #158.
=> New 'value_to' method for arrays

gwpy/plotter/core.py
This PR fixes #207 by creating a figure manager manually if the `new_figure_manager_given_figure` method isn't present in the `backend_mod`.
=> Fixed bug in `Plot`, build manager manually if needed

gwpy/spectrogram/core.py, gwpy/tests/test_spectrogram.py
This PR fixes the `FutureWarning` in `Spectrogram.ratio` when comparing an array to a string.
Also I added a dedicated `TestCase` for the `Spectrogram` that doesn't do much yet.
=> Fixed FutureWarning in Spectrogram.ratio

gwpy/tests/test_timeseries.py, gwpy/timeseries/core.py
This PR introduces the `observatory=None` kwarg for `TimeSeries.find`, allowing users to manually specify the observatory used for the datafind call.
=> Added `observatory` kwarg for TimeSeries.find

.travis.yml, .travis/build-src-dependencies.sh, .travis/build-with-autotools.sh, .travis/run-tests.sh, gwpy/tests/test_cli.py
This PR enables a 'strict' build mode where `py.test` will fail tests that include warnings, and will also stop at the first failure.
=> Add strict build to find warnings

gwpy/data/series.py, gwpy/tests/test_array.py
This PR fixes a bug in `Series.append` when dealing with `xindex` by deleting the input `xindex` unless we have all the information we need, and updating the test suite.
=> Fixed bug in Series.append dealing with xindex

gwpy/plotter/histogram.py, gwpy/tests/test_plotter.py
This PR fixes #220 with a change to the way `float`/`int` weights are parsed in `HistogramAxes.hist`, and adds a test against regression.
=> Fixed bug in `HistogramAxes.hist` parsing of weights as float or int

gwpy/plotter/table.py
This PR fixes a possible `TypeError` when converting a `lal.LIGOTimeGPS` to `glue.lal.LIGOTimeGPS`. This is only manifest when `pylal` is not present on the system.
=> Fixed possible TypeError in EventTableAxes.add_loudest

gwpy/plotter/utils.py, gwpy/tests/test_plotter.py
This PR fixes #224 by adding `'rasterized'` as a keyword argument in `gwpy.plotter.utils` that is used by `Plot.__init__` to separate kwargs between plots and axes.
I also added a unit test against regression.
=> Add rasterized as kwarg parseable in Plot()

gwpy/io/ligolw.py, gwpy/table/lsctables.py, gwpy/tests/test_table.py
This PR introduces two new methods attached to the `glue.ligolw.table.Table` and subclasses,
- `Table.to_recarray` : convert this table to a `numpy.recarray`
- `Table.from_recarray` : create a new table from a `numpy.recarray`
=> New methods for LIGO_LW Table <-> numpy.recarray conversions

gwpy/plotter/table.py
This PR fixes #149 by using the integer part of the first event in a table to set the default epoch for the `EventTablePlot`.
=> Improved default epoch for EventTablePlot

gwpy/spectrum/core.py
Fixes #234 . I've tested that this returns almost what we want with two issues:
* I'm having trouble setting the sample rate from `df`, so I set `dx` instead, but the units come out as inverse Hz. Not ideal.
* I'm struggling to understand the normalization convention used in `TimeSeries.fft`, so the output of `ifft` is not currently normalized correctly.
=> spectrum/core.py: add ifft method

.travis.yml
This PR adds `fast_finish: true` to the `matrix` section of the travis config, meaning travis will report the build status back to github as soon as all non-`allowed_failure` build as complete.
=> Use fast_finish to ignore allowed_failures in travis report

.travis/build-src-dependencies.sh, .travis/build-with-autotools.sh
This hopefully should fix python3 build that dies when nds2 fails to build (#229).
=> Run build-with-autotools.sh in travis, don't source

gwpy/spectrum/core.py, gwpy/spectrum/hist.py, gwpy/tests/test_array.py, gwpy/tests/test_spectrum.py, gwpy/tests/test_timeseries.py
This PR introduces a new `TestSuite` for the `Spectrum` object, then fixes a few bugs in that object uncovered by the unit tests (fixes #236), and does the same for `SpectralVariance`.
=> Added unit tests for the Spectrum and SpectralVariance

gwpy/plotter/segments.py
This PR fixes #244 by checking against `glue.segments` types in `SegmentAxes.plot` instead of the `gwpy.segments` subclasses.
=> Respect glue.segments types in SegmentAxes.plot

gwpy/segments/flag.py, gwpy/tests/test_segments.py
This PR fixes a bug in `DataQualityFlag.copy()` that would miss attributes that weren't explicitly named, and adds an `inplace` kwarg to `DataQualityFlag.pad` to modify the `active and `known` segmentlists in place, instead of returning a copy of the flag.
This is done to allow `DataQualityDict.populate` to not copy flags when padding is used, meaning the values are the same objects before and after this method is used.
=> Removed copy in flag.pad() when running dict.populate()

.travis.yml, gwpy/plotter/segments.py, gwpy/plotter/timeseries.py, gwpy/tests/test_plotter.py
This PR fixes #246 by allowing `*args, **kwargs` to pass through to the underlying method.
I also added a specific test against regresion, and improved a few of the other plotting tests (hopefully).
=> Fix bug in TimeSeriesAxes.set_xscale

gwpy/timeseries/statevector.py
This PR fixes #243 by over-writing `StateVector.get` to allow simple passing of bits as a kwarg to that method.
=> Fixed passing bits to StateVector.get

gwpy/timeseries/timeseries.py
This fixes a problem with `TimeSeries.whiten` where the result of the IFFT was being applied directly to the `TimeSeries` with no units, resulting in a `UnitsError`.
=> Fixed unit imcompatibility in TimeSeries.whiten

examples/timeseries/public.py, gwpy/tests/test_timeseries.py, gwpy/timeseries/core.py, gwpy/timeseries/io/losc.py, gwpy/timeseries/statevector.py
This PR introduces the `TimeSeries.fetch_open_data` class method, which automatically locates, downloads, and reads HDF5 files hosted on losc.ligo.org to return the requested data.
=> New TimeSeries.fetch_open_data classmethod

examples/timeseries/qscan.py, gwpy/signal/__init__.py, gwpy/signal/qtransform.py, gwpy/tests/test_timeseries.py, gwpy/timeseries/timeseries.py
This PR introduces a gwpy implementation to the original-MATLAB Q-transform scan, via the `TimeSeries.q_transform` instance method. Included are tests and an example, which produces this image:
**[NB: these data are from the S6 blind injection, and do not contain an astrophysical signal]**
Thanks to @scottcoughlin2014 for the original MATLAB-python conversion as part of the [GravitySpy](//github.com/mzevin1/GravitySpy/commits/PyOmega) project
=> New TimeSeries.q_transform method

examples/timeseries/qscan.py, gwpy/tests/test_timeseries.py
This PR modifies the tests and example for `TimeSeries.q_transform` to use `TimeSeries.fetch_open_data`.
This should hopefully fix the problem with reduced coverage for the new Q-transform implementation.
=> Use fetch_open_data for new Q-transform tests and examples

gwpy/io/datafind.py, gwpy/tests/test_timeseries.py, gwpy/timeseries/core.py
This PR further improves the `TimeSeriesDict.find` and the underlying `io.datafind` infrastructure to automatically determine the best frametype for a given channel.
=> Fixed bugs in TimeSeries.find and io.datafind

requirements.txt
There are a lot of warnings when using jupyter. According to https://github.com/astropy/astropy/issues/4169 , this was fixed in astropy 1.0.5. I've tested that upgrading astropy directly using pip fixes the problem, but I haven't tested a clean install.
=> Fix Jupyter ShimWarnings - bump astropy version.

gwpy/tests/test_timeseries.py, gwpy/timeseries/timeseries.py
This PR introduces a workaround in `TimeSeries.fft` due to numpy 1.7 not having `numpy.fft.rfftfreq. It's a simple method, so this is preferred to bumping the numpy version to 1.8 (give than the new SL7 on LDAS finally has numpy 1.7).
=> Workaround for numpy 1.7 not having rfftfreq

gwpy/tests/test_timeseries.py, gwpy/timeseries/timeseries.py
interpolation happens at exact frequencies, so need to operate on proper frequencies for both the `QRow` and the desired frequencies, then shift down by `fres/2.` for the output `Spectrogram` bins
Fixes #265. With this code, I get the following equivalent output for the example given in #265:
=> TimeSeries.q_transform: improved frequency recovery

gwpy/timeseries/core.py
This PR adds protection against `ImportError` in `TimeSeries.get` coming from having no frame library installed - this should get picked up by `TimeSeries.fetch` with the nds2 client.
=> Bypass `ImportError` in TimeSeries.get from missing frame library

gwpy/signal/qtransform.py, gwpy/timeseries/timeseries.py
This PR introduces `transform` instance methods for both the `QPlane` and `QTile` (formerly `QRow`) objects, and uses them in the `TimeSeries.q_transform` method to simplify it.
This should make it easier for the user to transform over a single `QTile` if they want, but doesn't quite provide the nice spectrogram interpolations to get all the way to the end.
=> Q-transform with a single Q

gwpy/plotter/frequencyseries.py
This PR fixes a missing `warnings` module import in `gwpy.plotter.frequencyseries`.
=> Fixed missing import

gwpy/io/cache.py, gwpy/tests/test_timeseries.py
This PR fixes bugs in the handling of cache files underneath `TimeSeries.read`. Astropy insists on opening the cache file, then passing it through the identifiers, so we need to handle open cache files (including temporary files) before passing on to the GWF reader.
=> Fixed reading timeseries from cache file path

gwpy/segments/flag.py, gwpy/tests/test_segments.py
This PR introduces an explicit `on_error` kwarg for `DataQualityDict.populate` to skip over failed flag queries. Also included are improvements of the tests for this method, and of segment tests in general.
=> Allow DataQualityDict.populate to skip failed downloads

.travis/run-tests.sh, requirements.txt, setup.cfg, setup.py
This PR cleans the `setup.py` script and its `.cfg` file a bit. The main change is the `pytest-runner` configuration as described [here](https://pytest.org/latest/goodpractices.html#integrating-with-setuptools-python-setup-py-test-pytest-runner) so that one can run
```bash
$ python setup.py test
```
to run the test suite.
=> Cleaned setup.py and cfg

.travis.yml, .travis/build-src-dependencies.sh, gwpy/io/datafind.py, gwpy/tests/test_cli.py, gwpy/tests/test_io.py, gwpy/tests/test_timeseries.py
This PR adds another build to the travis-ci setup, skipping the src package builds in favour of testing only the pure python setup.
This is probably what most users outside of the LSC are going to be trying anyway.
=> Add minimal python-only build to travis

gwpy/tests/test_utils.py, gwpy/utils/shell.py
This PR fixes critical bugs in `gwpy.utils.shell.call`, and introduces a test case for the `gwpy.utils` module covering `gwpy.utils.shell`.
=> Fixed bugs in utils.shell.call

gwpy/detector/channel.py, gwpy/tests/test_detector.py
GEO and Virgo channels don't follow the same conventions as LIGO, but should be handled just the same. This PR modifies the `Channel.MATCH` regular expression specifically to allow dash-delimited channel-name components other than the first division, and to optional match a trailing `-[a-z]+` string as the trend type (GEO uses `-min` rather than `.min`, for example).
This might break if it turns out there are channels with a dash-delimited lowercase component that isn't the trend type, but I haven't come across an example of that to date.
=> Improved Channel.MATCH regex for GEO channel support

gwpy/signal/__init__.py, gwpy/signal/filter.py, gwpy/signal/filter_design.py, gwpy/tests/test_signal.py, gwpy/tests/test_timeseries.py, gwpy/timeseries/timeseries.py
This PR addes a `filtfilt` kwarg to the `TimeSeries.filter` method, whilst also shuffling a few things in `gwpy.signal`.
This includes a quick `sosfiltfilt` implementation that can be removed whenever such a function becomes available.
=> Added filtfilt support in TimeSeries.filter

gwpy/data/array2d.py, gwpy/frequencyseries/hist.py, gwpy/spectrogram/core.py, gwpy/tests/test_array.py
This PR introduces two new private class variables for the Array2D
- `_rowclass`
- `_columnclass`
which are used by `Array2D.__getitem__` to decide how to return items from the 2-d array.
=> Added row and column class refernences to Array2D

gwpy/tests/test_timeseries.py, gwpy/timeseries/io/gwf/framecpp.py, gwpy/utils/lal.py
This PR fixes a bug in reading frames using frameCPP where channel parameters in the output `TimeSeries` were not set properly.
=> Fixed missing channel parameters in TimeSeries.read(format='framecpp')

.travis.yml, gwpy/io/cache.py, gwpy/table/__init__.py, gwpy/table/io/__init__.py, gwpy/table/io/ligolw.py, gwpy/table/io/pycbc.py, gwpy/table/lsctables.py, gwpy/table/rec.py, gwpy/table/utils.py, gwpy/tests/test_table.py, requirements.txt
This PR expands support for using the `numpy.recarray` to store tabular data normally stored in `LIGO_LW` format (using `glue.ligolw`). Changes include
- new `GWRecArray` object with `.read()` method tied to all `LIGO_LW` table formats
- new parser for `pycbc_live` files
=> Expand use of numpy.recarray for tabular data

.travis.yml
This PR moves the python26 build to the `allow_failures` section, now that python26 support will be best-effort.
=> Transition python26 support to 'best-effort'

gwpy/table/io/ligolw.py, gwpy/table/io/pycbc.py
This PR adds the `loudest=False` keyword argument for `GWRecArray.read(..., format='pycbc_live')`; if `loudest=True` then only the events indicated in the `loudest` dataset are returned, advertised as 50 events per file (16s).
=> Added loudest kwarg for reading pycbc_live events with GWRecArray

gwpy/plotter/segments.py, gwpy/plotter/utils.py
This PR improves the escaping of underscores when plotting with latex; those underscores followed by latex grouping brackets `{}` shouldn't be escaped - the assumption is that these are inside mathmode `$$`.
=> Improved handling of underscores in latex plotting

gwpy/io/cache.py, gwpy/io/utils.py, gwpy/segments/io/ligolw.py, gwpy/table/io/cwb.py
This PR resolves the `DeprecationWarning` currently displayed from `astropy.utils.compat.gzip` by using the builtin `gzip` module.
Fixes #293.
=> Use gzip module for GzipFile

gwpy/segments/io/hdf5.py, gwpy/segments/io/ligolw.py
This PR modifies all imports of `LIGOTimeGPS` to the `gwpy.time` module. Only that module should import that object from outside, which should make removing the glue dependency a bit easier in the future.
=> Use gwpy.time.LIGOTimeGPS import in segments.io

gwpy/cli/coherence.py, gwpy/frequencyseries/core.py, gwpy/frequencyseries/lal_.py, gwpy/signal/qtransform.py
This PR fixes #300 by removing a few lingering references to the `Spectrum`
=> Replaced deprecated Spectrum references

gwpy/detector/channel.py, gwpy/io/datafind.py, gwpy/timeseries/core.py
This PR improves the error handling in the `gwpy.io.datafind.find_frametype` method -- fixes #296  with a better error message. The main user-level change is that the `exclude_tape` keyword argument was renamed `allow_tape` to bring it inline with the `TimeSeries.find` arguments.
The new error for a channel not found is:
```
ValueError: Cannot locate 'L1:Test' in any known frametype at GPS=1158710417 [those files on tape have not been checked, use allow_tape=True to perform a complete search]
```
EDIT: fixes #288 by improving documentation of the `allow_tape` kwarg in the `TimeSeries` object.
=> Improved error handling in datafind.find_frametype

gwpy/table/io/pycbc.py
This PR improves the `pycbc.empty_hdf5_file` check to return `True` (i.e. 'empty') if no IFO-level group is found in the file (and `ifo` is given).
=> Check for IFO-level group in PyCBC HDF5 files

gwpy/tests/test_segments.py, gwpy/types/array2d.py
This PR fixes a bug in `Array2D.__getitem__` whereby changes to the x-axis metadata were being down twice, once in `Series.__getitem__` and once in `Array2D.__getitem__`.
=> Fixed metadata bugs in Array2D.__getitem__

.travis.yml, gwpy/table/io/__init__.py, gwpy/table/io/hacr.py, requirements-extra.txt
This PR adds a fetch method for HACR triggers stored in MySQL databases as per GEO600 conventions.
This isn't hooked up to either the `.fetch()` or `.read()` methods at this time, but users can directly access the reader via
```python
from gwpy.table.io.hacr import get_hacr_triggers
```
then call the function as described.
=> Added HACR trigger reader

gwpy/timeseries/timeseries.py
This PR modifies a couple of calls in `TimeSeries` methods to set `t0` instead of `epoch`, removing any calls to `Time` which can introduce precision issues with year-2016 GPS floats.
=> Set TimeSeries.t0 instead of TimeSeriesepoch to save precision

docs/_static/gwpy-sphinx.css, docs/_templates/layout.html, docs/conf.py, docs/timeseries/index.rst
This PR updates the style of the GWpy documentation, mainly to not use Lato font.
This also removes a couple of sphinx extensions that seem to be dead (epydoc) or broken (doxylink).
=> Minor improvements to documentation styling

docs/conf.py, docs/ex2rst.py
This PR updates the `/docs/ex2rst.py` script to use the `.. plot` RST directive for all code blocks, along with `:context:` to improve the formatting, rather than inserting a `.. plot` directive at the end of each.
=> Improved conversion of examples .py to RST

gwpy/plotter/__init__.py, gwpy/plotter/core.py, gwpy/plotter/utils.py, gwpy/tests/test_plotter.py, setup.cfg
This PR improves the default styling for figures by dynamically setting the subplot parameters using a lookup table for the figure dimensions.
This _only_ happens if the user has not changed the subplot params in `rcParams` compared to the defaults read from the `matplotlibrc` file - so there's still a hole if the user really wants the defaults - but if they specify `subplotpars` as a keyword in their `Plot` call everything is fine.
=> Added dynamic subplot params based on figure dimensions

gwpy/plotter/frequencyseries.py, gwpy/plotter/tex.py, gwpy/plotter/timeseries.py
This PR modifies the `TimeSeriesAxes.plot_timeseries` and `FrequencySeriesAxes.plot_spectrum` methods to set default axes labels.
=> Set default axes labels for TimeSeriesAxes and FrequencySeriesAxes

gwpy/plotter/frequencyseries.py, gwpy/tests/test_plotter.py
This PR renames the `FrequencySeriesAxes.plot_spectrum` method to `FrequencySeriesAxes.plot_frequencyseries` and provides a `DeprecationWarning`ed wrapper for legacy calls. Most users probably just use `plot()` anyway, so this might not hit many people.
=> Renamed one more ghost of Spectrum

gwpy/io/cache.py, gwpy/tests/test_io.py, gwpy/timeseries/core.py, gwpy/timeseries/io/cache.py, gwpy/timeseries/io/losc.py, gwpy/timeseries/statevector.py
This PR updates the `gwpy.timeseries.io.losc` module to use the JSON API for discovering public data hosted by https://losc.ligo.org.
=> Use LOSC JSON API to discover public data

gwpy/plotter/__init__.py, gwpy/tests/test_array.py, gwpy/tests/test_plotter.py
This PR fixes (hopefully) the test failure in `gwpy/tests/test_plotter.py::SegmentAxesTestCase::test_build_segment` under matplotlib-2.0.
=> Fixed tests of colors for matplotlib 2.0

gwpy/frequencyseries/hist.py, gwpy/spectrogram/core.py, gwpy/tests/test_timeseries.py, gwpy/timeseries/statevector.py, gwpy/timeseries/timeseries.py, gwpy/types/array.py, gwpy/types/array2d.py, gwpy/types/io/hdf5.py, gwpy/types/series.py
This PR improves a number of `Array` manipulation methods that rely on `numpy.ndarray.view` to cast to the output type. This operation loses all metadata, so we need to reset the unit explicitly because astropy doesn't do it for us.
=> Set unit after array.view(cls) operations

.travis.yml, .travis/build-src-dependencies.sh
This PR modifies the build script to use the separated ldas-tools-framecpp package, rather than the monolithic (deprecated) ldas-tools build.
=> Update travis build to use separate ldas-tools-framecpp package

gwpy/timeseries/core.py
This PR implements an interface to the nds2 client ALLOW_DATA_ON_TAPE parameter, if available. This also extends the logical server looping to do a first loop with `ALLOW_DATA_ON_TAPE=False`, then a second loop with `True`.
=> Added support for ALLOW_DATA_ON_TAPE

docs/install.rst
This PR fixes #332 by updating the macports references for `lal` and `lalframe`.
=> Updated lal/lalframe port references in installation docs

docs/Makefile, examples/frequencyseries/index.rst, examples/signal/index.rst, examples/spectrogram/index.rst, examples/table/index.rst, examples/timeseries/index.rst
This PR updates the examples in the documentation to use a manually ordered list. This should be a bit more pedagogical for walking through functionality.
=> Use ordered examples

gwpy/io/ligolw.py
The latest release of `glue` is backwards incompatible with previous, with a number of objects and methods being removed (`DeprecationWarning`s have been in place for a while). This PR updates any broken `glue.ligolw` calls in a backwards compatible manner.
=> Updated glue.ligolw calls to latest stable release

gwpy/io/ligolw.py, gwpy/table/io/ligolw.py, gwpy/table/lsctables.py
This PR fixes a deprecation in the latest release of `glue`.
=> Updated table.io ligolw calls to not use StripTableName

gwpy/table/io/ascii.py
This PR fixes another reference to `StripTableNames` which was removed in the latest release of `glue`.
=> Updated reference to deleted glue.ligolw object

.travis.yml, .travis/build-src-dependencies.sh, .travis/build-with-autotools.sh, .travis/find-latest-release.py, .travis/find-latest-releases.sh, .travis/install-requirements.sh, bin/gwpy-plot, gwpy/timeseries/statevector.py, requirements-2.6.txt, setup.py
This PR modifies the travis-ci configuration to include the LSCSoft apt sources for non-python dependency installation.
=> Use apt/sourceline to install more stuff for travis-ci

gwpy/cli/cliproduct.py, gwpy/cli/coherence.py
This PR modifies the `gwpy.cli` module to use the python3-compatible `print()` function, rather than the outdated `python` keyword.
Fixes #351.
=> Use print function for all calls (rather than print keyword)

.travis.yml, .travis/build-with-autotools.sh
This PR should speed up the continuous integration build by only running `./configure` for fresh builds.
=> Speed up travis-ci by not running ./configure for src builds every time

gwpy/table/io/pycbc.py
This PR fixes a bug in `gwpy.table.io.pycbc` where HDF5 files that get opened don't get closed again, resulting in `too many open files` errors. Thanks to @micamu for spotting this.
=> Fixed bugs where pycbc_live files don't get closed

gwpy/timeseries/io/cache.py, gwpy/timeseries/io/lalframe.py
This PR optimises `gwpy.timeseries.io.lalframe` by removing an array copy when appending to a `TimeSeriesDict`.
I also include a tiny addition to parse a `glue.lal.Cache` from an open file object.
=> Don't copy all vectors on reading with lalframe

gwpy/io/__init__.py, gwpy/io/mp.py, gwpy/table/io/ligolw.py, gwpy/table/io/pycbc.py, gwpy/table/io/root.py, gwpy/table/table.py, gwpy/tests/test_table.py
This PR cleans up the application of the `nproc` keyword argument to `Class.read` methods. The unified `gwpy.io.reader` factor method now takes a `mp_flattener` keyword argument that defines how to flatten a list of objects into a single object, as would be needed to coalesce the results of a multi-processed read operation.
This PR applies it first to the `EventTable.read` method, cleaning up the `nproc` references in `gwpy.table.io`.
=> Added unified nproc option to gwpy.io.reader

gwpy/io/mp.py, gwpy/io/registry.py, gwpy/table/io/pycbc.py, gwpy/tests/test_table.py
This PR fixes a bug introduced by #378 whereby reading directly from h5py objects would raise a `ValueError`. This includes a unittest to guard against regression.
=> Fixed bug in reading Tables directly from h5py objects

gwpy/table/io/ligolw.py
This PR modifies the LIGO_LW table reader to exclude specific methods that are known to not be column generators when using the `get_as_columns=True` option.
=> Exclude specific get_ methods from get_as_columns when reading LIGO_LW files

gwpy/timeseries/core.py
This PR modifies the defaults for `TimeSeries{Dict}.get` to include `allow_tape=None` (rather than `False`). This ends up doing the following
- `TimeSeries.find` gets called with `allow_tape=False`, then
- `TimeSeries.fetch` gets called with `allow_tape=None`
This should minimise the requirement of using a tape, but should eventually get data to the user.
=> Set allow_tape=None as default for TimeSeries.get

gwpy/table/io/pycbc.py, gwpy/tests/test_table.py
This PR fixes #377 by improving the error message for multi-ifo files, and adds a test method for `EventTable.read(..., format='hdf5.pycbc_live')`.
=> Improved error reporting and tests for reading pycbc_live tables

gwpy/cli/cliproduct.py
This PR fixes #352 by allowing the user to manually select the nds2 host for `TimeSeries.fetch`.
=> Added --nds2-server argument to gwpy-plot

gwpy/plotter/frequencyseries.py
This PR fixes a bug in `FrequencySeriesPlot.__init__` when setting default x-axis limits.
=> Fixed bug in setting default limits in FrequencySeriesPlot

docs/references.txt, docs/timeseries/index.rst, docs/timeseries/io.rst, docs/timeseries/ldg.rst, docs/timeseries/plot.rst, docs/timeseries/remote-access.rst, gwpy/timeseries/core.py
This PR improves the sphinx documentation for the `TimeSeries` and associated objects, mainly to improve the I/O components, spelling out what you can do for each filetype, similar to what is done in the Astropy documentation.
=> Improved TimeSeries documentation

gwpy/tests/test_timeseries.py, gwpy/timeseries/io/gwf/framecpp.py
This PR fixes a bug when reading data from a frame file that contains multiple frames (as in the aggregated LIGO h(t) frame files), when not reading the full data (i.e. `start` or `end` is given).
=> Fixed bugs in reading data from multi-frame GWF with framecpp

gwpy/segments/flag.py
This PR works around problems serialising LIGOTimeGPS with JSON when querying for segments from `dqsegdb`.
This may have to be changed/updated if/when dqsegdb allows non-integer segments.
=> Force query times to int when calling to dqsegdb

gwpy/tests/test_timeseries.py, gwpy/timeseries/core.py
This PR improves the formatting of the `StateTimeSeries` returned by comparison operations on a `TimeSeries`, e.g. TimeSeries(...) > 100.
=> Improved formatting/tests for timeseries comparisons

gwpy/tests/test_timeseries.py, gwpy/timeseries/timeseries.py
This PR fixes #393 by casting slice indices to `int` in `TimeSeries.rms`.
=> Use ints for slicing in TimeSeries.rms

gwpy/tests/test_timeseries.py, gwpy/timeseries/core.py, gwpy/utils/lal.py
This PR fixes #406 by improving the unit handling in `TimeSeries.to_lal` and `TimeSeries.from_lal`
=> Improved unit handling in TimeSeries.{to,from}_lal methods

gwpy/plotter/timeseries.py
This PR removes unneeded calls to `set_epoch` and similar when creating a `SegmentAxes` as part of `TimeSeriesPlot.add_state_segments`.
=> Simplified GPS axis scaling in TimeSeriesPlot.add_state_segments

gwpy/plotter/__init__.py, gwpy/plotter/core.py, gwpy/plotter/rc.py
This PR moves the `GWPY_PLOT_PARAMS` dict, and related customisations of `matplotlib.rcParams` to a new `gwpy.plotter.rc` module.
This cleans up the code a wee bit, whilst retaining backwards compatibility.
=> Moved rcParams customisation to new gwpy.plotter.rc module

gwpy/io/mp.py
This PR works around the fact that `SAXExceptions` are not pickleable, meaning they can't be returned from child processes in multiprocessing, so we need to get the underlying error and return that instead.
=> Handle XML parsing errors in mp

gwpy/timeseries/io/gwf/__init__.py
This PR fixes #418 by adding a line to sieve a cache internally if `start` and `end` keywords are given. [@andrew-lundgren]
=> Sieve cache internally when reading GWF into TimeSeries

gwpy/timeseries/io/gwf/__init__.py
This PR modifies the top-level `gwpy.timeseries.io.gwf.read_timeseriesdict` method to pass any other keyword arguments (`**kwargs`) to the underlying GWF API read method. This mainly allows specifying `type` when reading with `format='gwf.framecpp'`.
=> Pass keywords from TimeSeris.read to underlying GWF API

gwpy/timeseries/io/gwf/__init__.py
This PR augments #422 by handling `**kwargs` when multiprocessing.
=> Pass kwargs from TimeSeries.read to underlying GWF API when multiprocessing

gwpy/plotter/frequencyseries.py, gwpy/tests/test_frequencyseries.py, gwpy/tests/test_plotter.py, gwpy/tests/test_spectrogram.py, gwpy/tests/test_timeseries.py
This PR fixes #412 by improving the default formatting of log axes on a `FrequencySeriesPlot`. The trick is to set the x-axis scale (`ax.set_xscale`) before setting the limits.
This PR also modifies the `test_plot` method for all of the class tests to include a `plot.save` operation to make sure that the default figure actually renders (which would have caught #412).
=> Fixed bug in default plot for FrequencySeries

gwpy/plotter/log.py
This PR removes an unnecessary call to `math.log10` thereby removing a potential `ValueError` when zeros creep into a log scale.
=> Removed unnecessary log10 call in plotting

gwpy/plotter/axes.py, gwpy/tests/test_plotter.py
This PR modifies the `Axes.legend` method to force the legend frame to inherit the linewidth from the `axes.linewidth` setting. By default this means that a figure's axes and legends will have the same frame width, which is nice.
=> Axes.legend: inherit frame linewidth from rcparams

docs/table/index.rst, docs/table/io.rst, gwpy/io/mp.py, gwpy/table/io/gwf.py, gwpy/table/io/pycbc.py
This PR modifies `gwpy.io.mp.read_multi` to use `multiprocessing.Pool` (instead of `ProcessQueue`) for parallel file reading, enabling trivial parallel I/O for astropy registered readers (e.g. ASCII). Files are now passed through the pool one-by-one, so readers in `gwpy.table.io` only need to be built to handle a single file at a time.
=> Use multiprocessing.Pool for parallel I/O

requirements-dev.txt, requirements.txt, setup.py
This PR updates the setup/requirements dependencies to reference [`lscsoft-glue`](https://pypi.python.org/pypi/lscsoft-glue/) and [`dqsegdb`](https://pypi.python.org/pypi/dqsegdb/) from pypi. This should simplify the build.
=> Updated build dependencies to reference lscsoft-glue and dqegdb on pypi

.travis.yml
This PR adds auto-deployment from travis to pypi.python.org for all tags from the master branch. Currently this is configured only for python 2.7, but we should enable python 3.x when the builds run successfully.
=> Configured auto-deployment to pypi from travis-ci

docs/install.rst, requirements.txt, setup.py
This PR bumps the minimum version requirement for astropy to 1.2.1, since this is the first version that provides `astropy.io.registry.IORegistryError`.
=> Bumped astropy requirement to 1.2.1

docs/index.rst, docs/install/index.rst, docs/install/lal.rst, docs/references.txt, gwpy/tests/compat.py, gwpy/tests/test_astro.py, gwpy/tests/test_frequencyseries.py, gwpy/tests/test_plotter.py, gwpy/tests/test_segments.py, gwpy/tests/test_timeseries.py, gwpy/timeseries/io/losc.py, gwpy/utils/auth.py, setup.py
This PR modifies the build script (`setup.py`) and the test suite to ensure that the tests run end-to-end without any failures on a minimal install, e.g. after
```
git clone https://github.com/gwpy/gwpy
cd gwpy
pip install .
```
followed by
```
python setup.py test
```
The commits are individually simple and amount to
- making sure all required dependencies are listed in `install_requires` or `tests_require` as appropriate
- moving some optional imports to fail at run time rather than import
- adding `skipUnless` decorators to all tests requiring `h5py` or `dqsegdb`
=> Improved default build/test environment

gwpy/io/cache.py, gwpy/io/datafind.py, gwpy/io/ligolw.py, gwpy/table/io/pycbc.py, gwpy/tests/mockutils.py, gwpy/timeseries/io/losc.py
This PR updates references to `CacheEntry` to import from `lal.utils`, and not `glue.lal`. This resolves a `DeprecationWarning` thrown by `glue.lal`.
=> Updated references of glue.lal.CacheEntry to lal.utils.CacheEntry

bin/gwpy-plot, gwpy/cli/cliproduct.py
This PR adds a `--style` option for `gwpy-plot` documented as
```
--style FILE          path to custom matplotlib style sheet, see
http://matplotlib.org/users/style_sheets.html#style-
sheets for details of how to write one
```
The argument is a path to a matplotlib style sheet, as documented [here](http://matplotlib.org/users/style_sheets.html#style-sheets). This will allow users to customise their plots ad nauseam without manually editing python code.
In line with this I have removed the custom `rcParams` settings in `gwpy.cli.cliproduct`. These can be reinstated (e.g. on LDVW) with the following style file
```
figure.dpi: 100
font.family: sans-serif
font.size: 16
font.weight: book
legend.loc: best
lines.linewidth: 1.5
text.usetex: True
agg.path.chunksize: 10000
```
=> Added --style command-line option to gwpy-plot

.travis.yml, .travis/build-src-dependencies.sh, .travis/build-with-autotools.sh
This PR updates the autotools build scripts in `/.travis/` to support `cmake` builds, and updated the arguments for the NDS2-client builds to use those. `cmake` is the build system for that package as of the latest release, 0.14.
=> Updated travis-ci src builds to use cmake for nds2-client

examples/timeseries/index.rst, examples/timeseries/pycbc-snr.py, gwpy/frequencyseries/core.py, gwpy/tests/test_frequencyseries.py, gwpy/tests/test_timeseries.py, gwpy/timeseries/core.py, requirements-dev.txt
This PR fixes bugs and improves functionality in the `{TimeSeries,FrequencySeries}.{to,from}_pycbc` conversion methods, and the unit tests of those methods. This also adds a new example showing calculating the SNR for the GW150914 event detection.
=> Improved PyCBC conversion methods

examples/timeseries/pycbc-snr.py, gwpy/tests/test_array.py, gwpy/types/array.py
This PR implements the `Array.abs` instance method, using the underlying `numpy.abs` method, for convenience.
=> Implemented abs instance method for Array objects

.travis.yml
This PR attempts to fix the LAL build timeout for python3 by adding `travis_wait`.
=> Attempt to fix travis timeout buildling LAL for python3

gwpy/plotter/histogram.py, gwpy/plotter/table.py
This PR cleans up `gwpy.plotter.table` and `gwpy.plotter.histogram` by removing code to directly plot LIGO_LW tables, which have been deprecated for a while.
=> Removed deprecated LIGO_LW Table plotting code

gwpy/detector/channel.py, gwpy/io/nds2.py, gwpy/tests/compat.py, gwpy/tests/mockutils.py, gwpy/tests/test_detector.py, gwpy/tests/test_io.py, gwpy/tests/test_timeseries.py, gwpy/timeseries/core.py, gwpy/timeseries/io/nds2.py, gwpy/timeseries/statevector.py, setup.py
This PR attempts to simplify the nds2 API by centralising more of the query methods in the `gwpy.io.nds2` module, hopefully reducing the complexity of methods for the `TimeSeries` and `Channel{List}`.
additionally, the `TimeSeries.fetch` method has been separated into two parts with a new `gwpy.timeseries.io.nds2` module providing the low-level iterate wrapper.
This is a duplicate of #456 just without the segmentation fault.
=> Rework of NDS2 interface (gwpy.io.nds) (without segfault)

gwpy/tests/test_timeseries.py, gwpy/timeseries/core.py, gwpy/timeseries/io/nds2.py
This PR fixes a bug introduced by #457 in `TimeSeries.fetch` when using `allow_tape` (in that `allow_tape` was being totally ignored).
=> Fixed fetch tape bug

gwpy/plotter/gps.py
This PR fixes a bug in the unit setting for `GpsScale`, whereby setting it to `seconds` would cause an `AttributeError`.
=> Fixed bug in setting units in GpsScale

gwpy/signal/qtransform.py, gwpy/tests/test_timeseries.py
This PR modifies the behaviour of the `QTiling` object, which now forces the user's given upper frequency limit down to the maximum (based on Q, duration, sampling, etc), and posts a warning to that effect. Previously this would result in an `IndexError` further down the line that was essentially untraceable. Updated unit test included.
=> Force maximum frequency in QTiling down to workable value

gwpy/timeseries/io/gwf/framecpp.py
This PR removes lines that modify channel objects in place when reading `TimeSeries` using frameCPP, as this can change the hash of that channel, which causes problems when that is a `dict` key.
=> Removed channel modifications in timeseries.io.gwf.framecpp

gwpy/io/nds2.py, gwpy/tests/test_io.py, gwpy/timeseries/io/gwf/framecpp.py
This PR fixes #465 by adding the missing `gwpy.io.nds2.minute_trend_times` function that got forgotten in the confusion between #456 and #457, unit tests included.
=> Fixed missing minute_trend_times method

examples/timeseries/pycbc-snr.py, gwpy/timeseries/io/gwf/framecpp.py
This PR fixes a trivial typo in the text for the pycbc SNR example.
=> Fixed typo in example text

gwpy/tests/test_array.py, gwpy/timeseries/io/gwf/framecpp.py, gwpy/types/io/hdf5.py
This PR improves the reading/writing of `Channel` objects as part of `TimeSeries` I/O as follows
- read new `Channel` as part of `TimeSeries` from GWF
- use `pickle` to serialise/deserialise `Channel` as part of `TimeSeries` from HDF5
This reverts #463.
=> Improved handling of Channels in TimeSeries I/O

gwpy/timeseries/io/gwf/framecpp.py
This PR updates the frameCPP.py API to handle an unset `tRange` attribute in `FrProcData` structures. `tRange` is not required, so if it is set to 0 it might have been omitted, so carry on trying to read the frame; if the dataset is actually empty, that will get picked up further down the line.
=> Workaround for unset tRange in GWF frames

gwpy/signal/fft/ui.py, gwpy/tests/test_timeseries.py, gwpy/timeseries/timeseries.py
This PR fixes bugs in the processing of cross spectra and spectrograms via `TimeSeries.csd` and (more importantly) `TimeSeries.csd_spectrogram.
In the process, I have depcrecated the `cross` keyword argument in `TimeSeries.spectrogram`, users should just use `TimeSeries.csd_spectrogram`, and added a test for the deprecation warning.
=> TimeSeries.csd{_spectrogram}: fixed bugs introduced by v0.5

gwpy/tests/test_timeseries.py, gwpy/timeseries/timeseries.py
This PR fixes #464 by improving the default whitening arguments (`fftlength`, `overlap`, `method`) for `TimeSeries.q_transform`.
It also adds support for users to supply their own whitening ASD, by passing `whiten=fs` where `fs` is a `gwpy.frequencyseries.FrequencySeries`, as described in the function docstring.
=> Improved whitening options for TimeSeries.q_transform

gwpy/timeseries/io/nds2.py
This PR fixes a bug in the default channel type for the `TimeSeries.fetch` operation (and friends). The crux is to exclude the `ONLINE` channel type when searching for channels.
=> Fixed bug in default channel type for TimeSeries.fetch

.travis.yml
This PR removes the `travis_wait` prefix for the src builds on travis-ci.org, this was causing 20-minute timeouts on a lot of builds.
=> Removed travis_wait from travis-ci configuration

gwpy/tests/test_time.py, gwpy/time/_tconvert.py, requirements-dev.txt, setup.py
This PR adds `Examples` to all docstrings in `gwpy.time`, and updates the unit tests to be more complete.
This adds a new testing dependency on [`freezegun`](https://pypi.python.org/pypi/freezegun).
=> Improved docstrings and tests for gwpy.time

gwpy/tests/test_timeseries.py, gwpy/timeseries/core.py
This PR fixes a bug in `TimeSeriesDict.fetch` introduced by #457 by actually using the `series_class` keyword of the `gwpy.timeseries.io.nds2.fetch` method (that does the actual query). This is required to get a `StateVector` back from `StateVector.fetch`.
=> Fixed bug in output type for TimeSeriesDict.fetch

.travis.yml
This PR forces the travis-ci build to use the (beta) `dist: trusty` option, which should prevent src build timeouts (LAL etc).
=> Use trusty dist for travis CI

gwpy/timeseries/io/gwf/framecpp.py
This PR adds filtering on the `Name` attribute of an `FrVect`, fixing an issue reading some `V1_llhoft` frames whereby two `FrVect`s were being stored in a single `FrProcData`, and only one of which actually contained channel data.
=> Check FrVect name when reading GWF with frameCPP

gwpy/timeseries/io/gwf/framecpp.py
This PR updates the changes from #478 to match `FrVect`s with no Name attribtue set - LIGO trend frames don't (currently) set the Name for FrVects, so need to pass empty strings.
=> Match FrVect with no name when reading with frameCPP

gwpy/tests/test_timeseries.py, gwpy/timeseries/io/gwf/__init__.py
This PR fixes a bug in casting a `TimeSeries` to another data type as part of reading from GWF.
=> Fixed bug in typecasting when reading GWF data into TimeSeries

gwpy/plotter/tex.py, gwpy/tests/test_plotter.py
This PR improves the `gwpy.plotter.tex.label_to_latex` method used to escape LaTeX control characters in labels for plotting. The behaviour now is to avoid doubly-escaping already escaped strings. See the new function documentation for examples.
This PR also includes improvements to the documentation of the other public methods in the `gwpy.plotter.tex` module.
=> Improved tex escaping of strings for labelling

gwpy/io/cache.py, gwpy/tests/test_io.py
This PR updates the `gwpy.io.cache.cache_segments` method to handle non-integer (i.e. `float`) GPS times in filename strings. This is required to handle PyCBC Live filenames where the are bending the rules of LIGO-T050017.
=> Improved parsing of filenames with non-integer GPS times

gwpy/spectrogram/core.py
This PR improves the DC offset when trying to filter 0 Hz in `Spectrogram.filter`, an offset of `1e-100` causes numerical overflows, so just use `f[1] / 100`.
=> Avoid overflows in filtering DC

gwpy/tests/test_timeseries.py, gwpy/timeseries/core.py
This PR fixes (and adds a regression test for) a bug in `TimeSeriesDict.fetch` whereby an open `nds2.connection` passed by the user would be recognised such that a host/port pair weren't generated, but then not passed to the underlying core `fetch()` method, causing a `TypeError` or similar trying to handle the NDS2 host `None`.
=> Fixed bug in handling open connection in TimeSeriesDict.fetch

gwpy/signal/fft/ui.py, gwpy/tests/test_signal.py, gwpy/timeseries/timeseries.py
This PR cleans up the `gwpy.signal.fft.ui` module a wee bit, mainly with reference to hacky checks that we're not including the wrong kwargs in 'rayleigh' or other methods.
=> Clean up of gwpy.signal.fft.ui

gwpy/table/io/pycbc.py
This PR patches the `table.io.pycbc.empty_hdf5_file` to return `True` (i.e. 'empty') if there isn't a group for the given `ifo`. Previously if there were groups for other IFOs, the function would then try to `list()` the given one, which meant if it didn't exist, you would end up with a `KeyError`.
=> Improve empty() file checker for pycbc io

gwpy/timeseries/io/losc.py
This PR removes what a `print` statement that was presumably for debugging something.
=> Removed debugging print statement in timeseries.io.losc

gwpy/signal/fft/lal.py, gwpy/signal/fft/ui.py, gwpy/signal/window.py, gwpy/tests/test_signal.py, gwpy/tests/test_timeseries.py, gwpy/timeseries/timeseries.py
This PR adds a new module `gwpy.signal.window` which provides two simple routines
- `canonical_name`: translates arbitrary window name into one understood by scipy (e.g. `ksr` -> `kaiser`)
- `recommended_overlap`: uses [Heinzel, Rüdiger, & Schilling [2002]](http://edoc.mpg.de/395068) to return the recommended overlap for a given FFTlength and window combination
The `recommended_overlap` method is now used to set the default overlap for all `TimeSeries` FFT routines, unless specified by the user.
=> Added gwpy.signal.window module to help with FFT routines

gwpy/astro/range.py, gwpy/tests/test_astro.py, gwpy/tests/test_table.py, gwpy/tests/test_timeseries.py, gwpy/timeseries/core.py
This PR fixes two problems introduced by the release of astropy v2
- crappy test of `TimeSeriesList.coalesce` was exposed, needed fixes
- astropy 2 starts using numpy 1.13's new `__array_ufunc__` API, so we need to replicate that to get the `TimeSeries` -> `StateTimeSeries` conversion to work for numpy ufunc comparisons
=> Fixed breakages introduced by astropy-2.0

gwpy/tests/test_timeseries.py, gwpy/timeseries/core.py, gwpy/timeseries/io/losc.py, gwpy/timeseries/statevector.py
This PR adds support for downloading data from losc.ligo.org in formats other than HDF5, namely 'txt.gz' and 'gwf'. This helps the test suite because it means we can test LOSCy things, and other methods using LOSC data without requiring h5py.
=> Added support for non-HDF5 LOSC file formats

gwpy/table/filter.py, gwpy/table/io/gwf.py, gwpy/table/io/hacr.py, gwpy/table/io/ligolw.py, gwpy/table/io/pycbc.py, gwpy/table/io/root.py, gwpy/table/io/utils.py, gwpy/table/table.py, gwpy/tests/test_table.py
This PR adds methods to filter tables of events via 'selections', including adding on-the-fly filtering for all table readers in `gwpy.table.io`.
=> Added methods for filtering tables, including on-the-fly filtering when reading

requirements-dev.txt, requirements.txt, setup.py
This PR bumps the version requirement on `pytest` from 2.8 to 3.1, this is the lowest version that provides the `pytest.param` function [[ref](https://docs.pytest.org/en/latest/changelog.html#id52)].
=> Bumped pytest version requirement to 3.1

.travis.yml, requirements-dev.txt
This PR adds an environment marker [see [PEP 508](https://www.python.org/dev/peps/pep-0508/)] to `requirements-dev.txt` to only install pycbc for python 2.7. This should allow the python3 CI builds to complete.
=> Use environment markers to only install pycbc for python-2.7

gwpy/table/io/fetch.py, gwpy/table/io/hacr.py, gwpy/table/table.py, gwpy/tests/test_table.py
This PR implements the `EventTable.fetch` method, providing a clean UI for database queries that yield tables. The only registration so far is for HACR SQL queries, but a Gravity Spy query is in the works [@scottcoughlin2014].
=> EventTable.fetch: new registry-based method for fetching events from databases

gwpy/tests/test_table.py, gwpy/tests/utils.py
This PR modifies usage of `six.PY2` and `six.PY3` so that the relevant statements work for python > 3. Its nice to be ahead of the game.
=> Check 'not PY2' instead of PY3

gwpy/timeseries/io/gwf/framecpp.py
This PR fixes a problem whereby writing memory-discontiguous arrays to GWF with framecpp would fail.
=> Fixed corner-case bug in writing GWF with framecpp

gwpy/detector/__init__.py, gwpy/detector/channel.py, gwpy/frequencyseries/core.py, gwpy/io/datafind.py, gwpy/io/gwf.py, gwpy/tests/test_utils.py, gwpy/timeseries/core.py, gwpy/timeseries/io/gwf/__init__.py, gwpy/utils/deps.py
This PR deprecates the `gwpy.utils.deps` module, including the `@with_import` decorator. This construct obfuscates imports, making the code harder to read, and confuses the hell out of any code inspection tools.
=> Deprecation of gwpy.utils.deps and @with_import decorator

gwpy/detector/io/clf.py, gwpy/io/cache.py, gwpy/tests/test_detector.py, gwpy/tests/test_io.py
This PR adds unit tests for `ChannelList.read()` and `ChannelList.write()` I/O with LIGO Channel List Files (CLF).
=> Added tests for ChannelList I/O with LIGO channel list files (CLF)

gwpy/table/filter.py, gwpy/table/io/fetch.py, gwpy/table/io/gravityspy.py, gwpy/table/io/hacr.py, gwpy/table/io/sql.py, gwpy/table/table.py
This PR separates the SQL query stuff from `gwpy.table.io.gravityspy` into a generic SQL fetch system, where users can pass their own `sqlalchemy.engine.Engine` to query any database.
This required a re-write of the selection parser.
=> Added generic SQL fetcher (from table.io.gravityspy)

gwpy/plotter/gps.py
This PR improves the labelling of scaled GPS times on an axis with a GPS scale. The key is to use `Decimal` for all GPS time conversions to avoid ridiculous python/numpy float precision corrections.
=> Improved GPS axis tick labelling

gwpy/signal/qtransform.py, gwpy/tests/test_timeseries.py, gwpy/timeseries/timeseries.py
This PR uses an improved default for the `fftlength` option to `TimeSeries.q_transform`, duplicating what the original matlab implementation did.
Also, I have improved the defaults for the other ASD kwargs (see 598fbde).
=> Improved default Q-transform whitening duration

gwpy/tests/test_timeseries.py, gwpy/types/io/hdf5.py
This PR fixes a problem storing pickled `Channel` objects in python3 as HDF5 attributes. We require to use the simple ASCII protocol '0'.
=> Fixed pickle of Channel in py3 when writing to Array to HDF5

gwpy/detector/units.py, gwpy/tests/test_detector.py
This PR improves the handling of plural unit names in `gwpy.detector.units.parse_unit`, so that multiple plural components in a compound name get handled individually. The upshot is that something like `meters/second` now gets parsed as `m/s`.
=> Improved handling of plurals in custom unit parser 

examples/frequencyseries/rayleigh.py, examples/spectrogram/rayleigh.py, gwpy/tests/test_timeseries.py, gwpy/timeseries/io/losc.py, gwpy/timeseries/timeseries.py
This PR fixes a bug in the `TimeSeries.rayleigh_spectrogram` method - the `window` keyword is not supported for this method.
Associated with this fix are the following improvements
- [4e88c01] updated Rayleigh examples
- [5982538] optimised LOSC I/O (use HDF5 by default if `h5py` is installed)
=> Fixed bugs in computing Rayleigh spectrogram

gwpy/signal/fft/registry.py, gwpy/table/io/fetch.py, gwpy/tests/test_signal.py, gwpy/timeseries/timeseries.py
This PR fixes bugs in the tables embedded into method docstrings by registry-linked things, including for `EventTable.fetch` and `TimeSeries.psd` etc.
Also included are a few other miscellaneous docstrings fixes. No actual code was changed (other than code that generates the docstrings).
=> Fixed bugs in docstrings for registry-style tables

gwpy/detector/units.py, gwpy/tests/test_array.py, gwpy/tests/test_detector.py
This PR updates the `parse_unit` method to forgive any and all problems in the unit naming, by creating a new `NamedUnit` on-the-fly whenever a problem is created. This should allow mathematical operations on any and all frame data (including from NDS2), but does not allow conversions from these custom units into other units. The new units are also not registered, so that they cannot be compared to other physical units.
This also extends the format subclass to try and mangle the given name into a form it recognises, and defines a bunch of new LIGO-specific unit formats (e.g. `ptcls`) so that a custom `NamedUnit` is created only as a last resort.
Fixes #523.
cc: @areeda
=> Update to unit parser to forgive all errors

examples/frequencyseries/rayleigh.py
This PR fixes a trivial typo in one of the examples.
=> Fixed a typo in an example [ci skip]

gwpy/plotter/rc.py
This PR improves the user-selection for using LaTeX in figure generation, by adding a `GWPY_USETEX` environment variable, and improving the default `rcParams` when `text.usetex=False`.
=> Improved support for non-latex image generation

gwpy/plotter/core.py
This PR fixes a 'feature' in `Plot.add_colorbar` so that specifying `location='top'` will default to having a horizontal colour bar, rather than a very short vertical one.
=> Fixed orientation for adding colorbar with location='top'

gwpy/segments/io/ligolw.py
This PR fixes a precision issue when writing segments to `LIGO_LW` XML format. Casting to `float` loses precision compared to `LIGOTimeGPS`. I think this was an issue when attempting to cast directly from `numpy.float64` to `glue.lal.LIGOTimeGPS`, but we don't use the `glue` object any more, so this shouldn't be a problem any more.
=> Don't cast GPS times to float when writing segments to LIGO_LW

gwpy/timeseries/statevector.py
This PR fixes the use of the `dtype` keyword in `StateTimeSeries.to_dqflag`. The new default is the `dtype` of the time index of the input series, but allows casting up-front to other types, e.g. `LIGOTimeGPS`, rather than after-the-fact, which caused precision issues.
=> Fixed dtype casting in StateTimeSeries.to_dqflag

gwpy/utils/__init__.py
This PR removes the import of the `.deps` submodule from `gwpy.utils.__init__`. This module is deprecated, so the import invokes the `DeprecationWarning` unnecessarily. Users can still import the module and its contents directly:
```python
>>> from gwpy.utils.deps import *
```
=> Removed import of deps submodule from gwpy.utils

gwpy/types/array2d.py
This PR fixes iterating over an `Array2D` (including a `Spectrogram`). Since we overload `__getitem__` to return a custom column class, we need to bypass `astropy.units.Quantity.__iter__` to just call out to `__getitem__`.
=> Fixed iteration over Array2D

docs/index.rst, docs/plotter/colors.rst, docs/plotter/index.rst, examples/frequencyseries/hoff.py, examples/signal/gw150914.py, gwpy/plotter/colors.py
This PR modifies the `gwpy.plotter.colors` module to register the IFO colours (previously `GW_OBSERVATORY_COLORS`) with matplotlib so that they can be referenced as normal when plotting, e.g.:
```python
from gwpy.timeseries import TimeSeries
from gwpy.plotter import TimeSeriesPlot
h1 = TimeSeries.fetch_open_data('H1', 1126259457, 1126259467)
h1b = h1.bandpass(50, 250).notch(60).notch(120)
l1 = TimeSeries.fetch_open_data('L1', 1126259457, 1126259467)
l1b = l1.bandpass(50, 250).notch(60).notch(120)
plot = TimeSeriesPlot(figsize=(8, 4))
ax = plot.gca()
ax.plot(h1b, color='gwpy:ligo-hanford', label='LIGO-Hanford')
ax.plot(l1b, color='gwpy:ligo-livingston', label='LIGO-Livingston')
ax.set_xscale('seconds', epoch=1126259462)
ax.set_xlim(1126259462, 1126259462.6)
ax.set_xlabel('Time (seconds) …
```
=> Register named IFO colours with matplotlib

gwpy/plotter/colors.py
This PR fixes a version incompatibility introduced by #542 when using matplotlib 1.x.
=> Fixed use of named colours for matplotlib 1.x

gwpy/signal/qtransform.py, gwpy/tests/test_timeseries.py, gwpy/timeseries/timeseries.py
This PR improves the default normalisation of the Q-transform output (via `TimeSeries.q_transform`) to use the median, instead of the mean, and add support for using the mean via `norm='mean'`.
=> Updated normalisation in q-transform to median by default

gwpy/tests/test_timeseries.py, gwpy/timeseries/io/hdf5.py
This PR fixes a bug in auto-detecting `TimeSeries` datasets in an HDF5 file.
=> Fixed bug in auto-detecting keys reading TimeSeriesDict from HDF5

gwpy/plotter/core.py, gwpy/tests/test_plotter.py
This PR fixes errors in the test suite when asserting warnings for an empty legend. matplotlib 2.1 doesn't seem to warn any more...
=> Fixed test failures in add_legend

gwpy/io/utils.py, gwpy/tests/test_io.py
This PR commits one useful and one trivial improvement to `gwpy.io.utils`:
- [bddae73] patched `gopen` to identify gzipped content in open files
- [a77b173] added unit tests for `identify_factory` and made pedantic improvements
=> Improvements to gwpy.io.utils module

docs/table/histogram.rst, docs/table/io.rst, docs/table/plot.rst, docs/table/rate.rst, examples/table/histogram.py, examples/table/rate.py, examples/table/rate_binned.py, examples/table/scatter.py, examples/table/tiles.py, gwpy/io/cache.py, gwpy/io/ligolw.py, gwpy/segments/flag.py, gwpy/segments/io/ligolw.py, gwpy/table/io/ligolw.py, gwpy/tests/test_io.py, gwpy/tests/test_table.py
This PR simplifies the LIGO_LW interface, mainly by deprecating the table-dependent format registrations, in favour of a single format ``ligolw`` where I/O routines now accept (expect?) a ``tablename=`` keyword argument.
In the most common form, the following example:
```python
EventTable.read('events.xml', format='ligolw.sngl_burst')
```
should be updated to
```python
EventTable.read('events.xml', format='ligolw', tablename='sngl_burst')
```
This change allows for a simpler implementation of the interface, and also native discovery of ``LIGO_LW``-format files by their content, not by the file name.
The documentation has been updated to match the new syntax.
=> Simpler implementation of LIGO_LW interface

ci/install.sh, ci/lib.sh, ci/test.sh, gwpy/tests/test_frequencyseries.py, gwpy/tests/test_io.py, gwpy/tests/test_segments.py, gwpy/tests/test_timeseries.py
This PR fixes a bug in the TravisCI configuration introduced by #552 whereby a failing pytest run wouldn't be picked up by Travis itself.
=> Fixed bugs in identifying failed tests in travis CI

docs/conf.py, docs/install/index.rst, docs/segments/dqsegdb.rst, docs/segments/index.rst, docs/segments/io.rst, docs/signal/fft.rst, docs/table/io.rst, docs/timeseries/io.rst, docs/timeseries/remote-access.rst, examples/timeseries/pycbc-snr.py
This PR adds an `rst_epilog` to the sphinx `conf.py` so that `references.txt` is implicitly included in all pages, and removes any explicit inclusions from files.
=> Updated sphinx conf to use rst_epilog to include references.txt

.travis.yml, ci/install.sh
This PR adds another job to the CI configuration that uses the `--pre` option to `pip install` to test against pre-releases of the dependencies.
=> Added python3.5 CI build with --pre

.gitignore, MANIFEST.in, ci/install-debian.sh, ci/install-macos.sh, setup.cfg, setup.py, setup_utils.py
This PR reworks `setup.py` in the following ways
- moved custom command definitions and utilities to `setup_utils.py`, allowing for a slimmed-down `setup.py` script (which is much more readable)
- created new `bdist_spec` and `changelog` commands that are then called by `egg_info` to create the `gwpy.spec` and `debian/changelog` files - these are required in the tarball that gets sent to software.ligo.org for LDG packaging, so this fixes #560
=> Modified setup to include spec file and debian/changelog in sdist tarball

gwpy/cli/cliproduct.py
This PR sets the default cmap for `gwpy.cli` to `'YlOrRd'` for `matplotlib<1.5` when the `'viridis'` map is not yet available.
cc: @areeda
=> Fixed default cmap for mpl < 1.5 in gwpy.cli

gwpy/table/io/ligolw.py, gwpy/tests/test_table.py
This PR fixes a bug in `table.io.ligolw` where the auto-discovery of the real columns for 'time' was broken probably by #550.
=> Fixed bug in auto-discovery of LIGO_LW columns for 'time'

gwpy/detector/io/clf.py, gwpy/detector/io/omega.py, gwpy/io/nds2.py, gwpy/segments/flag.py, gwpy/signal/fft/registry.py, gwpy/tests/test_utils.py, gwpy/timeseries/core.py, gwpy/utils/compat.py
This PR deprecates (but doesn't remove) the `gwpy.utils.compat` module which so far only provided an import for `OrderedDict`. Since we don't support python2.6 anymore, we don't need it.
=> Deprecated unnecessary gwpy.utils.compat module

docs/index.rst, docs/spectrum/index.rst, docs/spectrum/io.rst, gwpy/frequencyseries/io/ligolw.py, gwpy/io/ligolw.py, gwpy/tests/test_frequencyseries.py, gwpy/types/io/ligolw.py
This PR adds support (including implementation, tests, and documentation) for reading a `FrequencySeries` from a `<LIGO_LW>` element containing an `<Array>`. This is used in the LSC for uploading PSDs to GraceDB (by at least one search).
=> Added support for reading FrequencySeries from LIGO_LW Array elements

gwpy/tests/test_array.py, gwpy/types/index.py
This PR patches `Index.__getitem__` to return scalar items as a `Quantity`, rather than a 0-dimensional `Index`, mainly because that doesn't really make sense.
A test case for the `Index` object has also been added.
=> Index should return elements as Quantity, not Index

.travis.yml, ci/lib.sh, gwpy/types/io/hdf5.py, setup.py
This PR extends the travis CI configuration to include simple builds against python 3.4 and 3.6, and adds classifiers in `setup.py` to display the compatible python versions.
=> Added CI jobs to test simple build against python 3.4 and 3.6

gwpy/spectrogram/core.py, gwpy/tests/test_spectrogram.py
This PR fixes a problem using `numpy.ndarray.abs` in `Spectrogram.filter` - either this method has never existed, or is only available in an advanced version of numpy.
Also included is a unit test for `Spectrogram.filter` that would have exposed the bug.
=> Fixed bug in Spectrogram.filter

gwpy/spectrogram/core.py, gwpy/tests/test_spectrogram.py
This PR improves the unit tests for the `Spectrogram` object, and fixes a bug in one method.
=> Improvements to tests for Spectrogram

gwpy/plotter/gps.py, gwpy/plotter/timeseries.py
This PR fixes a bug in `gwpy.plotter.gps.GPSAutoScale`, used to automagically set the x-axis scale for timeseries-axes plots.
=> Fixed bug in GPSAutoScale

ci/install.sh, gwpy/tests/test_spectrogram.py
This PR works around a problem with the python `'nightly'` CI build reaching the 10,000 line log error. The fix is to apply the `PIP_FLAGS` environment setting to the 
```
pip install .
```
command, mainly so that the `--quiet` flag gets applied.
=> Install package with PIP_FLAGS in CI

ci/install-debian.sh, gwpy/tests/test_spectrogram.py
This PR fixes a test that fails when `h5py` is missing by adding a decorator to skip that test in that situation (since `h5py` is optional).
=> Added skip decorator for missing h5py in Spectrogram tests

gwpy/detector/units.py, gwpy/tests/test_detector.py
This PR fixes an issue with the custom `IrreducibleUnit`s that are produced by `gwpy.detector.units.parse_unit` when the unit string is not recognised. The patch is to use a `dict` to cache the new units as they are created so that each unit string only gets mapped to a new unit once, allowed for equality comparisons with units of the same name (they are now the same object).
This is required for `TimeSeries.is_compatible` and similar functions to pass on custom units.
=> Added workaround for IrreducibleUnit comparisons

gwpy/table/table.py, gwpy/tests/test_table.py
This PR fixes a corner-case issue in `EventTable.event_rate` when `numpy.histogram` can't handle `numpy.object_` dtypes. The fix is to cast these to `float64` on-the-fly.
=> Handle object dtypes in EventTable.event_rate

gwpy/table/filter.py, gwpy/table/io/root.py, gwpy/tests/test_table.py
This PR fixes a problem with filtering on-the-fly when reading ROOT files using `root_numpy`.
`root_numpy` has support for on-the-fly selections, but obviously can't handle gwpy-style function filters, so we need to separate out the simple filters from the function filters and perform each appropriately.
I updated the unit tests to capture this in `test_read_write_root`.
=> Fixed problems with filtering ROOT files when reading

docs/table/io.rst, gwpy/io/ligolw.py, gwpy/segments/io/ligolw.py, gwpy/table/io/ligolw.py, gwpy/tests/test_table.py
This PR implements a new keyword argument `use_numpy_dtypes` when reading `LIGO_LW`-format XML files into a `Table`. This casts known custom object types to numpy types to prevent `numpy.object_` dtypes in the returned table (since e.g. HDF5 can't write them).
=> Added option to cast ligolw types to numpy when reading Tables

gwpy/timeseries/io/nds2.py
This PR modifies `timeseries.io.nds2` to use the astropy `ProgressBar` instead of the custom built progress indicator, for `verbose=True`, the astropy one looks better.
We might end up moving to `tqdm` for this, but the principal is basically the same.
=> Use astropy's ProgressBar to show progress in TimeSeries.fetch

.travis.yml, gwpy/io/ligolw.py, gwpy/tests/test_table.py
This PR adds a docker build for the `ligo-software/stretch-proposed` image, which should get a bit further on python3 (according to @tpdownes).
=> Added stretch-proposed docker build to CI

gwpy/io/mp.py, gwpy/segments/flag.py, gwpy/table/table.py, gwpy/utils/mp.py
This PR implements a multiprocess-friendly `ProgressBar` mainly for the `gwpy.io.mp.read_multi` I/O utility method. With this enable (`verbose=True`) you should get something like this: 
```
Reading (ligolw):
|==========================================| 1.8k/1.8k (100.00%)      1m48s
```
All kudos go to whomsoever added this to Astropy.
=> Added verbose output to gwpy.io.mp.read_multi

gwpy/tests/test_timeseries.py, gwpy/timeseries/core.py, gwpy/timeseries/io/gwf/__init__.py, gwpy/timeseries/io/gwf/framecpp.py, gwpy/timeseries/io/gwf/lalframe.py, gwpy/timeseries/io/losc.py, gwpy/timeseries/statevector.py, gwpy/types/array.py
This PR combines a few different improvements related to `TimeSeries.fetch_open_data`, namely
- use astropy progress bar for `verbose=True`
- enable astropy download caching with `cache=True`
- fixed errors when `format='gwf'`
- improved unit tests for both `TimeSeries` and `StateVector`
=> Improvements to LOSC data fetching

.pep8speaks.yml, docs/conf.py, docs/signal/index.rst, gwpy/frequencyseries/_fdcommon.py, gwpy/frequencyseries/core.py, gwpy/plotter/filter.py, gwpy/signal/filter_design.py, gwpy/spectrogram/core.py, gwpy/tests/test_spectrogram.py, gwpy/tests/test_timeseries.py, gwpy/timeseries/timeseries.py
This PR improves the way FIR and IIR filters are passed to filtering functions, and normalises duplicated code into the relevant modules. Summary is:
- new common methods under `signal.filter_design` for parsing filter arguments, and converting analog ZPK to digital, used by `<Array>.filter` instance methods
- added common frequency-domain methods module as `frequencyseries._fdcommon`, which now feeds `FrequencySeries.filter` and `TimeSeries.filter`
- improved documentation of methods and functions
=> Improved filtering definitions and parsing

gwpy/plotter/timeseries.py, gwpy/plotter/utils.py, gwpy/tests/test_plotter.py, gwpy/tests/test_spectrogram.py
This PR enables using `imshow()` for rendering a `Spectrogram` via `TimeSeriesAxes.plot_spectrogram`. matplotlib 2.0 finally fixed the problem of images on a log axes, so we can use it for spectrograms! It is not the default option whenever mpl >= 2.0 is present.
Fixes #172.
=> Added support for imshow in plotting spectrograms

gwpy/plotter/gps.py
This PR implements a slight optimisation of the use of `decimal.Decimal in `plotter.gps`. The `GPSTransform` uses `decimal.Decimal` via `str` to guarantee precision when converting to/from 19-sigfig GPS times, but we need to do this only when absolutely necessary, because it's very slow.
=> Optimised (minimised) use of decimal.Decimal in GPSTransform

gwpy/utils/misc.py, gwpy/utils/mp.py
This PR adds a new submodule `gwpy.utils.misc` that provides `null_context`, an empty `contextmanager` useful in a `with` statement where a context is optional (i.e. in progress bars for verbose `utils.mp`).
=> Added empty contextmanager utility

gwpy/timeseries/io/gwf/framecpp.py
This PR adds a small optimisation to the frameCPP GWF reader in `timeseries.io.gwf.framecpp` which allows user to specify number of frames via `nframes=<int>`, so we don't have to query for it, which can be slow.
=> Added nframes kwarg to frameCPP GWF reader

gwpy/utils/mp.py
This PR speeds up the prep for `multiprocessing_with_queues` by using an unsized input `Queue`, meaning we can `queue.put(..., block=False)`.
=> Use unsized input Queue when preparing multiprocessing_with_queues

docs/signal/fft.rst, gwpy/signal/fft/pycbc.py
This PR adds the ``scheme`` keyword argument to the `signal.fft.pycbc` FFT methods, allowing the user to specify a `Scheme` context object in which to perform the FFT operations.
=> Added ``scheme`` keyword to pycbc FFT methods

gwpy/io/cache.py, gwpy/io/mp.py, gwpy/io/registry.py, gwpy/signal/fft/ui.py, gwpy/spectrogram/core.py, gwpy/tests/test_io.py, gwpy/tests/test_timeseries.py, gwpy/timeseries/core.py, gwpy/timeseries/io/cache.py, gwpy/timeseries/io/gwf/__init__.py, gwpy/timeseries/timeseries.py, gwpy/types/array2d.py
This PR reinstates an improved version of  `gwpy.timeseries.io.cache`, which provides an efficient reader of `TimeSeries` data from cache files - at least more efficient than a simple `map` from `gwpy.io.mp`.
=> Reinstated timeseries.io.cache module for multiprocessing cache reading

ci/install.sh, setup_utils.py
This PR fixes the broken build (see [travis-ci/315512380](https://travis-ci.org/gwpy/gwpy/builds/315512380)): GitPython 2.1.8 is required to operate alongside git 2.15 [[ref]].
[ref]: https://github.com/gitpython-developers/GitPython/issues/687#issuecomment-350780349
=> Bump required GitPython for setup

gwpy/io/datafind.py
This PR fixes a missing `return` for the specific case of a file returned from a datafind 'latest' query that wasn't readable, or was on tape.
=> Fixed missing return for gwpy.io.datafind._find_latest_frame

gwpy/timeseries/core.py, gwpy/timeseries/io/nds2.py
This PR introduces a minor improvement to `gwpy.timeseries.io.nds2`  with calls to `nds2.connection.set_parameter` abstracted to a new method, mainly so that error handling/warnings are only handled once.
This introduces no changes to the logic in the calling `fetch` method.
=> Abstracted nds2.connection.set_parameter calls to function

gwpy/io/nds2.py, gwpy/plotter/core.py, gwpy/tests/test_array.py, gwpy/tests/test_cli.py, gwpy/tests/test_frequencyseries.py, gwpy/tests/test_io.py, gwpy/tests/test_plotter.py, gwpy/tests/test_table.py, gwpy/tests/test_timeseries.py, gwpy/types/series.py
This PR catches a lot of warnings emitted from the test suite, either by catching them appropriately with `pytest.warns` (which also acts as a test that the warning gets emitted when it should), or by modifying the test or module code to not produce the warning in the first place.
This should clean up the test output, and make finding problems easier in the future, especially when scanning the warning dump.
=> Fixed a lot of warnings in the test

gwpy/detector/units.py, gwpy/tests/test_detector.py
This PR fixes an issue in `gwpy.detector.units.parse_unit` with `parse_strict='silent'` by adding a class attribute that controls whether warnings should be emitted. It's a bit clunky, but it works.
=> Fixed warnings in parse_unit if parse_strict='silent'

docs/astro/index.rst, docs/index.rst, gwpy/astro/range.py, gwpy/tests/test_astro.py
This PR makes some internal improvements to astro.range
- preformat PSDs to ensure unit=1/Hz
- use proper `Quantity` operations throughout to make sure units get handled properly
- don't pass 0 Hz from PSD in testing, always ends up with a `RuntimeWarning` (which it should, its just annoying)
- removed `unit` kwarg from all `astro.range` methods, its unnecessary
=> Minor improvements to astro.range

gwpy/frequencyseries/_fdcommon.py, gwpy/plotter/filter.py, gwpy/signal/filter_design.py, gwpy/tests/test_plotter.py, gwpy/tests/test_signal.py, gwpy/timeseries/timeseries.py
This PR reworks `gwpy.signal.filter_design.parse_filter` (renamed from `parse_digital_lti`) to make it simpler. The return is now just the filter type (`'ba'` or `'zpk'`) and the filter components. The main improvement here is that FIR filters aren't shoe-horned through `scipy.signal.lti` so we don't get annoying warnings about bad filter coefficients.
A small set of other improvements are included, but have no impact on the API.
=> Improvements to internal parse_filter method

gwpy/timeseries/io/gwf/framecpp.py
This PR fixes a bug in reading GWF data with frameCPP; the index of the end of the array needs to be rounded down, and never up, since ADC samples are typically considered semi-open `[)` intervals
=> Fixed rounding error in frameCPP GWF reading

docs/table/filter.rst, gwpy/table/filter.py
This PR improves the documentation for `gwpy.table.filter` by adding some documentation notes about the importance of quoting strings, especially if they may contain non-alpha-numeric characters (e.g. LIGO channel names).
=> Added documentation notes about quoting strings in table filters [ci skip]

gwpy/table/filter.py, gwpy/tests/test_table.py
This PR fixes a bug in `gwpy.table.filter` whereby `unicode` names were not being parsed properly. The fix is to use `six.string_types` to accept `str` and `unicode` throughout.
=> Fixed bug in parsing table filters with unicode names

ci/install-macos.sh, gwpy/io/datafind.py, gwpy/tests/mocks.py, gwpy/tests/test_io.py, gwpy/timeseries/core.py
This PR introduces a rewrite of the `gwpy.io.datafind.find_frametype` method to support searching for matching types for multiple channels. `TimeSeriesBaseDict.find` has been patched to use this new functionality, which should greatly speed up multi-channel finds.
The logic in the new `find_frametype` looks very complicated, but hopefully the inline comments are enough to help readers understand the flow.
=> Optimised io.datafind.find_frametype for multiple channels

gwpy/table/io/ligolw.py, gwpy/tests/test_table.py
This PR improves auto-handling of `gpsproperty` instances in LIGO_LW tables (from `glue.ligolw.lsctables`), by auto-reading the constituent columns (e.g. reading `peak_time` and `peak_time_ns` when someone requests `peak`).
=> Improved handling of gpsproperty when reading LIGO_LW tables

gwpy/time/_tconvert.py
This PR works around the annoyance of `XLALError` statements being printed when tconverting _to_ GPS because `LIGOTimeGPS` doesn't like non-floatable strings.
=> Updated tconvert() to use float() to test GPS, avoids XLALError warnings

gwpy/tests/test_signal.py
This PR adds a new unit test for `gwpy.signal.fft.get_default_fft_api()`. I couldn't think of an elegant test, so the test essentially reproduces the functional code to check that it worked. Changes are I didn't mess it up twice.
=> Added test of signal.fft.get_default_fft_api

docs/conf.py, docs/index.rst
This PR adds a sphinx dependency on `ifconfig` to support a disclaimer reminding viewers of the development documentation `/latest` that things might not be 100% stable.
=> Added disclaimer to dev docs [ci skip]

.travis.yml
This PR adds a fix for the CI failures caused by a shallow clone on travis. This caused versioneer failures that escalated to a `dpkg-buildpackage` failure on debian images.
=> Fixed CI failure caused by shallow clone on travis

ci/install-debian.sh, ci/lib.sh, debian/control
This PR updates the `Build-Requires` list in `debian/control` to match what is actually required, and updated ci instructions to duplicate build-requires list, which should prevent further `setuptools` incompatibility issues.
=> Updated Build-Requires in debian/control

gwpy/timeseries/io/hdf5.py, gwpy/timeseries/io/wav.py
This PR fixes #627 by patching `gwpy.timeseries.io.wav` to catch errors identifying wav-format files. I also patched this a second time by explicitly setting `format='hdf5'` for the `TimeSeries.write` calls inside of `TimeSeriesDict.write` for `format='hdf5'`.
=> Fixed bug in writing TimeSeriesDict with HDF5

requirements-dev.txt, requirements.txt, setup.py
This PR updates the dependencies (`setup.py` and `requirements.txt`) to avoid installing matplotlib 2.1.x, see matplotlib/matplotlib#10003.
=> Updated dependencies to avoid matplotlib 2.1.x due to bug in mlab.cohere()

ci/install-debian.sh
This PR adds an option to install 'Suggests' packages in debian CI builds. This should hopefully extend the test suite coverage a wee bit.
=> Install suggested packages for gwpy

README.md
This PR separates the project status badges into release (`master`) and development (`develop`) groups, so that people can see progress between releases.
=>  Separate release/development badges on README [ci skip]

gwpy/cli/qtransform.py
This PR fixes the [current CI Failures](https://travis-ci.org/gwpy/gwpy/builds/327600956) by fixing an error in the usage of the `search` kwarg for `TimeSeries.q_transform`.
This param is a one-sided window duration, meaning the search is actually `[gps-search, gps+search)`, so we need to pass `duration/2.` to search the entire `TimeSeries`. Fixing this then prevents any warnings from `TimeSeries.crop`.
cc: @areeda
=> Fixed CI failures due to excessive warnings

gwpy/spectrogram/core.py, gwpy/types/series.py
This PR fixes inconsistensies and bugs in the `Series.crop` and `Spectrogram.crop_frequencies` methods that meant (a) the behaviour was wrong, and (b) the behaviour was different between these methods.
=> Fixed bugs and inconsistencies in crop() methods

gwpy/signal/filter_design.py, gwpy/tests/test_timeseries.py
This PR fixes #344 by patching `gwpy.signal.filter_design.parse_filter` to handle second order sections as input, which feeds into `TimeSeries.filter`, `Spectrogram.filter`, and `BodePlot`.
=> Enable parsing SOS for TimeSeries.filter and friends

bin/gwpy-plot
We seem to have lost a test for  no display that requires a different backend.
=> gwpy-plot re-add check for need for no display matplotlib renderer

ci/docker-install.sh, ci/install.sh
This PR modifies the CI configuration to use `--quiet` when install the `requirements-dev.txt` file. This should hopefully prevent [annoying errors](https://travis-ci.org/gwpy/gwpy/jobs/329240853) from travis.
=> Added --quiet flag to pip install for dev to prevent travis errors

MANIFEST.in
This PR fixes a problem with the `sdist` for debian builds by explicitly adding `include debian/source/*` to `MANIFEST.in.
=> Added debian/source/ to MANIFEST

ci/install-debian.sh, ci/install-el.sh, debian/control, etc/spec.template, setup.py
This PR modifies `setup.py` to only use fancy dependency specification for matplotlib if the version of setuptools will support it. This should simplify the build for debian and RHEL packages.
=> Don't use fancy dependencies if not supported by setuptools

ci/install-debian.sh, ci/install-el.sh, ci/install.sh, etc/spec.template, setup_utils.py
This PR modifies the build sequence in a few ways:
- modified `setup_utils.py` to only require `GitPython >= 2.1.8` if the installed version of `git` itself is `>= 2.15.0`
- install `GitPython>=2.1.8` manually for CI builds on RHEL
- upgrade `setuptools` _after_ the package build to help installing from requirements files
=> Fixes to builds on RHEL with mock/chroot

gwpy/tests/test_io.py
This PR updates a unit test to include the O1 dataset in LOSC test output, since that dataset has now been released. In the future we should probably mock that test to control the output.
=> Updated tests to include 'O1' in LOSC test output

ci/install-debian.sh, ci/install-el.sh
This PR modifies the CI builds for debian and RHEL linux to install both of the python2 and python3 packages at the same time, mainly to test for conflicts between them.
=> Install python2 and python3 packages during CI for debian and rhel

.travis.yml
This PR fixes (attempts to fix) a bug in the pypi deployment configuration on travis-ci where _all_ python2.7 builds attempt to upload a tarball to pypi.python.org. The trick, hopefully, is to add the condition `-z "${DOCKER_IMAGE}"` to only deploy for non-docker builds.
=> Fixed duplicate pypi deployment by excluding docker builds

etc/spec.template
This PR fixes a bug in the `spec.template` file that ended up with `/usr/bin/python3.4` as a dependency of the `python2-gwpy` RPM package.
The trick is that we need to build python2 _after_ python3, so that the resulting `bin/` files have `/usr/bin/python2` in their shebang line - this gets pulled into the dependencies for the resulting `python2-gwpy` RPM package.
This also means that when we move to having `python3x-gwpy` supply the binaries, we need to switch the `%build` order back again.
=> Fixed bug in RPM spec file that adds python3.4 as a dependency of python2-gwpy

.codeclimate.yml, gwpy/io/losc.py, gwpy/tests/test_timeseries.py, gwpy/timeseries/core.py, gwpy/timeseries/io/losc.py
This PR updates the LOSC API to handle multiple dataset tags and versions. This solves the problem of separating uncleaned `'C00'` data from cleaned `'CLN' data, and also multiple versions of the same data. By default the highest discovered version is returned, while multiple tags raises a `ValueError` that lists the available tags.
`TimeSeries.fetch_open_data` documentation was updated to describe the new kwargs, and give examples of how to use them.
=> Updated LOSC API to handle multiple tags and versions

gwpy/io/datafind.py, gwpy/tests/test_io.py
This PR fixes a broken error state in `gwpy.io.datafind.find_best_frametype` where only if _all_ channels were not matched would a `ValueError` be raised.
Now, if _any_ channel is not matched to a frametype, an error is raised.
=> Fixed error raising in io.datafind.find_best_frametype

.travis.yml, ci/install.sh
This PR modifies `.travis.yml` to use `python: '3.6'` for the `pip install --pre` CI job. Scipy doesn't seem to want to build on `python: 'nightly'` and the purpose of this job is to find breaking changes in dependencies, not necessary the python standard library.
=> Use python 3.6 for pre-release CI build

ci/install.sh, ci/lib.sh, requirements.txt, setup.py
This PR updates `setup.py` and `requirements.txt` to use [PEP-508](https://www.python.org/dev/peps/pep-0508/) for fancy dependency specification, allowing the following specifications:
- astropy<3 for python<3
- matplotlib!=2.1.[01] (broken)
`enum34` is still specified using a `try/except` so that systems with old versions of `setuptools` still get the correct basic requirements.
=> Use PEP-508 to specify dependencies

gwpy/io/losc.py, gwpy/tests/test_io.py
This PR adds a new `event_gps()` method to `gwpy.io.losc` to return just the GPS time of an event, as recorded by LOSC.
This is useful to build GPS segments for use with `TimeSeries.fetch_open_data` and friends.
=> Added event_gps method to gwpy.io.losc

gwpy/signal/qtransform.py
This PR removes the `raise StopIteration()` statements from `gwpy.signal.qtransform. These are unnecessary, and will result in exceptions in an upcoming version of python.
=> Removed raise StopIteration calls from signal.qtransform

gwpy/timeseries/io/losc.py
This PR makes a trivial improvement to the `verbose=True` output of `TimeSeries.fetch_open_data`.
=> Improved verbose output of TimeSeries.fetch_open_data

gwpy/segments/flag.py, gwpy/tests/test_segments.py
This PR improves the default server and method logic in `gwpy.segments.flag` for the `DataQualityFlag` and `DataQualityDict` objects.
- fixes #664 by matching only `geosegdb` to `query_segdb()`
- fixes #665 by using `DEFAULT_SEGMENT_SERVER` for default query URL
=> Improved default server selection in DataQualityFlag.query*

gwpy/tests/test_segments.py
This PR fixes the expected results from `DataQualityFlag.fetch_open_data` to accommodate an upstream bug-fix to the LOSC timeline segments. This should serve as a reminder that this test should use `mock`, and not rely on an actualy download from losc.ligo.org.
=> Updated expected LOSC timeline results to handle upstream change

gwpy/tests/test_io.py
This PR fixes an out-of-date test, broken by an upstream change in the LOSC JSON metadata for GW150914.
=> Updated tests to match updated LOSC JSON metadata for GW150914

gwpy/tests/test_table.py
This PR improves the error handling in the tests of `GravitySpyTable.search` by catching `URLError` as well as `SSLError` (see, e.g, [this failure](https://travis-ci.org/gwpy/gwpy/jobs/342725747)).
cc: @scottcoughlin2014
=> Improved error handling in TestGravitySpyTable

ci/install-macos.sh, etc/Portfile.template, setup_utils.py
This PR updates the template `Portfile` for macports, based on discussions with the macports maintainers, and reworks the `setup.py port` command to use the tarball that exists on pypi.python.org to get the checksums, since that is what will be downloaded during `port install py-gwpy`.
=> Updated setup.py port command

.gitignore, docs/Makefile, docs/index.rst, docs/zenodo-citations.py, requirements-dev.txt, setup.py
This PR adds the `/docs/zenodo-citations.py` script to auto-generate a page of DOIs to help people who want to cite GWpy.
=> Added documentation page for citations

gwpy/tests/test_timeseries.py, gwpy/timeseries/timeseries.py
This PR fixes a critical bug in `TimeSeries.spectrogram` whereby the `window` kwarg wasn't being used at all.
=> Fixed missing kwarg in TimeSeries.spectrogram

gwpy/signal/fft/basic.py, gwpy/signal/fft/lal.py, gwpy/signal/fft/pycbc.py, gwpy/signal/fft/registry.py, gwpy/signal/fft/scipy.py, gwpy/signal/fft/ui.py, gwpy/tests/test_signal.py, gwpy/tests/test_timeseries.py, gwpy/timeseries/timeseries.py
This PR fixes at least one bug in the `gwpy.signal.fft` methods for the `TimeSeries` class, and improves the tests of some of those methods.
=> Fixed bugs in TimeSeries FFT methods and improved tests

.pylintrc, debian/control, etc/spec.template, gwpy/frequencyseries/core.py, gwpy/signal/fft/lal.py, gwpy/tests/test_detector.py, gwpy/tests/test_timeseries.py, gwpy/tests/test_utils.py, gwpy/timeseries/core.py, gwpy/timeseries/io/gwf/lalframe.py, gwpy/utils/lal.py
This PR removes support for lal < 6.14.0 by simplifying the `gwpy.utils.lal` module. 6.14.0 was released in 2015, so is probably new enough.
Additionally this PR provides a few new methods to simplify mapping python types to LAL type strings (e.g. `float` -> `'REAL8'`).
Finally, I added tests of the functions in `gwpy.utils.lal`.
=> Simplified gwpy.utils.lal module for lal>=6.14.0

gwpy/io/cache.py, gwpy/segments/io/ligolw.py, gwpy/tests/test_io.py, gwpy/tests/test_time.py, gwpy/tests/test_timeseries.py, gwpy/timeseries/io/gwf/__init__.py, gwpy/utils/lal.py
This PR updates usage of `glue.lal` and `lal.utils` throughout gwpy now that (as of lscsoft-glue-1.58.1) `glue.lal` no longer explicitly depends on LAL.
=> Updated usage of glue.lal for glue-1.58.1

gwpy/tests/test_timeseries.py, gwpy/timeseries/core.py
This PR fixes #379 by improving the naming of the `StateTimeSeries` that results from a comparison operation on a `TimeSeries`.
=> Improved naming of StateTimeSeries for comparison outputs

examples/frequencyseries/index.rst, examples/frequencyseries/percentiles.py
This PR adds a new example, demonstrating `FrequencySeriesAxes.plot_frequencyseries_mmm`. Closes #298.
=> Added new example of FrequencySeriesAxes.plot_frequencyseries_mmm

gwpy/plotter/timeseries.py, gwpy/spectrogram/core.py
This PR improves the docstrings for `Spectrogram.plot` and `TimeSeriesAxes.plot_spectrogram`.
Fixes #462.
=> Improved docstring for Spectrogram.plot

gwpy/tests/test_array.py, gwpy/tests/test_timeseries.py, gwpy/types/array.py
This PR modifies `Array.__new__` to explicitly call `Array.copy()` for `Array(..., copy=True)`.
See astropy/astropy#7244. Fixes #446.
=> Use .copy() to ensure data ownership when creating Array

.travis.yml, ci/docker-install.sh, ci/install-debian.sh, ci/install-el.sh, ci/install-macos.sh, ci/install.sh, ci/lib.sh, gwpy/tests/test_segments.py
This PR modifies the configuration for CI builds using docker images, or macOS, to prevent implicit upgrades of system-installed dependencies and extras with `pip`. This should allow more robust testing of gwpy against system packages for debian/el/macos.
=> Reworked dependency installation for OS CI builds

gwpy/frequencyseries/hist.py, gwpy/tests/test_frequencyseries.py
This PR fixes a bug in `SpectralVariance` where the `yspan` property wasn't actually defined using `@property`.
=> Fixed bug in definition of SpectralVariance.yspan

examples/signal/gw150914.py, examples/table/rate.py, examples/table/rate_binned.py, examples/timeseries/public.py, examples/timeseries/statevector.py, gwpy/cli/cliproduct.py, gwpy/plotter/decorators.py, gwpy/tests/test_plotter.py, gwpy/timeseries/timeseries.py
This PR deprecates the `@axes_methods` decorator used in `gwpy.plotter.Plot` and subclasses to project methods of `Axes` onto `Plot` with a single `Axes`.
This magic was never documented properly, and is potentially confusing to use - it presents a non-standard usage for `Plot`s with multiple `Axes` - and potentially annoying to maintain.
@areeda, this includes a small change to `gwpy.cli` to remove usage of the decorator, so please take a look.
=> Deprecated the @axes_methods decorator

gwpy/io/losc.py, gwpy/tests/test_io.py
This PR fixes a bug in the `gwpy.io.losc.find_datasets` methods where the datasets were sort-ordered incorrectly, especially if a short dataset only partially overlapped the request (e.g. an event dataset).
=> Improved LOSC dataset sorting in find_datasets function

docs/timeseries/remote-access.rst, gwpy/timeseries/core.py, gwpy/timeseries/io/losc.py
This PR adds support for a new `GWPY_CACHE` environment variable, which allows automatic setting of `cache=True` for `TimeSeries.fetch_open_data` and similar methods. This can be very useful for repeated documentation/examples builds where the same data are downloaded many times (without hard-coding `cache=True` into the example code).
=> Added support for the GWPY_CACHE environment variable to automatically set cache=True

docs/segments/index.rst, gwpy/segments/flag.py, gwpy/tests/test_segments.py
This PR modifies the behavour of the `known` segmentlist during `DataQualityFlag` logic operations. The thinking is that the result of a logic operation should only be 'known' when both of the flags (on either side of the operator) were known, with the exception of 'or' (`|`, union), where either flag can be known.
One example of where this is important is when subtracting hardware injection segments from observing segments. If there is a gap in the knowledge of the injection flag then the result of `observing - injection` should only be known (or active) when both the observing and injection flags were known, just in case an injection was present during the gap in the knowledge of the flag, or similar.
=> Updated behaviour of known segments for DataQualityFlag logic operations

gwpy/cli/cliproduct.py
This PR fixes #341 by preserving order when uniquifying the `start_time` list in `gwpy.cli`.
cc: @areeda
=> Preserve order when uniquifying start times in gwpy.cli

gwpy/tests/test_timeseries.py, gwpy/timeseries/timeseries.py
This is my first pass at implementing a demodulation method for `TimeSeries` objects. The proposed method takes in a frequency and stride, and returns a new `TimeSeries` object with `dt=stride` which represents the original signal's average magnitude and phase at the given frequency as a complex number.
Also included in this pull request is a unit test which creates a pure sinusoid and then checks that `demod` correctly measures the amplitude and phase within acceptable precision. (Note, the error in this calculation decreases for arbitrary amplitude and phase as the stride increases.)
=> Demodulation method for TimeSeries objects

docs/segments/io.rst, gwpy/io/ligolw.py, gwpy/segments/flag.py, gwpy/segments/io/ligolw.py, gwpy/table/io/ligolw.py, gwpy/tests/test_io.py, gwpy/tests/test_segments.py, gwpy/tests/test_table.py
This PR improves the `LIGO_LW` XML interface, mainly to support writing `'process_id'`-like columns to LIGO_LW-format XML files for `DataQualityFlag`.
=> Enabled setting extra attributes for DataQualityFlag when writing to LIGO_LW

.travis.yml, setup.cfg
This PR modifies `setup.cfg` to build universal wheels, since this package is python2 and python3 compatible. This also simplifies the travis-ci configuration, since we now only need to deploy from a single version of python.
=> Build universal wheels

gwpy/plotter/filter.py
This PR fixes a bug (or two) in handling `frequencies` in `BodePlot`.
=> Fixed bugs with specifying frequencies in BodePlot

gwpy/timeseries/io/gwf/framecpp.py
This PR patches `gwpy.timeseries.io.gwf.framecpp` to work around a segmentation default from `LDAStools.frameCPP` when iterating directly over `FrAdcData.data`. The trick is to extract the size first and enumerate that (credit to @emaros for working that out).
=> Patch to work around segmentation fault when iterating in frameCPP

examples/signal/gw150914.py, gwpy/plotter/timeseries.py, gwpy/tests/test_timeseries.py, gwpy/timeseries/core.py
This PR adds a new instance method for `TimeSeries` to shift the timing of data. It's just a fancy call to `self.t0 = ...` that handles `Quantities`.
This PR includes an update to the GW150914 example to overlay H1 and L1 (using `TimeSeries.shift`).
=> Added new TimeSeries.shift method

gwpy/plotter/axes.py, gwpy/tests/test_plotter.py, gwpy/utils/decorators.py
This PR deprecates the following custom `Axes` properties 
- `Axes.xlabel`
- `Axes.xlim`
- `Axes.logx`
- `Axes.ylabel`
- `Axes.ylim`
- `Axes.logy`
These don't really add functionality, have never been documented, and are a pain to maintain.
=> Deprecated custom Axes properties

gwpy/plotter/series.py, gwpy/tests/test_plotter.py
This PR fixes a bug in the labelling for `SeriesAxes.plot_mmm`, whereby the min and max lines were also labelled, if those `Series` had names.
=> Fixed labelling bug in SeriesAxes.plot_mmm

gwpy/plotter/histogram.py, gwpy/plotter/utils.py, gwpy/tests/test_plotter.py
This PR adds support for parsing `ax.hist` keywords directly in `Plot` constructors as part of `Plot._parse_kwargs`. This allowed a simplification of the `HistogramPlot` constructor which, until now, contained its own list of `ax.hist` keywords.
=> Added support for parsing histogram plot params in plot constructors

gwpy/plotter/series.py, gwpy/tests/test_plotter.py
This PR partially undoes some of the changes from #724 to not set `alpha` for the min and max lines, only the `fill_between` collections.
This PR also fixes a bug in the return from `SeriesAxes.plot_mmm`
=> Partial reversion of 724 to not set alpha for mmm lines

gwpy/tests/test_timeseries_io.py, gwpy/timeseries/io/cache.py
This PR fixes a corner-case bug where the multiprocessing segments generate by `gwpy.timeseries.io.cache.get_mp_cache_segments` would include the final segment with less than one sample of time in it (for minute-trends), which causes frameCPP to panic.
=> Fixed bug in generating multiprocessing segments in timeseries.io.cache

gwpy/frequencyseries/core.py, gwpy/tests/test_frequencyseries.py
I've taken a stab at altering the units and normalization of `FrequencySeries.ifft()` so that it reproduces the original timeseries after `TimeSeries.fft().ifft()`. I've also added a unit test to make sure this is the case.
This fixes https://github.com/gwpy/gwpy/issues/729.
=> Make FrequencySeries.ifft() consistent with TimeSeries.fft()

docs/dev/release.rst
This PR adds a note about how to GPG sign the release merge commit and tag, since I got it wrong for 0.9.0 and fucked things up.
=> Added GPG signing instructions to release docs page

.travis.yml, setup_utils.py
This PR patches `setup_utils.py` so that tags are sorted properly (by semantic version), so that 0.10.0 is sorted **after** 0.9.0.
This also bumps the xcode version to 9.2 in an attempt to fix [this build error](https://travis-ci.org/gwpy/gwpy/jobs/368544942).
=> Fixed sorting of tags in changelogs

gwpy/signal/window.py
This PR updates the import of the underlying `windows.py` module in scipy to `scipy.signal.windows.windows` for 1.1.0rc1. This is required to resolve the `_win_equiv` mapping used in the `canonical_name` method.
=> Fixed import of scipy windows module for 1.1.0rc1

gwpy/segments/flag.py, gwpy/tests/test_segments.py
This PR adds a `contract=False` keyword to `DataQualityFlag.round()` to reverse the logic to round start time up and end time down, and return the set of integer segments wholly contained within the active segments.
=> Added contract keyword to DataQualityFlag.round

gwpy/spectrogram/coherence.py, gwpy/tests/test_timeseries.py
This PR fixes a ridiculous bug in `TimeSeries.coherence_spectrogram` where the `dt` was set wildly incorrectly. This PR also adds unit tests for this and `TimeSeries.coherence`.
=> Fixed critical bug in TimeSeries.coherence_spectrogram, and added tests for coherence methods

gwpy/table/io/pycbc.py
This PR fixes bugs in reading PyCBC offline HDF5 files, which includes nested Groups and other columns that don't have the same number of elements as the 'main table' columns, so we need to exclude group names and `_template` columns to get a well-structured table.
cc: @scottcoughlin2014
=> Fixed bugs in reading offline PyCBC files

setup_utils.py
This PR fixes a naivety in `setup_utils.py` when parsing the output of `git --version`. On macOS:
```
$ /usr/bin/git --version
git version 2.14.3 (Apple Git-98)
```
so we need to strip the 2th (3rd) word of the output, and not the last.
cc: @scottcoughlin2014
=> Fixed bug in parsing git --version on macos

gwpy/segments/flag.py, gwpy/tests/test_segments.py, gwpy/tests/test_time.py, gwpy/time/_tconvert.py
This PR simplifies `gwpy.time._tconvert` to reduce the complexity of the module, which has the nice consequence of removing any (optional) dependency on LAL.
This also rewrites the tests for this module to use `parametrize()` to simplify the actual test functions.
=> Reworked internals of gwpy.time to reduce complexity

gwpy/segments/flag.py
Both `lal.LIGOTimeGPS.__add__()` and `glue.lal.LIGOTimeGPS.__add__()` are incompatible with `numpy.int32` datatypes, so padding values had to be cast to float when initializing a `DataQualityFlag`. This recovers the intended functionality of `DataQualityFlag.pad()` with `self.padding` as the intended padding window. It also fixes the bug with `DataQualityFlag.populate()` and `DataQualityDict.populate()` using padding windows from veto definers.
Fixes #750
=> Explicitly cast padding to float

gwpy/plotter/table.py, gwpy/tests/test_plotter.py
This PR deprecates the `size_by` and `size_by_log` keywords to `EventTableAxes.plot_table`, which have never really been tested (they definitely worked at some point, but aren't under unit test), and were never documented.
=> Deprecated size_by and size_by_log keywords for EventTableAxes.plot_table

gwpy/timeseries/io/gwf/__init__.py
This PR fixes a typo in deprecating the `dtype` keyword to `gwpy.timeseries.io.gwf.read`, introduced by #739.
=> Fixed typo in deprecation warning

ci/install-debian.sh, debian/control, etc/Portfile.template, etc/spec.template, gwpy/io/mp.py, gwpy/signal/fft/ui.py, gwpy/table/gravityspy.py, gwpy/tests/test_utils.py, gwpy/timeseries/core.py, gwpy/timeseries/io/nds2.py, gwpy/utils/mp.py, gwpy/utils/progress.py, requirements.txt, setup.py
This PR updates `gwpy.utils.mp` and adds a new module `gwpy.utils.progress` that uses [`tqdm`](https://pypi.org/project/tqdm/) for verbose progress bars.
This adds `tqdm` as a hard dependency for gwpy, which might be an issue for debian jessie.
UPDATE: this PR probably needs to sit here until `python-tqdm` is moved into production as part of the `lscsoft` `jessie` distributions. You can follow along [here](https://bugs.ligo.org/redmine/issues/6135) (required LIGO.ORG auth).
=> Use tqdm for progress bars

gwpy/tests/test_time.py, gwpy/time/_tconvert.py
This PR fixes a bug in `gwpy.time.to_gps` whereby it couldn't handle `str` representations of `float`.
=> Fixed to_gps('0')

gwpy/tests/test_timeseries.py, gwpy/types/io/hdf5.py
This PR improves the error handling inside `gwpy.types.io.hdf5.read_hdf5_array` to handle an `IndexError` raised by `pickle.loads`, which will happen whenever a channel name is stored in HDF5 as text without any delimiters:
```python
>>> from gwpy.timeseries import TimeSeries
>>> a = TimeSeries([1, 2, 3], channel='test')
>>> a.write('test.h5', path='/test', overwrite=True)
>>> TimeSeries.read('test.h5')
File "<stdin>", line 1, in <module>
...
File "/Users/duncan/Library/Python/2.7/lib/python/site-packages/gwpy/timeseries/io/hdf5.py", line 42, in read_hdf5_timeseries
series = read_hdf5_array(h5f, path=path, **kwargs)
File "/Users/duncan/Library/Python/2.7/lib/python/site-packages/gwpy/io/hdf5.py", line 59, in decorated_func
return func(h5f, *args, …
```
=> Catch `IndexError` from pickle.loads

.travis.yml, ci/docker-install.sh, ci/install-debian.sh, ci/install-el.sh, ci/install-macos.sh, ci/install.sh, ci/lib.sh, ci/test.sh, etc/spec.template, setup.cfg
This PR modifies the travis configuration to use the `ligo/base` images instead of `ligo/software` - I am informed that they are much smaller, and so should provide a faster build.
=> Use ligo/base docker images during CI

.pep8speaks.yml, docs/references.txt, gwpy/frequencyseries/core.py, gwpy/frequencyseries/hist.py, gwpy/io/cache.py, gwpy/io/ligolw.py, gwpy/spectrogram/core.py, gwpy/table/io/pycbc.py, gwpy/table/table.py, gwpy/tests/test_io.py, gwpy/tests/test_timeseries.py, gwpy/timeseries/core.py, gwpy/timeseries/io/cache.py, gwpy/timeseries/io/gwf/__init__.py, gwpy/timeseries/io/gwf/lalframe.py, gwpy/timeseries/statevector.py, gwpy/types/series.py
This PR removes any direct dependency on the `glue.lal.Cache` object, which has a complicated set up now that the `CacheEntry` is part of `lal.utils`.
This reduces our overall dependency on `glue` itself, meaning when we can move to using `ligo.segments`, we might be able to not rely on that package at all.
=> Remove dependency on glue.lal.Cache object

setup_utils.py
This PR updates `setup_utils.py` to work with pip-10.0, specifically the `setup.py port` command.
=> Updated setup_utils.py for pip 10

gwpy/tests/test_utils.py, gwpy/types/sliceutils.py
This PR fixes some test failures on python<3.5: `numpy.int64` is _not_ a subclass of `numbers.Integral` so need to directly compare to `numpy.integer`.
=> Fixed type comparison for np.int on python3.4

requirements-dev.txt
This PR pins the `pandas` version to `< 0.21` for python3.4; pandas >= 0.21 is python==2.7,>3.4 only.
=> Pin pandas version in requirements-dev.txt for python3.4

.gitignore, gwpy/tests/__init__.py, gwpy/tests/test_array.py, gwpy/tests/test_astro.py, gwpy/tests/test_cli.py, gwpy/tests/test_detector.py, gwpy/tests/test_frequencyseries.py, gwpy/tests/test_io.py, gwpy/tests/test_plotter.py, gwpy/tests/test_segments.py, gwpy/tests/test_signal.py, gwpy/tests/test_spectrogram.py, gwpy/tests/test_table.py, gwpy/tests/test_timeseries.py, gwpy/tests/test_utils.py, setup.py
This PR adds `/gwpy/tests/__init__.py`, elevating `gwpy.tests` to a proper sub-package, enabling running the tests as:
```
py.test --pyargs gwpy
```
=> Added init file for gwpy.tests sub-package

requirements-dev.txt
This PR modifies the dependency spec in `requirements-dev.txt` to force not installing pycbc-1.10.0 (the current release), which is broken.
=> Don't install pycbc-1.10.0, its broken

docs/conf.py
This PR modifies `/docs/conf.py` to set the matplotlib backend via `rcParams`, so that the `.. plot` directive can't override it.
=> Set matplotlib backend for docs in rcParams

.travis.yml, gwpy/tests/test_time.py, gwpy/time/__init__.py, gwpy/timeseries/core.py, requirements-dev.txt
This PR adds the `gwpy.time.gps_types` tuple, similar to `six.string_types`, which contains all available, known implementations of `LIGOTimeGPS`, e.g.:
```python
>>> from gwpy.time import gps_types
>>> print(gps_types)
(<type 'lal.LIGOTimeGPS'>, <class 'ligotimegps.LIGOTimeGPS'>, <class 'glue.lal.LIGOTimeGPS'>)
```
This is mainly useful for `isinstance` checks.
This includes a unit test that the included gps types are all API compliant.
=> Added gwpy.time.gps_types tuple

examples/table/histogram.py, examples/table/rate.py, examples/table/rate_binned.py, examples/table/scatter.py, examples/table/tiles.py, gwpy/plotter/table.py, gwpy/table/table.py
This PR introduces a new internal method `EventTable._get_time_column` to try and work out which column (if any) represents 'time' in the current table. This is useful for methods like `event_rate()` which require a time column to operate.
I also fixed the examples for `table` which were all still referring to the old magic 'time' column from the `sngl_burst` table.
=> New _get_time_column method for EventTable

gwpy/io/losc.py, gwpy/tests/test_io.py
This PR updates `test_io.py` to account for the new `O1_16KHZ` dataset published by losc.ligo.org.
=> Updated tests for O1_16KHZ dataset

gwpy/detector/units.py, gwpy/tests/test_detector.py
This PR adds another variant of the `'degrees_C'` unit to `gwpy.detector.units`; its easier on LIGO to just patch the weird units here, rather than letting individuals handle it on their own
=> Added more variants on degrees_C in detector.units

gwpy/timeseries/core.py
This PR improves the handling of domain-specific keywords for `TimeSeriesDict.get`, such that if users give any nds2-specific keywords, don't search using datafind.
=> Improved keyword handling in TimeSeriesDict.get

gwpy/plot/plot.py, gwpy/plot/tests/test_plot.py
This PR fixes up the `Plot` constructor to enable creating empty plots with multiple axes.
=> Fixed creation of empty Plot with geometry

gwpy/types/sliceutils.py, gwpy/types/tests/test_series.py
This PR fixes a bug in `gwpy.types.seriesutils` that caused a slice of a `Series` using a null boolean array (either no elements, or all `False`) to crash, and adds a regression test.
=> Fixed bug slicing Series with null boolean array

gwpy/plot/axes.py, gwpy/plot/tests/test_axes.py
This PR fixes a bug in `gwpy.plot.Axes.scatter`, which presumed the inputs were already `numpy.ndarray`s, which isn't required by matplotlib.
=> Fixed bug in Axes.scatter, need to cast to array before c_sorting

gwpy/frequencyseries/tests/test_frequencyseries.py, gwpy/plot/axes.py, gwpy/plot/tests/test_plot.py, gwpy/timeseries/tests/test_core.py, gwpy/timeseries/tests/test_statevector.py
This PR removes the last vestiges of passing `Quantity` arrays to matplotlib, since a number of the internals to matplotlib fall over when given those objects as opposed to scalars or arrays, especially when the units don't match across axes.
=> Modified gwpy.plot to just plot arrays, not quantities

gwpy/table/table.py, gwpy/table/tests/test_table.py
This PR improves the new private `EventTable._get_time_column` method, which attempts to guess the 'time' column for a table (which is tricksy if there isn't a column named `'time'`), and its usage in `EventTable.{binned_}event_rate{s}`.
=> Improvements to EventTable._get_time_column and dependents

examples/miscellaneous/open-data-spectrogram.py
This PR fixes the colorbar in the `open-data-spectrogram.py` example script, which was left including a debugging statement, presumably from testing of #790.
=> Fixed colorbar in open-data-spectrogram.py

gwpy/plot/segments.py
This PR fixes `SegmentAxes.plot` to not overwrite user settings for autoscaling, which would ignore any set y-axis limits, for example.
=> Fixed autoscaling after segment plotting in SegmentAxes

gwpy/plot/plot.py, gwpy/plot/tests/test_plot.py
This PR fixes `Plot([1, 2, 3, 4])`, which used to plot each integer separately, I think.
=> Fixed creating Plot from a list of numbers
