gwpy/gwpy

gwpy/plot/plot.py

This PR fixes #818 by removing a module-level import of `matplotlib.backends`, since that sets the backend preventing users from changing it with `matplotlib.use()`.
This should supersede #819.
cc: @areeda

Removed module-level import of matplotlib.backends in gwpy.plot.plot

---

gwpy/plot/plot.py
gwpy/table/table.py

This PR fixes two bugs related to default labels:
- [6a9a69d] preserve user-given labels during `Plot` creation
- [965ae61] preserve user-given labels during `EventTable.scatter` and `EventTable.tile`

Fixed bugs in default labels for Plots and EventTable plotting

---

.travis.yml
ci/coveralls.sh
ci/install-debian.sh
ci/install-el.sh
ci/install-macos.sh
ci/lib.sh
ci/test.sh
etc/spec.template
gwpy/segments/tests/test_flag.py
gwpy/segments/tests/test_segments.py
gwpy/timeseries/tests/test_statevector.py
requirements-dev.txt
requirements-doc.txt
requirements-test.txt
setup.py

This PR removes the python3 builds for RHEL7 (el7) and Debian Jessie (debian8), because they don't work, and those systems are too old to give useful python3 package support.

Removed python3 CI builds for el7 and debian8

---

gwpy/cli/qtransform.py

This PR fixes a bug in `gwpy.cli.Qtransform` where all generated figures would have the X-axis limits from the first generated figure. The fix is just to manually overwrite the `xmin` and `xmax` according to `outseg` for each figure.
cc: @areeda

Set x-axis limit for each Q plot in gwpy.cli

---

gwpy/frequencyseries/tests/test_frequencyseries.py
gwpy/frequencyseries/tests/test_hist.py
gwpy/segments/tests/test_flag.py
gwpy/spectrogram/tests/test_spectrogram.py
gwpy/table/tests/test_table.py
gwpy/tests/test_plotter.py
gwpy/timeseries/tests/test_core.py
gwpy/timeseries/tests/test_statevector.py

This PR modifies all tests to use `BytesIO()` when testing saving images, so that we never actually write anything to the filesystem.

Use BytesIO to test plot savefig() without touching the disk

---

gwpy/spectrogram/tests/test_spectrogram.py
gwpy/table/tests/test_table.py
gwpy/types/tests/test_array.py
gwpy/types/tests/test_series.py

This PR removes some unused methods, and unnecessary `print()` calls from the test modules.

Removed unused code from test suite

---

gwpy/table/io/cwb.py
gwpy/table/io/omega.py

This PR fixes an issue reading ASCII tables on Windows, which seems to receive extra empty lines when reading ASCII tables relative to Unix.

Fixed ascii header bug on Windows

---

gwpy/cli/tests/base.py
gwpy/detector/tests/test_channel.py
gwpy/io/tests/test_cache.py
gwpy/io/tests/test_kerberos.py
gwpy/io/tests/test_utils.py
gwpy/plot/tests/test_plot.py
gwpy/segments/tests/test_segments.py
gwpy/table/tests/test_table.py
gwpy/tests/utils.py
gwpy/timeseries/tests/test_timeseries.py

This PR introduces a new `TemporaryFilename` context manager for the test suite, which resolves an error testing under Windows where open files cannot be written to via their file name. The new context manager just creates a new file path as a `str` and returns that, cleaning up that file path upon exit, if the file was written.
This isn't threadsafe, but is good enough for testing purposes.

Use TemporaryFilename contextmanager for tests

---

gwpy/utils/shell.py
gwpy/utils/tests/test_shell.py

This PR simplifies `gwpy.utils.shell` as follows:
- use `distutils.spawn.find_executable` for `which`
- simplified tests to run under Windows

Simplified gwpy.utils.shell

---

requirements-dev.txt

This PR bumps the pycbc version to >= [1.10.1](https://github.com/gwastro/pycbc/tree/v1.10.1), a non-broken version that accepts window as numpy array for `pycbc.psd.welch`.

Bumped pycbc version in development requirements file

---

gwpy/frequencyseries/hist.py
gwpy/frequencyseries/tests/test_hist.py
gwpy/timeseries/statevector.py
gwpy/types/array.py
gwpy/types/array2d.py
gwpy/types/series.py
gwpy/types/sliceutils.py
gwpy/types/tests/test_array.py
gwpy/types/tests/test_array2d.py

This PR adds two new overloaded methods:
- `gwpy.types.Array.flatten` - returns a basic `Quantity` array, rather than the input subclass
- `gwpy.types.Array2D.T` (transpose property) - properly formats index arrays and units

Added overloaded array methods for flatten and transpose

---

ci/install-debian.sh
requirements-dev.txt

This PR attempts to fix (for example) [this build failure](https://travis-ci.com/gwpy/gwpy/jobs/136282460) when testing python3 on debian stretch by installing more packages with `apt`, so that `pip` has less to do.

Added more packages for python3 on debian

---

setup.py

This PR fixes a typo in `setup.py` that incorrectly sets the astropy version requirement for python2.7.

Fixed bug in astropy requirement spec

---

gwpy/timeseries/timeseries.py

This PR closes #836 by modifying `TimeSeries.q_transform` to raise any and all exceptions related to floating point numbers when calling `TimeSeries.whiten`. This means that any zeros in the ASD will result in an exception being raised (`FloatingPointError`), rather than allowing the Q-transform to filter over `nan`s.
This may have impacts for GravitySpy and LDVW.
cc: @areeda, @scottcoughlin2014

Raise error on any floating point issues during whitening in q_transform

---

gwpy/plot/axes.py
gwpy/plot/tests/test_axes.py

This PR improves the error message for `ax.hist([], logbins=True, range=None)` to explain exactly what the problem is.

Present better error for empty data given to Axes.hist if logbins=True, range=None

---

ci/install-debian.sh
ci/install-el.sh

This PR adds the necessary latex binary installs for EL and Debian Linux-based CI jobs. This should allow slightly more complete tests.

Install latex under docker for CI tests

---

requirements-dev.txt

This PR adds `lalsuite` to the `requirements-dev.txt` file, meaning it will get installed during testing for the 'basic' python builds on travis-CI. This should mean some more robust tests.
We should think about having staged jobs on travis whereby a small set of initial tests gets run without any of the `requirements-dev` extras to make sure that the core requirements are enough to run the core tests.

Include lalsuite in requirements-dev.txt for testing

---

ci/install-debian.sh
ci/install-el.sh
ci/install-macos.sh
debian/control
etc/spec.template
requirements-dev.txt
requirements.txt
setup.py

This PR improves the dependency spec in a number of ways, mainly so that dependencies are properly specified for all builds _except_ EL7, since `setuptools` is too old.

Improved dependency specifications in setup files

---

.circleci/config.yml
gwpy/detector/channel.py
setup.py

This PR is a first attempt to 'officially' support python3.7, by adding a CircleCI job on that version, and the relevant classifier in `setup.py`.

Added CI job for python3.7

---

docs/examples/index.rst
examples/segments/open-data.py

This PR fixes a bug in the docs that mean that the examples under `/examples/segments/` were not being rendered.

Fixed inclusion of segments in docs

---

gwpy/cli/tests/test_qtransform.py
gwpy/frequencyseries/frequencyseries.py
gwpy/frequencyseries/tests/test_frequencyseries.py
gwpy/signal/filter_design.py
gwpy/signal/tests/test_filter_design.py
gwpy/signal/tests/test_window.py
gwpy/timeseries/tests/test_timeseries.py
gwpy/timeseries/timeseries.py

This pull request addresses a common issue with filter transients in the current whitening method by replacing it with an alternative scheme which designs and applies an FIR (finite impulse response) filter using inverse spectrum truncation.
Other new features added include:
* A method `FrequencySeries.interpolate()` and functions `timeseries._fft_length_default`, `signal.filter_design.truncate_transfer`, and `signal.filter_design.truncate_impulse`, all used to design the FIR filter
* New keyword arguments for filter duration (in the time domain) and highpass corner frequency
* In `TimeSeries.whiten()`, a default value of `fftlength`which  causes it to be set to `max(2, int(2048 // self.sample_rate.decompose().value))`
* Automatic cropping of the beginning and end of the whitened …

New whitening scheme based on inverse spectrum truncation

---

gwpy/timeseries/core.py
gwpy/timeseries/statevector.py
gwpy/timeseries/tests/test_core.py
gwpy/timeseries/tests/test_statevector.py

This PR fixes #862 by adding a new `classmethod` for `TimeSeriesBaseDict`.

Added from_nds2_buffers method for TimeSeriesBaseDict

---

gwpy/timeseries/timeseries.py

This PR fixes a lot of `UserWarning`s in `TimeSeries.q_transform` introduced when the new whitening was merged (#868) - since the output of the new whitening is a truncated `TimeSeries`, the default `search` window in `gwpy.cli.qtransform` overflows the available data and causes warnings, so we just truncate the search window to match the output of the whitener.
cc: @areeda, @alurban

Fixed crop warnings in TimeSeries.q_transform

---

gwpy/detector/channel.py
gwpy/io/nds2.py
gwpy/tests/mocks.py
gwpy/timeseries/io/nds2.py

This PR fixes some problems seen when trying to fetch data from `'ONLINE'` channels, especially from NDS1 servers.

Fixed fetching 'online' data with the NDS2 client

---

gwpy/timeseries/io/gwf/lalframe.py
gwpy/timeseries/tests/test_timeseries.py

This PR fixes a problem reading data from GWF using `lalframe` when the filepath is `unicode`.
cc: @scottcoughlin2014

Fixed error reading GWF from unicode file path

---

gwpy/timeseries/core.py
gwpy/timeseries/io/core.py
gwpy/timeseries/io/nds2.py

This PR fixes some issues with handling gaps in source data in `TimeSeries.read` and `TimeSeries.fetch`.
Fixes #810.

Fixed issues with automagic gap handling in TimeSeries data access methods

---

gwpy/timeseries/tests/test_timeseries.py
gwpy/timeseries/timeseries.py

This PR updates the defaults for `TimeSeries.spectrogram2` to better match `TimeSeries.spectrogram` as follows:
- window, was `None`, now `hann`
- overlap, was `0`, now `None` (defaults to `recommended_overlap` output)

Updated defaults for spectrogram2

---

ci/install-debian.sh
ci/install-el.sh

This PR updates `setuptools` for all CI builds on LDG references OSs. This should fix release build failures such as [this one](https://travis-ci.com/gwpy/gwpy/jobs/140405017).

Update setuptools for LDG builds on CI

---

gwpy/plot/colors.py
gwpy/plot/tests/test_colors.py

This PR fixes an error seen when running `gwdetchar-omega` with gwpy-0.12.0, which manually passes `clim=None` to a plotting method, which caused `format_norm` to crash.
I have also added a dedicated test module for `gwpy.plot.colors`, include a regression test for this bug.
cc @alurban

Allow passing clim=None to gwpy.plot.colors.format_norm

---

appveyor.yml

This PR works around the failing unit tests on windows by excluding pytest-3.8.0 from the build, it seems that version introduced a change. See #894 for progress on actually fixing it.

Avoid pytest-3.8.0 on windows

---

examples/timeseries/whiten.py
gwpy/cli/tests/test_qtransform.py
gwpy/signal/filter_design.py
gwpy/signal/tests/test_filter_design.py
gwpy/timeseries/tests/test_timeseries.py
gwpy/timeseries/timeseries.py

@duncanmmacleod, this PR includes the following changes:
* Window the first and last half-filter-length of input data before convolving, and return a `TimeSeries` the same length as the input (this is mostly to stay more in line with the behavior of the old whitener)
* Update the documentation’s whitening example to reflect this
* Change default whitening filter length to 2 seconds, which better reproduces the published GW150914 Q-spectrogram
* Refactor FIR filter design into its own function, `signal.filter_design.fir_from_transfer()`, including a unit test
* Use `scipy.signal.fftconvolve()` to apply the whitening filter, anticipating #883
* Edit unit tests affected by changes to `TimeSeries.whiten()`
This fixes #890.

Address issues with whitening defaults

---

gwpy/io/kerberos.py
gwpy/io/tests/test_kerberos.py

This PR fixes bugs in `kerberos.kinit` on python3, just a simple type issue with `str` vs `bytes`. I took this opportunity to make some small, backwards-compatible internal improvements to that method.

Fixed bugs in gwpy.io.kerberos for python3

---

gwpy/cli/timeseries.py

I got tired of minute trends reporting Fs to 10 decimal digits.  I verified VIrgo sample rates are not slower than .001 Hz

gwpy/cli/timeseries.py: limit sample rate to 3 decimals in plot title

---

gwpy/cli/tests/test_qtransform.py
gwpy/timeseries/tests/test_timeseries.py
gwpy/timeseries/timeseries.py

@duncanmmacleod, this PR updates whitening defaults (and affected unit tests) under `TimeSeries.q_transform`. This was missed in #891, but will properly restore the low-frequency content in the GW150914 spectrogram when run with default values, and should be released with GWPy 0.12.1.

Update to whitening defaults in TimeSeries.q_transform

---

gwpy/timeseries/core.py
gwpy/timeseries/tests/test_core.py
gwpy/types/series.py
gwpy/types/tests/test_series.py

This PR moves the `TimeSeries.shift` method upstream to the `Series` object, exposing it to `FrequencySeries` and friends. Also, I fixed a bug in the implementation where `shift()` would have no effect if the `xindex` had already been created.

Moved TimeSeries.shift upstream to Series

---

gwpy/timeseries/io/gwf/lalframe.py

This PR fixes a bug in identifying detectors when writing GWF `FrHeader` structures using `lalframe`.
Fixes #889.

Fixed detector bits for writing with lalframe

---

README.md
debian/copyright
docs/index.rst
etc/Portfile.template
setup.py

This PR updates the license for GWpy to GPLv3+ and improves the inclusion of licensing information in distributions.

Updated licensing information to GPLv3+

---

gwpy/signal/filter_design.py
gwpy/timeseries/tests/test_timeseries.py
gwpy/timeseries/timeseries.py

@duncanmmacleod, this PR adjusts the normali(s)ation in `signal.filter_design.fir_from_transfer` so that the resulting filter's frequency response has the same overall amplitude as the original transfer function. **Crucially, this means FIR filter design will use the `numpy` normalization.** To compensate for this, the PR also fixes normalization in `TimeSeries.whiten()` so that the output timeseries has zero mean and unit variance:
First plot shows the original spectrum in blue and the frequency response of the filter in orange; second plot shows the original timeseries on top and the whitened timeseries (note the y-axis scale) on the bottom; third plot compares the original strain ASD to that of the whitened data.
This fixes #902.

Fix normalization for whitening and FIR filter design

---

appveyor.yml

This PR fixes the version pinning for `pytest` for Windows builds on Appveyor. See #894.

Avoid pytest>=3.8 on appveyor

---

gwpy/timeseries/tests/test_timeseries.py
gwpy/timeseries/timeseries.py

@duncanmmacleod, this PR introduces a `TimeSeries.convolve()` method which efficiently applies an FIR filter to a long timeseries using the [overlap-save](https://en.wikipedia.org/wiki/Overlap–save_method) algorithm. It also adds a unit test for `TimeSeries.convolve()` which prepares a timeseries and then checks that the input data are unchanged by convolving with a delta function.
@andrew-lundgren, this fixes #451.

Introducing a TimeSeries.convolve() method based on the overlap-save algorithm

---

gwpy/io/cache.py
gwpy/io/datafind.py
gwpy/io/gwf.py
gwpy/io/tests/test_gwf.py

This PR fixes a few failures when trying to read (mainly `open()`) local files using `file://localhost` style URLs, mainly by calling `urlparse(...).path`.
This is necessary because the updated `gwdatafind` package returns file URLs, rather than cache objects.

Allow reading caches and GWFs from file:// URLs

---

gwpy/timeseries/core.py
gwpy/types/series.py

It has been confusing that there are two keywords to handle gap filling: `pad` and `gap`, both of which are required to guarantee the output. This PR modifies the behaviour to not require the `gap` option, so that if `pad` is given as not `None`, the default is as if `gap='pad'` was passed.

Updated gap handling syntax

---

gwpy/plot/plot.py
gwpy/plot/tests/test_plot.py

This PR fixes an issue with `gwpy.plot.Plot.add_segments_bar` where the `epoch` of the parent axes would be unset when creating the segments bar axes.
cc: @alurban

Preserve epoch in add_segments_bar

---

gwpy/io/nds2.py
gwpy/io/tests/test_nds2.py

This PR silences the `no default host found for ifo 'V1'` style warnings when you try to dynamically `get` (`fetch`) data for a non-LIGO interferometer, as long as the `NDSSERVER` variable is set (meaning the user/admin has opted into selecting the default host for themselves).
Fixes #816.

Silence some NDS2 host warnings

---

gwpy/timeseries/core.py
gwpy/timeseries/io/nds2.py

This PR modifies the behaviour of the `verbose` keyword to `TimeSeries.fetch` and friends, such that the user can now specify the prefix string for the tqdm progress bar. This has the impact of silencing all other output, mainly to enable convenient embedding of the progress bar into other contexts. This is useful for the LIGO summary pages.

Allow specifying verbose prefix for NDS fetch

---

gwpy/table/filter.py

This PR updates the `gwpy.table.filters.parse_column_filter()` function to account for the new implicit `NEWLINE` token in latest bug-fix releases of python (cf python/cpython#7891).

Fixed parsing filter strings in bug-fix python releases

---

gwpy/segments/flag.py
gwpy/segments/tests/test_flag.py

This PR adds a new `.coalesce()` method to the `DataQualityDict`. This just calls `DataQualityFlag.coalesce()` for all values.

Added DataQualityDict.coalesce method

---

gwpy/segments/tests/test_flag.py
gwpy/tests/utils.py

This PR fixes a bug in the test suite utilities (`gwpy.tests`) that was hiding bad test results.

Fixed bug in assert_dict_equal in the test suite

---

gwpy/detector/io/clf.py
gwpy/detector/io/omega.py
gwpy/frequencyseries/tests/test_frequencyseries.py
gwpy/signal/fft/ui.py
gwpy/signal/tests/test_fft.py
gwpy/timeseries/tests/test_core.py
gwpy/timeseries/timeseries.py
gwpy/types/array.py

This PR fixes a number of `FutureWarning`s and `DeprecationWarning`s emitted when running the test suite, mainly from not correctly comparing `Quantity` objects to other things.

Fixed DeprecationWarnings in the test suite

---

gwpy/segments/flag.py

This PR modifies `DataQualityFlag.round()` to preserve the type of the numbers contained within each segment list. For python3, the `math.floor` and `math.ceil` return `Integral` types, rather than floats, meaning type was being lost.

Patched DataQualityFlag.round() to preserve type

---

gwpy/segments/flag.py
gwpy/segments/io/segwizard.py
gwpy/segments/segments.py

This PR updates the `gwpy.segments` subpackage to use `gwpy.io.mp` to provide multi-processed I/O as standard.

Patched gwpy.segments to use standard multi-processed I/O

---

gwpy/segments/io/segwizard.py
gwpy/segments/tests/test_segments.py
gwpy/timeseries/statevector.py
gwpy/timeseries/tests/test_statevector.py

This PR removes any dependencies on the `glue.segmentsUtils` module, mainly be adapting the necessary code directly into the calling gwpy modules, with credits.

Removed dependencies on glue.segmentsUtils library

---

gwpy/io/nds2.py

This PR fixes #949 by casting the output of `map` to `list` for python3.

Fixed bug in nds2 get_availability interface for python3

---

examples/timeseries/correlate.py
examples/timeseries/index.rst
gwpy/timeseries/tests/test_timeseries.py
gwpy/timeseries/timeseries.py

@duncanmmacleod, this pull request makes the following changes:
* Introduce a method, `TimeSeries.correlate()`, which convolves `self` with the phase reverse of a given signal, yielding the matched-filter SNR
* The new method whitens both the input and the matched-filter if requested, using an ASD of the input followed by two calls to `TimeSeries.whiten()`
* Add a unit test and documentation example for the new method (the latter requires `LIGO.ORG` credentials)
* Update `TimeSeries.whiten()` to normalize by expected standard deviation, rather than observed
* Update the unit test for `TimeSeries.whiten()`
Note, the SNR timeseries returned by `TimeSeries.correlate()` has the same length and timestamps as `self`. Both `self` and the matched-filter argument are detrended (to give the output …

Introducing a TimeSeries.correlate() method

---

gwpy/detector/units.py

This PR modifies the definition of the custom `'strain'` unit to be represent `dimensionless_unscaled`, this used to be defined like this, but was removed in cffd06c738f7482e52a8574e7d8bc7179b90fb40 for some reason; fixes #958.

Modified strain unit definition to be an alias for dimensionless

---

docs/env.rst
docs/index.rst
gwpy/plot/rc.py
gwpy/timeseries/io/losc.py
gwpy/utils/env.py
gwpy/utils/tests/test_env.py

This PR adds the `gwpy.utils.env` module, which currently provides just a single function `bool_env` - which parses an environment variable as a boolean switch. I updated the two blocks in the library that would use it.

Added new gwpy.utils.env module

---

requirements-test.txt
setup.py

This PR pins out pytest requirement to `< 4.0a0` - this new major version has been released, but we can't use it until pytest-dev/pytest#4401 has been resolved.

Pin to pytest<4.0.0 for now

---

gwpy/timeseries/timeseries.py

@duncanmmacleod, this PR patches up a memory leak I discovered while helping @siddharth101 track 50 Hz lines at Livingston. The issue is in `TimeSeries.demodulate()`, which originally contained a call to the `self.times` object, a massive memory hog for long timeseries. The fix I've implemented here is to instead range over sample indices, breaking them up into slices of length `stridesamp`.
The following changes are also applied:
* Change the reference time offset to `self.t0`, rather than GPS second 0
* Mix with a local oscillator inside the `for` loop, to limit its size in memory
* Replace use of `__metadata_finalize__()` with `__array_finalize__` in constructing the output in memory
* Minor refinement to the docstring
* Tweak the worked example in the docstring
This fixes #973.

Patch a memory leak in TimeSeries.demodulate()

---

ci/test.sh
gwpy/io/datafind.py

This PR removes the `urltype` keyword argument from the `find_frametype` and `find_best_frametype` functions in `gwpy.io.datafind`. Only `'file'` URLs are supported, so we may as well not expose the option to change it.

Removed urltype keyword from datafind find_*frametype functions

---

gwpy/cli/tests/test_qtransform.py
gwpy/timeseries/tests/test_timeseries.py
gwpy/timeseries/timeseries.py

This PR gives users the option to sample Q-scan spectrograms logarithmically in frequency, so that they can render Qscan plots more quickly (and using less memory) by invoking `Spectrogram.pcolormesh()` with a much smaller input array.
Other memory-saving changes in this PR include:
* Define an `ndarray` x-index proxy for interpolating Q-tiles, as this will use less memory than explicit calls to `series.times`
* Add a unit test for the `logf=True` use case
* Minor tweaks to unit tests affected by these changes
cc @duncanmmacleod, @areeda, @tjma12

Allow users to save time and memory computing Q-scans

---

.appveyor.yml

This is an attempt to fix the current issues related to the appveyor builds on python 3.7, by upgrading `python` itself inside the conda environment. This should only upgrade to latest patch release for a given minor version, so hopefully won't break everything.

Use fresh conda env in appveyor builds

---

gwpy/frequencyseries/frequencyseries.py
gwpy/frequencyseries/tests/test_frequencyseries.py

This PR fixes a bug in `FrequencySeries.interpolate()` so that the output of that method is interpolated properly only over the domain of the input. As a consequence, the `left` and `right` arguments have been removed, since they are redundant.
A more complete unit test for `FrequencySeries.interpolate()` is also added.
This fixes #932. (Note, the first attempt at doing this was in #940.)

Fix interpolation domain in FrequencySeries.interpolate()

---

docs/timeseries/io.rst

This PR adds a documentation on how to read GWOSC data from their HDF5 files using `format='hdf5.losc'`.

Added timeseries/io section on GWOSC HDF5

---

gwpy/plot/plot.py

The `%matplotlib inline` functionality in Jupyter notebooks was not working because the matplotlib inline backend doesn't have a `FigureManagerBase` class. This PR adds a check to use the correct methods if the inline backend is called. I tested this in a jupyterhub notebook and was able to render inline figures.
Fixes #964.
@duncanmmacleod @alurban

Added functionality for matplotlib inline backend

---

examples/frequencyseries/inject.py
examples/timeseries/correlate.py

@duncanmmacleod, this PR corrects an issue I noticed with [**the build version**](https://ldas-jobs.ligo.caltech.edu/~duncan.macleod/gwpy/testing/977/examples/timeseries/correlate.html) of the cross-correlation example for the GWPy docs.

Close docs plots to prevent them showing up more than once

---

gwpy/types/array.py
gwpy/types/tests/test_array.py

This PR fixes #919 by augmenting `Array.copy` to `copy.copy` all metadata attributes declared in `_metadata_slots`.

Copy all metadata in Array.copy

---

gwpy/testing/mocks.py
gwpy/timeseries/core.py
gwpy/timeseries/io/nds2.py
gwpy/timeseries/tests/test_core.py
gwpy/timeseries/tests/test_statevector.py

This PR adds two new keywords to `TimeSeriesBase.from_nds2_buffer`:
- `scaled=True`, whether to apply ADC scale and bias settings
- `copy=True`, whether to copy the data array to new memory
and exposes these keywords through all `TimeSeries*.{fetch,find,get}` methods.
This now means that we almost have a consistent interface for auto-applying ADC calibration, since NDS2 and frameCPP access will support it identically. Its just lalframe that doesn't, but I still plan to remove that interface in the near future anyway.

Added support for applying ADC scaling from NDS2 buffers

---

ci/install-macports.sh

This PR attempts to fix the current Travis CI failures [[example](https://travis-ci.com/gwpy/gwpy/jobs/167964402)] by manually installing `OpenBLAS` with macports before building GWpy on that platform. This should allow scipy-1.2.0 to then build against those libraries, rather than the system ones that seem to be missing symbols.

Manually install openblas for scipy on macports

---

gwpy/io/kerberos.py
gwpy/io/tests/test_kerberos.py
gwpy/timeseries/core.py
gwpy/timeseries/tests/test_timeseries.py

This PR fixes #838 by patching `gwpy.io.kerberos.kinit` to raise an exception whenever it is about to try and prompt for a username or password in a session that won't allow a response from the user.
I also took an opportunity to clean up the test suite for the containing `gwpy.io.kerberos` module.

Error on interactive prompts in non-interactive sessions for kinit()

---

examples/signal/index.rst
examples/signal/qscan.py
gwpy/signal/qtransform.py
gwpy/signal/tests/test_qtransform.py
gwpy/timeseries/tests/test_timeseries.py
gwpy/timeseries/timeseries.py

This PR substantially refactors `TimeSeries.q_transform()` to support eventgrams, a feature ported over from [**`gwdetchar-omega`**](https://github.com/gwdetchar/gwdetchar/blob/master/bin/gwdetchar-omega#L166-L254). To simplify review, here is a summary of changes made:
**New Features**
* Introduce a new object class, `~gwpy.signal.qtransform.QGram`, to support eventgrams
* Introduce a new function, `~gwpy.signal.qtransform.q_scan()`, which identifies the time-frequency plane at fixed Q with the most significant tile within a given (optional) search window. This method returns an instance of `QGram` along with the estimated false alarm rate from white Gaussian noise.
* Include a method, `QGram.table()`, which converts a populated `QGram` object to an `EventTable` so that it can be …

Refactor TimeSeries.q_transform() to support eventgrams

---

.travis.yml
ci/install-el.sh
ci/test.sh
gwpy/cli/tests/base.py
gwpy/cli/tests/test_spectrogram.py
requirements-test.txt
setup.py
setup_utils.py

This PR refactors the test suite for `gwpy.cli` to be compatible with `pytest-4.0.0`, mainly by removing direct calling of fixtures. The suite itself is now a little harder to read, but it runs.

Refactored tests of gwpy.cli to work with pytest-4.0

---

docs/table/io.rst
docs/timeseries/remote-access.rst

Hello :-)
The DOI Foundation [started recommending a new resolver](https://www.doi.org/doi_handbook/3_Resolution.html#3.8). While their URL change may be a bit ironic, it's now [encrypted](https://www.ssllabs.com/ssltest/analyze.html?d=doi.org) and the old `dx` subdomain is being redirected, there is no urgency here.
However, for consistency, this PRs suggests to update all static DOI links accordingly, plus the code that generates new DOI links.
Cheers!

Hyperlink DOIs to preferred resolver

---

gwpy/timeseries/core.py
gwpy/timeseries/io/gwf/framecpp.py

This PR modifies `gwpy.timeseries` to only apply ADC scaling if its mathematically interesting (`scale != 1. or bias != 0`); this helps to prevent unnecessary type-casting (e.g. for `uint` data).

Don't apply null ADC scaling

---

gwpy/timeseries/core.py
gwpy/timeseries/statevector.py
gwpy/timeseries/tests/test_core.py

This PR fixes #864 by implementing a `span` property for the `TimeSeriesDict`, essentially just the logical OR of all `span`s for contained `TimeSeries`.

Implemented TimeSeriesDict.span

---

gwpy/io/tests/test_nds2.py

This PR fixes a minor testing failure when NDSSERVER is inherited from the environment (LDG).

Fixed error testing gwpy.io.nds2 when NDSSERVER is set on the host

---

requirements-test.txt
setup.py

This PR fixes the minimum `pytest` version we require; parsing `capsys.readouterr()` as a namedtuple is only available in `pytest>=3.3.0`.

Corrected pytest version requirement

---

docs/examples/table/H1-LDAS_STRAIN-968654552-10.xml.gz
docs/table/H1-LDAS_STRAIN-968654552-10.xml.gz
examples/table/H1-LDAS_STRAIN-968654552-10.xml.gz

This PR fixes the broken symlinks for XML files, this was missed when I moved `gwpy.tests -> gwpy.testing` (#993).

Fixed symlinks of XML files

---

gwpy/time/__main__.py
gwpy/time/_tconvert.py
gwpy/time/tests/test_main.py
gwpy/time/tests/test_time.py

This PR adds a command-line interface to `gwpy.time` to replicate `tconvert` functionality, used as follows:
```shell
$ python -m gwpy.time 1161887657
2016-10-30 18:34:00.000000 UTC
```
This also improves the functionality of `gwpy.time._str_to_datetime` by optionally using [`maya`](https://pypi.org/project/maya/) to parse datetime strings, its a little better than `dateutil`.

Added tconvert-like command-line interface for gwpy.time

---

gwpy/table/tests/test_table.py

This PR works around a supposed bug in `python-ldas-tools-framecpp-2.6.7` by just skipping the test if the bug attacks, see [ldastools/LDAS_Tools#57](https://git.ligo.org/ldastools/LDAS_Tools/issues/57).

Skip failing test from bug in framecpp

---

docs/conf.py
requirements-doc.txt

This PR fixes how the extra CSS and JS files are linked into the output documentation HTML pages for the relevant version of sphinx that auto-creates the docs.

Fixed linking of CSS and JS in conf.py

---

gwpy/plot/tex.py

This PR patches `gwpy.plot.tex.has_tex` to catch `KeyError`s, so that no `PATH` variable doesn't crash the plotter, but just disables TeX.

Protect against KeyError in has_tex()

---

MANIFEST.in
docs/timeseries/io.rst

This PR fixes the last lingering references to `gwpy.tests` that are currently causing conda builds to fail.

Fixed lingering references to gwpy.tests

---

.travis.yml

This PR fixes the problem of multiple competing deployments from travis for tags by adding the `skip_existing: true` key to the `deploy` configuration.

Fixed error with multiple deployments from travis

---

gwpy/signal/fft/scipy.py
gwpy/signal/tests/test_fft.py
gwpy/timeseries/tests/test_timeseries.py

This PR adds support for calling `scipy.signal.welch` with `average='median'`, which was introduced in scipy-1.2.0.

Added support for median average from scipy

---

gwpy/segments/io/segwizard.py
gwpy/segments/tests/test_segments.py

This PR fixes a bug in the implementation and handling of the `strict` keyword argument to 'segwizard' I/O methods for the `SegmentList`.

Fixed bugs in strict reading of segments from segwizard format

---

gwpy/timeseries/io/losc.py
requirements-test.txt

This PR fixes a simple `DeprecationWarning` in `gwpy.timeseries.io.losc` when reading HDF5 data.

Fixed HDF5 DeprecationWarning

---

examples/timeseries/correlate.py

This PR makes a few 'improvements' to the `correlate` example, mainly so that my laptop doesn't explode when I run it:
- use `outseg` to reduce memory usage in interpolation
- use wider `qrange`, rather than specific Q (which we would have to document)
- explicitly use `imshow`

Minor improvements to correlate.py

---

gwpy/plot/axes.py
gwpy/plot/tests/test_axes.py

`matplotlib`'s `Axes.pcolormesh` method sets `ax.grid(False)` for some reason:
https://github.com/matplotlib/matplotlib/blob/v3.0.2/lib/matplotlib/axes/_axes.py#L6007
so this PR adds a decorator to `gwpy.plot.axes` that can be used to restore the grid settings after an `Axes` call to what they were before, and applies it to the `pcolormesh` override method.

Restore grid after pcolormesh

---

gwpy/plot/gps.py

This PR fixes buggy formatting of small GPS intervals by formatting using truncation, rather than rounding or quantisation.

Fixed tick label precision again

---

debian/control
docs/references.rst
docs/segments/dqsegdb.rst
docs/segments/index.rst
etc/Portfile.template
etc/spec.template
gwpy/io/cache.py
gwpy/segments/flag.py
gwpy/segments/tests/test_flag.py
requirements-dev.txt
requirements.txt
setup.py

This PR modifies the `gwpy.segments` sub-package to use the [`dqsegdb2`](https://dqsegdb2.readthedocs.io) library for segment queries, instead of `dqsegdb`.
`dqsegdb2` is added as a first-class dependency, so segment queries should now be considered a standard part of GWpy's capability.

Use dqsegdb2 for segment queries

---

gwpy/signal/qtransform.py
gwpy/timeseries/timeseries.py

This PR refactors the defaults for the Q-transform as module level variables of `gwpy.signal.qtransform`:
https://github.com/duncanmmacleod/gwpy/blob/334c3ccf01b5aa05a1ab860e74371e9a3b5b07aa/gwpy/signal/qtransform.py#L44-L47
and updates `gwpy.timeseries.timeseries` to match. This doesn't change any of the defaults.

Refactored default parameters for Q-transform as module-level variables

---

examples/frequencyseries/percentiles.py
examples/frequencyseries/rayleigh.py
examples/frequencyseries/variance.py
examples/miscellaneous/open-data-spectrogram.py
examples/spectrogram/spectrogram2.py
examples/timeseries/filter.py

This PR removes the use of the `\rtHz` TeX macro from the examples; we don't use TeX for the documentation any more, so we can't use the macros.
This reminds me, we should document that you _can_ use TeX for formatting, and it looks good.

Removed latex macros from examples

---

ci/install-macports.sh

This PR removes the manual install of `scipy` with macports, hopefully this has been fixed upstream.

Removed macports scipy install hack

---

gwpy/cli/qtransform.py
gwpy/cli/tests/test_qtransform.py

I had the sign  of protract wrong. Plus align reading pad with calculation padding

Q-transform fix min search length

---

gwpy/detector/io/clf.py
gwpy/io/cache.py
gwpy/io/ligolw.py
gwpy/io/mp.py
gwpy/io/registry.py
gwpy/io/tests/test_cache.py
gwpy/io/tests/test_utils.py
gwpy/io/utils.py
gwpy/timeseries/io/gwf/framecpp.py
gwpy/timeseries/io/gwf/lalframe.py

This PR renames/relocates the following methods and variables:
- `gwpy.io.cache.FILE_LIKE` -> `gwpy.io.utils.FILE_LIKE`
- `gwpy.io.cache.file_name` -> `gwpy.io.utils.file_path`
- `gwpy.io.cache.file_list` -> `gwpy.io.utils.file_list`
and updates their usage and tests throughout the package. This is backwards compatible (the new names are imported to their old locations, with appropriate `DeprecationWarnings`).

Renamed and moved a couple of I/O utility functions

---

gwpy/segments/io/segwizard.py
gwpy/segments/tests/test_segments.py

This PR fixes a bug in `gwpy.segments.io.segwizard` when reading segments from a two-column ASCII file (python3 only).

Fixed bug reading two-col segments

---

gwpy/table/io/__init__.py
gwpy/table/io/cwb.py
gwpy/table/io/omega.py
gwpy/table/io/pycbc.py
gwpy/table/io/root.py
gwpy/table/io/utils.py
gwpy/table/table.py
gwpy/table/tests/test_table.py

This PR attempts to improve the `EventTable` I/O system, mainly to make the keyword arguments more consistent across formats.
All readers (including those inherited from astropy) now accept the `columns` and `selection` keywords, mainly thanks to the new `gwpy.table.io.utils.decorate_registered_reader` function.
This is technically backwards incompatible since it registers the 'hdf5' reader for the `EventTable`, meaning PyCBC HDF5 files cannot be distinguished from normal HDF5 files, which in turns means the `format` keyword now needs to be explicitly given when reading either PyCBC Live files.

Improved EventTable I/O with decorators

---

gwpy/testing/utils.py

This PR fixes the `skip_minimum_version` testing decorator to actually compare versions properly using `distutils.version.LooseVersion`.

Fixed a bug in the skip_minimum_version testing decorator

---

gwpy/cli/spectrogram.py
gwpy/cli/tests/base.py

This PR fixes some warnings emitted during testing `gwpy.cli`; one can't directly compare quantities, or get their 'truth' value, need to use fancier methods or compare against `None`.

Fixed some warnings in testing

---

ci/install-el.sh
ci/install-macports.sh
debian/control
docs/install/index.rst
docs/segments/io.rst
etc/Portfile.template
etc/spec.template
gwpy/io/datafind.py
gwpy/io/tests/test_datafind.py
gwpy/timeseries/core.py
requirements-dev.txt
requirements.txt
setup.py

This PR upgrades `gwdatafind` to a first-class dependency. This was the case in practice already since `dqsegdb2` is a dependency and depends in turn on `gwdatafind`, but this allows us to clean up some imports.
I also took this chance to clean up the dependency lists as they exist across various files, now all alphabetically ordered, and rechecked.

Upgrade gwdatafind to first-class dependency

---

gwpy/signal/tests/test_spectral_pycbc.py

This PR should hopefully fix the [current CI failures](https://travis-ci.com/gwpy/gwpy/builds/101769964) by improving the import protection in the test suite for `gwpy.signal`.

Improved pycbc import protection in tests

---

examples/timeseries/qscan.py
gwpy/signal/qtransform.py
gwpy/signal/tests/test_qtransform.py
gwpy/timeseries/tests/test_timeseries.py
gwpy/timeseries/timeseries.py

This pull request ensures that interpolated Q-transform spectrograms are populated with single-precision floats, to save memory. It also slightly expands unit tests for the Q-transform, and fixes one of the documentation examples to use `outseg` rather than `crop`.
This fixes #1050.
cc @duncanmmacleod, @tjma12

Make interpolated Q-transform spectrograms single precision

---

gwpy/timeseries/io/gwf/framecpp.py
gwpy/timeseries/tests/test_timeseries.py

This PR adds a `test_read_write_gwf_errors` test method that exposed a failure, and corrects said failure in error reporting.

Added tests for frameCPP errors and fixed a bug

---

gwpy/timeseries/tests/test_timeseries.py
gwpy/timeseries/timeseries.py

This PR adds gating as a `TimeSeries` class method. The method whitens the time series, marks all points above a threshold, clusters them within a time window, and applies inverse Planck windows to zero out the data. The **unwhitened**, gated time series is returned.
An example can be found here (behind LIGO.org auth): https://ldas-jobs.ligo.caltech.edu/~thomas.massinger/notebook/demonstrate-gwpy-gating.html
Whitening arguments can be passed to the underlying whitening used to locate gating points.

Added basic gating as TimeSeries method

---

.appveyor.yml
.circleci/config.yml
.travis.yml
README.md
ci/codecov.sh
ci/install-conda.sh
ci/install-debian.sh
ci/install-pip.sh
ci/test.sh

This PR does one big thing, and a few small things.
This switches the coverage reporting from coveralls to codecov, mainly because it natively supports multiple coverage providers. The reporting is also very nice.
- use test reports properly in appveyor
- removed python3.5 build for appveyor - it just adds time and not useful information
- fixed some bugs in the CI scripts, mainly conda related
- fixed caching of conda builds in circleci

Switch coverage to codecov, and update CI

---

.circleci/config.yml
.travis.yml

This PR moves the automatic PyPI deployment to CircleCI, which is better suited to it. This is impossible to actually test in CI as part of a pull request, unfortunately.

Moved PyPI deploy to circleci

---

.appveyor.yml
ci/test.sh
gwpy/plot/tests/test_gps.py
gwpy/utils/tests/test_env.py
requirements-test.txt

This PR adds `pytest-xdist` to the CI configuration to try and run the tests in parallel, ideally speeding things up.

Use pytest-xdist to run tests in parallel

---

.codecov.yml
gwpy/signal/tests/test_spectral_median_mean.py
requirements-dev.txt

This PR fixes a failing test based on using `pytest.deprecated_call` with `pytest < 3.9.1`.

Fixed usage of deprecated_call to fix failing test

---

gwpy/timeseries/core.py
gwpy/timeseries/io/gwf/framecpp.py
gwpy/timeseries/io/nds2.py
gwpy/timeseries/tests/test_core.py
gwpy/timeseries/tests/test_timeseries.py

This PR swaps the defaults for applying ADC bias and slope calibration to a dynamic choice based on the channel name. For H1 and L1 channels, bias and slope are ignored, else they are applied.

Swap the defaults for applying ADC bias and slope calibration

---

ci/install-conda.sh

This PR patches the travis conda installer script to manually request `numpy` when creating the environment, this forces `numpy` to come from `conda-forge`, rather than `defaults`, meaning when we install `lal` and friends, we end up not having to switch.

Manually request numpy when creating environment

---

gwpy/timeseries/io/gwf/lalframe.py
gwpy/timeseries/tests/test_timeseries.py

This PR fixes a bug in GWF reading whereby the `scaled` keyword argument is always passed, but the `lalframe` API doesn't expect it. The mod is to handle it and just present a warning when the user has actually used it, since the `lalframe` API doesn't support it.

Handle scaled keyword argument when reading GWF with lalframe

---

gwpy/timeseries/tests/test_timeseries.py
gwpy/timeseries/timeseries.py

This PR patches `TimeSeries.resample` to detect when the requested rate matches the input rate, and just returns `self`.

Handle noop in TimeSeries.resample with warning

---

gwpy/io/datafind.py
gwpy/io/tests/test_datafind.py

Sometimes `gwdatafind` fails with an `HTTPError` (`BadStatusLine`?), so the simple thing to do is just try to reconnect and try again.

Try and reconnect to datafind if connection fails with HTTPError

---

gwpy/io/gwf.py
gwpy/io/tests/test_gwf.py

This PR adds `gwpy.io.gwf.data_segments()` (copied from gwpy/pyomicron#88) to determine available data segments for a given channel in a list of GWF paths.
This is useful when trying to read data from a list of paths, some of which don't actually contain the channel you want.

Added gwpy.io.gwf.data_segments function

---

.appveyor.yml
gwpy/plot/axes.py
gwpy/plot/tests/test_axes.py

This PR fixes two issues with using `gwpy.plot.Axes` for 'normal' matplotlib usage, include via `pylab`
- fixed handling of positional arguments in `Axes.plot`
- fixed handling of positional arguments in `Axes.imshow`

Fixed some bugs in gwpy.plot.Axes overrides of upstream methods

---

gwpy/time/_tconvert.py
gwpy/time/tests/test_time.py

This PR fixes a corner-case bug in `to_gps` when converting high-precision floats to `LIGOTimeGPS`. The trick is to not use `float` as much as possible, but rather use `str`.

Fixed a corner case issue with to_gps

---

gwpy/frequencyseries/frequencyseries.py
gwpy/timeseries/core.py
gwpy/timeseries/io/gwf/__init__.py
gwpy/timeseries/io/gwf/lalframe.py
gwpy/types/array2d.py
gwpy/types/index.py
gwpy/types/series.py
gwpy/types/tests/test_series.py

This PR simplifies the way that index properties are handled between the `Series` and `Array2D` classes, mainly to remove the large amount of code duplication between the two.
Additionally I put in some small changes to preserve `dtype` wherever possible, mainly in `numpy` calls, and also to remove some unnecessary casts of `LIGOTimeGPS` to `float`, which can cause precision loss.

Improved index handling in Series and Array2D

---

gwpy/utils/tests/test_shell.py

This PR attempts to fix failures under windows on azure CI [[ref](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=21287)] by stripping whitespace when comparing the output of `gwpy.utils.shell.call`.

Strip whitespace when testing shell.call

---

gwpy/table/io/pycbc.py
gwpy/table/tests/test_table.py

This PR fixes #1081 by using `set` to parse the necessary read column names.

Use set to format readcols for pycbc

---

gwpy/plot/plot.py

This PR fixes a `DeprecationWarning` in `gwpy.plot.plot` by importing `{Keys/Values}View` from `collections.abc` if we can.

Import KeysView and ValuesView from collections.abc

---

debian/control
etc/spec.template
gwpy/io/cache.py
gwpy/io/tests/test_cache.py
requirements.txt
setup.py

This PR improves the `read_cache` and `write_cache` functions from `gwpy.io.cache` to support the following:
- read a plaintxt file of paths (in LIGO-T050017 format)
- a new `format` keyword argument to `write_cache` to specify the format
To support this, a new `filename_metadata` function was added. This is essentially the same as that in `gwdatafind.utils`, but handles floats in the filename.

Improved read_cache and write_cache functions

---

gwpy/cli/spectrogram.py

The current way to set axis limits for spectrogram and q-transform is to crop the transformed data.
specgram = self.result.crop(
args.xmin, min(args.xmax, self.result.xspan[1]),
).crop_frequencies(args.ymin, args.ymax)```
The change to log spacing for y-axis causes the following error:
```Traceback (most recent call last):
File "/Users/areeda/miniconda2/envs/ligo-py27/bin/gwpy-plot", line 105, in <module>
prod.run()
File "/Users/areeda/miniconda2/envs/ligo-py27/lib/python2.7/site-packages/gwpy/cli/cliproduct.py", line 712, in run
self.set_plot_properties()
File "/Users/areeda/miniconda2/envs/ligo-py27/lib/python2.7/site-packages/gwpy/cli/cliproduct.py", line 547, in set_plot_properties
self.set_axes_properties()
File "/Users/areeda/miniconda2/envs/ligo-py27/lib/python2.7/site-packages/gwpy …

Change spectrogram axis set from crop for y-axis to ax.set_ylim() try#2

---

gwpy/io/kerberos.py
gwpy/io/tests/test_kerberos.py

This PR fixes an issue in `gwpy.io.kerberos` whereby keytab files with multiple copies of the same kvno/principal would be returned, causing `kinit()` to fall over. `parse_keytab()` has been modified to return an ordered, unique list of credentials, and also to return a `list` of `tuple`, rather than a `list` of `list`.
cc @scottcoughlin2014

gwpy.io: return unique creds from parse_keytab

---

requirements-test.txt

This PR fixes [this sort of issue](https://circleci.com/gh/gwpy/gwpy/5443) with testing on older python versions where astropy still pins pytest.

Pin requirements to compatible pytest-xdist

---

ci/install-debian.sh
ci/install-el.sh
docs/references.rst
docs/segments/io.rst
docs/table/io.rst
examples/table/rate.py
examples/table/rate_binned.py
examples/table/tiles.py
gwpy/frequencyseries/tests/test_frequencyseries.py
gwpy/io/ligolw.py
gwpy/io/tests/test_ligolw.py
gwpy/segments/flag.py
gwpy/segments/io/ligolw.py
gwpy/segments/tests/test_flag.py
gwpy/table/io/__init__.py
gwpy/table/io/ligolw.py
gwpy/table/table.py
gwpy/table/tests/test_table.py
gwpy/types/io/ligolw.py
requirements-dev.txt

This PR implements a backwards-compatible update to use the new `python-ligo-lw` library for `LIGO_LW` I/O, but with fallbacks to `glue.ligolw` when reading old files.
When reading there is now a try/except that should try and read with the new library, and if that fails, try and use the old library.
When writing:
- ...tables, the columns/datatypes in the table define the format version, so both libraries are tried (new first)
- ...segments, there is a new `ilwdchar_compat` keyword that currently defaults to `None`, which presents a warning that it will use `True` (old format), but will be switched to `False` for the 1.0.0 release (at which time the warning will be removed).
The upshot of this is that GWpy should now be able to seamlessly read LIGO_LW files written in either new or old …

Port LIGO_LW I/O to python-ligo-lw

---

gwpy/plot/tests/test_utils.py
gwpy/plot/utils.py

This PR updates the `color_cycle` function in `gwpy.plot.utils` to work with `matplotlib >= 2.2`. This also adds unit tests for that module.

Fixed bugs in gwpy.plot.utils for new matplotlib

---

gwpy/io/kerberos.py
gwpy/io/tests/test_kerberos.py

This PR fixes an a problem using `gwpy.io.kerberos.kinit` in jupyter notebooks (ipython kernels in general) when the `sys.stdout.isatty()` returns `False`, to the function would refuse to attempt an interactive prompt.
The solution here is to manually look up existence of the `__IPYTHON__` special variable, and use that to override the result of `isatty()`.

Fixed interactive usage of kinit() in ipython kernels (jupyter)

---

gwpy/plot/axes.py
gwpy/plot/gps.py
gwpy/plot/rc.py
gwpy/plot/tests/test_axes.py
gwpy/plot/tests/test_plot.py

This PR fixes some compatibility issues with matplotlib-3.1+:
* Since LaTeX preamble definitions will now have expected type `str` (not `list`), try to concatenate TeX macros to a list first, then fall back to a string if that fails (see [**TeX API changes**](https://matplotlib.org/devdocs/api/api_changes.html#latex-code-in-matplotlibrc-file))
* Since the public utility `matplotlib.scale.get_scale_docs` is deprecated, switch to using `inspect.getdocs` directly while preserving the order of scales (see [**attribute deprecations**](https://matplotlib.org/devdocs/api/api_changes.html#class-method-attribute-deprecations))
* `matplotlib.cbook.iterable` is deprecated, use `numpy.iterable`
* `cbar.get_clim` is deprecated, use `cbar.mappable.get_clim`
This fixes #1099, and supersedes #1100.
cc …

Compatibility fixes for matplotlib-3.1+

---

docs/plot/index.rst
docs/plot/legend.rst
docs/timeseries/datafind.rst
gwpy/plot/axes.py
gwpy/plot/legend.py
gwpy/plot/tests/test_axes.py

This PR changes the way legends are customised by default, to make things easier to modify for the user.
The old way was to use some extra keyword arguments, namely `linewidth`, to specify a new default linewidth in the legend. However, those keywords aren't recognised by default matplotlib figures, so calling `ax.legend(linewidth=4)` isn't cross-compatible between gwpy and non-gwpy plots. There's also no way to disable the custom linewidth and use the linewidth of the original handle.
The new way is to define a custom legend handler, which operates on `Line2D` objects, and sets the default linewidth. The interface is now that gwpy's `Axes.legend` method inserts the new handler into the existing `handler_map` keyword of matplotlib's `Axes.legend` method, which is entirely cross-compatible …

Updated custom legend formatting

---

gwpy/plot/tex.py
gwpy/segments/flag.py

This PR fixes a bug discovered in the production LIGO summary pages. The issue comes when attempting to use python > 3 to read an HDF5 file that was written with python < 3, largely because of UTF encoding compatibility issues.
For the same reason, this PR also adds `#` to the list of `LATEX_CONTROL_CHARACTERS`.

Miscellaneous python2/3 cross-compatibility changes

---

gwpy/timeseries/statevector.py
gwpy/types/array.py

This PR implements a top-level `Array.__array_ufunc__` method that returns scalars as `Quantity` objects from ufuncs. This will be required to support astropy-3.2, but should be backwards compatible.

Implemented __array_ufunc__ for gwpy.types.Array

---

gwpy/segments/tests/test_flag.py
gwpy/timeseries/tests/test_timeseries.py

This PR cleans up a bunch of warnings emitted during the tests, mainly from un-caught `DeprecationWarnings` related to segdb queries and lal/pycbc PSD methods.

Cleaned up test warnings

---

ci/install-debian.sh
setup_utils.py

This PR adds a call to `lintian` to validate the debian packages, after building them.

Run lintian after building debian packages

---

docs/table/gwosc.rst
gwpy/table/gravityspy.py
gwpy/table/io/losc.py
gwpy/table/table.py
gwpy/table/tests/test_table.py

This PR improves the parsing of open-data catalog event tables from GWOSC, mainly by detecting and replacing the `'NA'` that GWOSC uses to mark missing data. The logic here is a bit more complicated, because we have to determine the underlying data type of the column without the missing values, in order to replace the `'NA'` with the appropriate null value (`0` for `int`, `nan` for float).

Improved reading tables from GWOSC

---

gwpy/plot/gps.py
gwpy/plot/tests/test_gps.py

This PR fixes/attempts to fix errors in getting the correct default GPS epoch for plots when using matplotlib-3.1.0.

Fixed GPS epoch handling in mpl-3.1.0

---

gwpy/io/nds2.py

This PR fixes #1103 by fixing the casing of the default epoch name (`'All' -> 'ALL'`).

Fixed case error in setting nds connection epoch

---

.appveyor.yml
gwpy/frequencyseries/frequencyseries.py
gwpy/frequencyseries/hist.py
gwpy/io/mp.py
gwpy/io/tests/test_mp.py
gwpy/segments/flag.py
gwpy/segments/segments.py
gwpy/table/table.py
gwpy/timeseries/core.py
gwpy/timeseries/statevector.py
gwpy/types/series.py

This PR modifies `gwpy.io.mp.read_multi` (the function that underpins `EventTable.read`, `TimeSeries.read`, etc) to raise an `IndexError` early if the input `source` argument is parsed as an empty list.
Currently the behaviour in this condition is unpredictable, and dependent on the other keyword arguments, which doesn't make a great UX.
I also added an independent test suite for that function.

Raise IndexError early when reading an empty list of files

---

CODE_OF_CONDUCT.rst
CONTRIBUTING.md
README.md

This PR updates the readme and contributing guide to reflect the return to a stable mainline development model where everything lands on `master`. I have also added a code of conduct file that just links to the Astropy CoC.

Update readme, contributing guide, and code of conduct

---

.circleci/config.yml
gwpy/segments/segments.py
gwpy/segments/tests/test_segments.py

This PR introduces a new method, `SegmentList.to_table`, to cast `SegmentList` objects as type `~gwpy.table.Table`. This is provided mainly to have a way to write `SegmentList` objects to standard CSV tables, which has proven useful in delivering data products to LIGO management; see [**this tool**](https://git.ligo.org/detchar/ligo-summary-pages/blob/master/scripts/gw_epoch_time_accounting) for the LIGO summary pages (requires `LIGO.ORG` credentials).

Introduce a SegmentList.to_table method

---

.appveyor.yml
.circleci/config.yml
ci/codecov.sh
ci/test.sh

This PR modifies the CI configurations to run `pytest` from a separate directory, to guarantee that we are testing the installed version of the code.

Run all tests from a separate directory

---

gwpy/spectrogram/spectrogram.py
gwpy/spectrogram/tests/test_spectrogram.py

This PR fixes a minor bug in which `Spectrogram.percentile` returns a `FrequencySeries` with no units. The fix is to ensure that the `FrequencySeries` has the same units as the parent `Spectrogram`.

Ensure percentile spectra have the same units as the parent Spectrogram

---

gwpy/frequencyseries/hist.py

This PR fixes a `FutureWarning` emitted by `numpy.stack` when called from `SpectralVariance.from_spectrogram`.

Fixed FutureWarning from numpy.stack

---

examples/miscellaneous/index.rst
examples/miscellaneous/range-spectrogram.py
examples/miscellaneous/range-timeseries.py
gwpy/astro/__init__.py
gwpy/astro/range.py
gwpy/astro/tests/test_range.py

This PR introduces two new functions in `gwpy.astro`:
* `range_timeseries`
* `range_spectrogram`
Unit tests and documentation examples for these new functions are also included.
The `range_spectrogram` utility works by first calculating a standard PSD spectrogram (or accepting one as an input), then stepping through its time bins, passing each PSD measurement to either the `astro.burst_range_spectrum` or `astro.inspiral_range_psd` function depending on the use case. The `range_timeseries` utility follows a similar procedure, but returns a `TimeSeries` record of the output of `astro.burst_range` or `astro.inspiral_range`.
**Notes:**
* This PR is mainly to address requests from Advanced LIGO commissioners, who want to analyze spectral contributions to the binary neutron star inspiral range …

Introduce a range_spectrogram method as a figure-of-merit

---

ci/test.sh
examples/frequencyseries/coherence.py
examples/frequencyseries/variance.py
examples/miscellaneous/range-spectrogram.py
examples/signal/gw150914.py
examples/spectrogram/coherence.py
examples/spectrogram/spectrogram2.py
examples/test_examples.py
examples/timeseries/blrms.py
examples/timeseries/correlate.py
examples/timeseries/filter.py
setup.cfg

This PR un-excludes `examples/` from the `flake8` configuration in `setup.cfg`.

Don't exclude examples from flake8 in CI

---

gwpy/detector/channel.py
gwpy/detector/tests/test_channel.py
gwpy/io/_framecpp.py
gwpy/io/gwf.py
gwpy/io/nds2.py
gwpy/io/tests/test_gwf.py
gwpy/io/tests/test_nds2.py
gwpy/testing/fixtures.py
gwpy/timeseries/io/gwf/framecpp.py
gwpy/utils/enum.py
gwpy/utils/tests/test_enum.py

This PR introduces a re-factoring of a bunch of code, mainly moving functions from `gwpy.timeseries.io.gwf.framecpp` into `gwpy.io.framecpp` and the new `gwpy.io._framecpp` module.
In order to reduce duplication, there is a new `gwpy.utils.enum` module that provides a common parent class for enums that reference numpy types, and is now used by `gwpy.io.nds2.Nds2DataType` and `gwpy.io._framecpp.FrVectType`.
This change should present exactly zero functional changes to the code for 99.9% of cases, technically the API to `TimeSeries{Dict}.write` has changed when `format='gwf'` is given, but I suspect that nobody has ever attempted to use the (undocumented) keywords that have changed.

Refactor of GWF I/O utility code

---

gwpy/timeseries/io/gwf/lalframe.py
gwpy/timeseries/tests/test_io_gwf_lalframe.py

This PR fixes #1094 by improving the error handling in the lalframe GWF API's `write()` function.

Fixed bug in writing GWF with lalframe

---

gwpy/time/_tconvert.py
gwpy/time/tests/test_time.py

Python's `datetime.datetime` can't handle an exact leap second, so `gwpy.time.tconvert` will fail when trying to convert one:
```pytb
$ python -m gwpy.time 1167264017
File "/Users/duncan/opt/miniconda3/envs/py37/lib/python3.7/site-packages/astropy/time/formats.py", line 680, in to_value
.format((iy, im, id, ihr, imin, isec, ifracsec)))
ValueError: Time (array(2016, dtype=int32), array(12, dtype=int32), array(31, dtype=int32), array(23, dtype=int32), array(59, dtype=int32), array(60, dtype=int32), array(0, dtype=int32)) is within a leap second but datetime does not support leap seconds
```
This PR just improves the error reporting of that:
```pytb
$ python -m gwpy.time 1167264017
File …
```

Improved error reporting when tconverting leap seconds

---

README.md

- removed depsy badge (that project isn't being updated)
- updated travis badge to point to .com instead of .org
- removed link from python versions badge
- correct minor grammatical oddity in license section

A few minor updates to the README

---

.circleci/config.yml
gwpy/timeseries/tests/test_timeseries.py
requirements-test.txt
setup.py

~This PR updates a test of the `TimeSeries` object to handle more exception types from `h5py`. Apparently the exception types cannot be relied upon because the upstream HDF5 library doesn't consider error codes part of the public API, see http://docs.h5py.org/en/2.9.0/faq.html#exceptions for information.~
UPDATE: This PR fixes a few unrelated build failures:
- updates a test of the `TimeSeries` object to handle more exception types from `h5py`; apparently the exception types cannot be relied upon because the upstream HDF5 library doesn't consider error codes part of the public API, see http://docs.h5py.org/en/2.9.0/faq.html#exceptions for information
- pin to pytest<5.0.0 to avoid annoying internal errors
- updated images for ligo reference OS builds

Myriad build/CI fixes

---

.circleci/config.yml
gwpy/segments/flag.py
gwpy/timeseries/tests/test_timeseries.py
requirements-test.txt
setup.py

In `segments/flag.py`,  there are cases of `LIGOTimeGPS` objects attempting to access the `LIGOTimeGPS.seconds` attribute, which doesn't exist, the correct attribute should be `.gpsSeconds`. These are invoked in cases where the end time of a flag is set to `+inf`, such as when populating a `DataQualityDict` from a veto definer. I was able to successfully populate a `DataQualityDict` with `+inf` end times locally after this fix.

corrected LIGOTimeGPS attribute call

---

gwpy/timeseries/tests/test_timeseries.py
gwpy/timeseries/timeseries.py

This adds a method similar to the TimeSeries demodulate method, however, this takes in the phase evolution within which to demodulate/heterodyne the array. By default this returns a double-sided complex output, rather than the single-sided value.
This PR also adds testing of the method.
Closes #1146 

Add heterodyne method to TimeSeries class

---

gwpy/timeseries/tests/test_timeseries.py
gwpy/timeseries/timeseries.py

Adds `duration` and `nsamples` options to `TimeSeries.taper()` that allow user to specify a time duration or number of samples to taper rather than using the automatic tapering window. If neither are provided, the method defaults to the automatic tapering. If both `duration` and `nsamples` are provided, a `ValueError` is thrown to avoid mismatched taper arguments.
I also added a couple of explicit type casts to `int` that were causing issues when the specified number of taper samples was more than half of the duration of the data.

Added fixed length args to TimeSeries.taper

---

gwpy/cli/cliproduct.py
gwpy/cli/spectrogram.py
gwpy/cli/spectrum.py
gwpy/cli/tests/base.py
gwpy/utils/__init__.py
gwpy/utils/misc.py
gwpy/utils/tests/test_misc.py

This PR simply moves the `gwpy.cli.cliproduct.unique` utility into `gwpy.utils.misc`, which emerged as an useful thing to do in the discussion of #1156.

Move unique utility into gwpy.utils.misc

---

gwpy/signal/qtransform.py
gwpy/utils/__init__.py
gwpy/utils/misc.py
gwpy/utils/tests/test_misc.py

This PR introduces a new utility, `gwpy.utils.misc.round_to_power`, which accepts any positive scalar (`float`, `int`, `~astropy.units.Quantity`, etc.) and rounds (in log space) to the nearest integer power of a given base. The output has the same type as the base, and users can force the function to round up or down if they desire.
The new utility replaces and generalizes an existing one in `gwpy.signal.qtransform`.

Introduce a round_to_power utility

---

gwpy/timeseries/core.py
gwpy/timeseries/io/core.py
gwpy/timeseries/io/hdf5.py
gwpy/timeseries/io/nds2.py
gwpy/timeseries/tests/test_timeseries.py

This PR improves the support for padding gaps in data read using `.find()` or `.read()`. The main changes are:
- borrowed logic from the nds2 reader to ensure that all series are returned with the requested boundaries, padding the start or end as required
- allow gaps in datafind queries if `pad` is given
This should allow users to read, for example, months of trend data directly from GWF even if gaps are present.

Improved support for pad in TimeSeries.read and TimeSeries.find

---

.circleci/config.yml
gwpy/cli/cliproduct.py
gwpy/segments/flag.py
gwpy/signal/qtransform.py
gwpy/timeseries/tests/test_timeseries.py
gwpy/timeseries/timeseries.py
requirements-test.txt
setup.py

There are two new command line options 
* `--std-seg` which adds a predefined list of DQ segment ribbons see: https://ldvw.ligo.caltech.edu/ldvw/view?act=getImg&imgId=254114
* `--seg <segment name:version> [...]` add one or more segments by full name. See: https://ldvw.ligo.caltech.edu/ldvw/view?act=getImg&imgId=254112
Next version of ldvw implements the `--std-seg` option.  A subsequent version will have the ability to select which segments are displayed.

add optional segment ribbons to gwpy-plot when x-axis is time

---

ci/install-el.sh
gwpy/testing/utils.py
gwpy/timeseries/io/gwf/__init__.py
gwpy/timeseries/io/gwf/framecpp.py
gwpy/timeseries/io/gwf/lalframe.py
gwpy/timeseries/tests/test_io_gwf_framecpp.py
gwpy/timeseries/tests/test_io_gwf_lalframe.py
gwpy/timeseries/tests/test_timeseries.py

This PR fixes a bug in the application of ADC scale factors that prevented type casting between int arrays and floats.
cc @pmeyers279, @basswinkels

Fix to handle type changes when applying ADC scaling

---

gwpy/table/table.py
gwpy/table/tests/test_table.py

This adds a basic clustering method to `EventTable` objects. The clustering algorithm uses a pooling method to identify points that are all separated in time by less than `window`. The maximum value point of each cluster is calculated and replaces the cluster. 
An example (behind LIGO credentials) of clustering PyCBC Live triggers clustered with a 0.1 second window and maximizing over SNR.
Before: https://ldas-jobs.ligo.caltech.edu/~thomas.massinger/plots/test_clustering_unclustered_SNR.pdf
After: https://ldas-jobs.ligo.caltech.edu/~thomas.massinger/plots/test_clustering_clustered_SNR.pdf
Unit tests all pass when run from the command line.

Add basic clustering method to EventTable

---

docs/table/io.rst
gwpy/table/io/__init__.py
gwpy/table/io/snax.py
gwpy/table/tests/test_table.py

This adds in a new EventTable format, `hdf5.snax`, to read in SNAX-based features (formally known as GstLAL feature extractor).
Example:
```
>>> from gwpy.table import EventTable
>>> data = EventTable.read('H-GSTLAL_IDQ_FEATURES-1255853400-20.h5', 'H1:SUS-PRM_M3_WIT_P_DQ', format='hdf5.snax')
>>> data
<EventTable length=319>
time        frequency     q        snr       phase      duration 
float64        float32   float32   float32    float32     float32  
------------------ --------- --------- --------- ------------ ----------
1255853400.046875 29.116926  8.01923  3.179394 0.0115922745 0.59008665
...
```
`EventTable.read()` takes in an additional positional argument, `channel`, to specify the channel needed from the file since multiple channels are contained within.
I added a unit test, …

Add table format to read in SNAX features

---

gwpy/segments/tests/test_flag.py
gwpy/table/tests/test_table.py
gwpy/timeseries/tests/test_timeseries.py

This PR adds explicit `mode=<>` keyword arguments to all `h5py.File` calls. The default `mode` is changing in h5py-3.0.0 from `'a'` to `'r'`, so we need this to make sure nothing breaks - this should be backwards-compatible.

Pass mode to all h5py.File calls

---

gwpy/io/mp.py
gwpy/signal/spectral/_ui.py
gwpy/table/gravityspy.py
gwpy/timeseries/timeseries.py
gwpy/utils/mp.py
gwpy/utils/tests/test_mp.py
setup.cfg

This PR fixes use of multiprocessing with 'spawn' start methods (default on Windows, and on macOS for python-3.8) by removing the use of local functions with `multiprocess_with_queues`.

Remove use of local functions with multiprocessing

---

ci/install-conda.sh

This PR modifies the conda CI jobs to timeout the `conda install root_numpy` command after 2 minutes, so as to not timeout the whole build (e.g. [here](https://travis-ci.com/gwpy/gwpy/jobs/259811528)). `root_numpy` is an optional dependency, and this only times out on `python2.7`, so we don't really care if we don't have it in every test environment.

Timeout conda install of root_numpy in CI

---

.circleci/config.yml
ci/install-el.sh
etc/spec.template
gwpy/segments/tests/test_flag.py
gwpy/table/tests/test_table.py

Now that the LSCSoft yum repositories are updated to EPEL7.7, we can build python3.6 rpms directly, so this PR updates the spec file and adds the necessary CI jobs to do that.
I also took the opportunity to rip out the custom git tag workflow on CircleCI which has never worked, and just complicates the CI configuration.

Added python36 RPM build on epel77

---

gwpy/frequencyseries/frequencyseries.py

Fix the following error that occurred when interpolating a
complex-valued frequency series:
>>> FrequencySeries(np.arange(10) * 1j).interpolate(1)
File "<stdin>", line 1, in <module>
File "/usr/lib/python/site-packages/gwpy/frequencyseries/frequencyseries.py", line 297, in interpolate
self.value))
File "<__array_function__ internals>", line 6, in interp
File "/usr/lib/python3.7/site-packages/numpy/lib/function_base.py", line 1412, in interp
return interp_func(x, xp, fp, left, right)
TypeError: Cannot cast array data from dtype('complex128') to dtype('float64') according to the rule 'safe'
The abscissa for interpolation must be a real data type, even if
the frequency series is complex.

Fix bug in interpolating complex frequency series

---

debian/control
docs/install/index.rst
etc/spec.template
gwpy/table/io/fetch.py
requirements.txt
setup.py

This PR bumps the minimum astropy requirement to 1.3.0 now that the LSCSoft yum repositories have gotten that far. This allows the removal of one hack in `gwpy.table`.

Bump minimum astropy requirement to 1.3.0

---

gwpy/types/series.py
gwpy/types/tests/test_array2d.py
gwpy/types/tests/test_series.py

This PR fixes #1182, and improves the tests for `Series.pad` to minimise risk of regression.

Fix bug in x0 handling in Series.pad

---

gwpy/plot/axes.py

This PR improves the docstring for `gwpy.plot.Axes.legend` to explain better what the defaults are, and how to disable them if you want.
Related to #1187.

Improve documentation of custom legend handler in Axes.legend

---

etc/spec.template

This PR makes some generic improvements to the RPM spec file template, mainly in adding some sanity check tests in the `%check` section, which requires having all of the runtime dependencies declared as `BuildRequires` as well.

Improve RPM spec template

---

gwpy/table/table.py
gwpy/table/tests/test_table.py
requirements-test.txt

This PR fixes #886 by patching `EventTable.fetch()` to cast the returned table to a subclass if appropriate.
@scottcoughlin2014, please check that this fixes the issue properly for you.

Cast return of EventTable.fetch to subclasses

---

gwpy/frequencyseries/tests/test_frequencyseries.py
gwpy/types/io/ligolw.py

This PR fixes #1189, by applying the index `<Dim>` `Start` property properly.

Apply index dimension Start property when reading LIGO_LW Arrays

---

gwpy/table/io/pycbc.py
gwpy/table/tests/test_io_pycbc.py

This PR patches `gwpy.table.io.pycbc.patch_empty_files` to ignore the `'gates'` dataset that is now included in `pycbc_live` files. I also added a unit test for that function.

Patch pycbc empty_hdf5_files() to ignore gates dataset

---

.appveyor.yml
gwpy/cli/spectrogram.py
gwpy/frequencyseries/hist.py
gwpy/table/tests/test_gravityspy.py
gwpy/types/series.py

This PR fixes a few errors when running with `astropy` 4.0, mainly to do with comparing units, all fixed by using regular numpy arrays in that particular operation.

A few fixes to support astropy 4.0

---

ci/test.sh
gwpy/table/io/ligolw.py
gwpy/table/tests/test_io_ligolw.py
gwpy/table/tests/test_table.py

This PR improves the reading of empty tables from `LIGO_LW`-format XML. The tricky part is determining the correct `dtype` for dynamic columns (i.e. ones that aren't natively part of the XML structure, but are supported by the `ligo.lw` python API).

Improve reading of empty tables from LIGO_LW XML

---

requirements-test.txt
setup.py

This PR pins `mock` to `<4.0.0a0` on python 2, since 4.0.0 is python3-only, but `pip` has no idea how to respect that. This should fix the build failures seen in #1209, etc.

Pin mock for testing on python2

---

examples/test_examples.py
gwpy/astro/tests/test_range.py
gwpy/segments/tests/test_flag.py
gwpy/table/tests/test_gravityspy.py
gwpy/table/tests/test_table.py
gwpy/timeseries/tests/test_statevector.py
gwpy/timeseries/tests/test_timeseries.py
gwpy/utils/tests/test_lal.py

This PR adds a bunch of `# pragma: no-cover` comments around `pytest.skip()` calls, to exclude the skips in the coverage reports. This should mean that if tests start passing (when they used to fail) the coverage doesn't drop, and that the coverage doesn't fluctuate around flaky tests.

Don't include test skips in coverage

---

requirements-test.txt
requirements.txt
setup.py

This PR removes legacy dependency version pins that were required for python2 support.

Remove python2 version pins

---

docs/install/index.rst
gwpy/astro/tests/test_range.py
gwpy/frequencyseries/tests/test_frequencyseries.py
gwpy/plot/bode.py
gwpy/plot/tests/test_bode.py
gwpy/signal/filter_design.py
gwpy/signal/qtransform.py
gwpy/signal/spectral/_scipy.py
gwpy/signal/tests/test_spectral_scipy.py
gwpy/signal/window.py
gwpy/spectrogram/spectrogram.py
gwpy/timeseries/tests/test_core.py
gwpy/timeseries/tests/test_timeseries.py
gwpy/timeseries/timeseries.py
requirements.txt
setup.py

This PR bumps the minimum scipy version requirement to 1.2.0, and the minimum numpy version requirement to 1.12.0. The former is dictated by a need to support median averaging in spectrograms, and the latter is determined by a desire to support `numpy.geomspace`, both the most encompassing requirements I could find scattered throughout gwpy.
Per instructions left in comment lines, this includes a somewhat large-scale refactoring of `gwpy/signal/spectral/_scipy.py`.

Bump minimum scipy and numpy version requirements

---

gwpy/detector/channel.py
gwpy/detector/io/cis.py
gwpy/detector/tests/test_channel.py
requirements-dev.txt
requirements-test.txt

This PR updates the `Channel{List}.query` interface to the CIS API to use `ciecplib`, rather than the discontinued `ligo.org` python package.

Fix CIS API support

---

docs/install/index.rst
examples/test_examples.py
gwpy/astro/tests/test_range.py
gwpy/io/tests/test_mp.py
gwpy/table/tests/test_gravityspy.py
gwpy/table/tests/test_table.py
gwpy/timeseries/core.py
gwpy/utils/lal.py
requirements.txt
setup.py

This PR updates the `astropy` requirement to `>= 3.0.0`, mainly to remove annoying workarounds.

Update astropy requirement to 3.0.0

---

gwpy/io/gwf.py
gwpy/timeseries/io/gwf/framecpp.py
gwpy/timeseries/tests/test_io_gwf_framecpp.py

This PR fixes #1206 by patching `gwpy.io.gwf` to prefer the `Series.name` attribute when creating GWF structures, rather than the buggy mix that existed previously.
In principle this is backwards incompatible, since the `Series.channel` attribute was used before, but anyone who tried to write/read series where the `channel` and `name` were different would have hit #1206 anyway.

Write series to GWF using name attribute for all structure names

---

gwpy/cli/cliproduct.py
gwpy/cli/coherencegram.py
gwpy/cli/tests/base.py
gwpy/cli/tests/test_coherencegram.py
gwpy/plot/axes.py
gwpy/plot/bode.py
gwpy/plot/colorbar.py
gwpy/plot/colors.py
gwpy/plot/plot.py
gwpy/plot/rc.py
gwpy/plot/tests/test_axes.py
gwpy/plot/tests/test_log.py
gwpy/plot/tests/test_segments.py
gwpy/plot/tests/test_utils.py
gwpy/plot/utils.py
gwpy/types/array2d.py
requirements-test.txt
requirements.txt
setup.py

This PR updates the `matplotlib` requirement to `>= 3.0.0`, mainly to remove annoying workarounds.

Update matplotlib requirement to 3.0.0

---

ci/install-conda.sh

This PR fixes a CI issue where the curl of the miniconda installer for macOS fails to handle a redirect.

Fix CI failures curling miniconda installer on macos

---

gwpy/timeseries/tests/test_timeseries.py

This PR introduces some `pytest.skip` calls for tests that try `gwdatafind` queries that require X.509 credentials when none are available.

Skip timeseries tests that require X.509 and don't find it

---

gwpy/timeseries/io/core.py
gwpy/timeseries/tests/test_timeseries.py

This PR fixes a corner-case bug in reading data when the `[start, end)` request is a superset of the available data. In that case the data were automatically padded with `nan` which is bad, rather than just returning what we could.

Fix a bug in reading data asking for a superset of the available segment

---

ci/install-conda.sh
ci/parse-conda-requirements.py
gwpy/timeseries/tests/test_statevector.py
requirements.txt

This PR updates the `parse-conda-requirements.py` script to use `pkg_resources` to parse requirements files, rather than the internal API from `pip`, which breaks every now and then.
ADDENDUM: this also fixes a failing `StateVector` test by correcting a dataset version reference which was incorrect (prior to gwosc-0.5.3 that client didn't actually return the right dataset, so we didn't notice that ours was wrong).

Fix two issues with test suites

---

gwpy/io/gwf.py
gwpy/plot/axes.py
gwpy/plot/tests/test_axes.py
gwpy/plot/tests/test_segments.py
gwpy/signal/spectral/_lal.py
gwpy/timeseries/core.py
gwpy/timeseries/io/gwf/framecpp.py

This PR resolves a few precision issues of the sort:
```python
>>> print(lal.LIGOTimeGPS(1126259640.413))
1126259640.413000107
```
by calling through `to_gps` which prevents these precision issues (by itself using `str` as a go-between).

Prevent GPS precision errors by using to_gps as middleware

---

docs/install/index.rst
docs/plot/index.rst
docs/plot/log.rst
gwpy/plot/colorbar.py
gwpy/plot/log.py
gwpy/plot/plot.py
gwpy/plot/tests/test_log.py
requirements.txt
setup.py

This PR reworks the custom log formatters defined in `gwpy.plot.log` to improve the display of ticks across a number of different ranges. The end result is actually simpler code (less custom objects), which is nice.
Fixes #1129.

Updates to custom LogFormatters for plots

---

gwpy/timeseries/tests/test_timeseries.py
gwpy/timeseries/timeseries.py

This PR implements a new method, `TimeSeries.mask`, that masks away portions of a given timeseries which fall within of a user-defined deadtime. This can be given as either:
* A `SegmentList` custom-defining the deadtime
* The name of a data-quality flag to be queried for
The former will supersede the latter if both are given, and in the second case, the `DataQualityFlag.isgood` attribute is used to determine whether the given flag defines livetime or deadtime.
This method also optionally tapers away data at segment boundaries, with the taper length controlled by the user. The following corner cases are explicitly handled:
* The edges of the original `TimeSeries` **will not** be tapered
* Any livetime shorter than twice the taper length will get a subset of the tapering window, chosen so …

Implement a TimeSeries.mask method

---

gwpy/plot/tests/test_log.py

This PR fixes a failing test on matplotlib-3.2.2, which has updated TeX text formatting compared to 3.2.1.

Update test for matplotlib-3.2.2

---

gwpy/timeseries/io/core.py
gwpy/timeseries/io/losc.py
gwpy/timeseries/tests/test_timeseries.py

This PR fixes #1211 by fixing the timeseries reader to actually raise a `ValueError` if the underlying reader returns a proper subset of the requested `[start, end)` segment _and_ `gap='raise'` was given.

Raise ValueError in TimeSeries.read if file(s) return a proper subset of request

---

gwpy/astro/range.py
gwpy/signal/spectral/_registry.py
gwpy/timeseries/timeseries.py

This PR raises a `DeprecationWarning` loudly warning users that the default spectral averaging method will change to `'median'` in gwpy-2.1.0.
This is related to #1228.

Raise DeprecationWarning for a future change to the default spectral averaging method

---

docs/dev/release.rst
setup_utils.py

This PR fixes a couple of issues with the copyright update utility in `setup_utils.py`:
- on windows the regular expression didn't work, so this adds explicit parentheses around the years
- added a default year to the update functions (set to the 'current' year)

Fix some issues with the copyright update utility

---

gwpy/conftest.py
gwpy/plot/plot.py
gwpy/plot/tests/test_axes.py
gwpy/table/tests/test_table.py
gwpy/timeseries/core.py
gwpy/types/series.py

This PR updates the matplotlib usage to be compatible with matplotlib-3.3.0.
EDIT: this PR now includes #1258, mainly so that all of the tests pass. Closes #1258.

Update matplotlib usage for compatibility with 3.3.0

---

.circleci/config.yml
docs/install/index.rst
gwpy/plot/tests/test_axes.py
requirements.txt
setup.py

This PR adds a CI job to run the tests using the minimum requirements as declared in the `requirements.txt` file, mainly to check that they are correct.

Add CI job to test minimum requirements

---

ci/install-conda.sh
docs/conf.py
docs/install/index.rst
docs/references.rst
docs/table/io.rst
gwpy/table/io/root.py
gwpy/table/tests/test_table.py
requirements-dev.txt

This PR closes #1200 by re-implementing the ROOT-format input/output routines for `Table` and subclasses to use `uproot`. This is a much lighter library that is available on all platforms and doesn't require a working ROOT installation.
This should be API compatible, since everything is under-the-hood, but there are likely small differences that may trip up users who use ROOT I/O heavily - I don't actually know of anyone doing that.

Migrate ROOT I/O to uproot

---

gwpy/io/datafind.py
gwpy/io/gwf.py

This PR modifies two internal uses of `urlparse(x).path` to instead use the `gwpy.io.utils.file_path` function. Just stripping the scheme out (which is what `urlparse(x).path` does) sometimes causes problems on Windows when it gets passes a string with a drive name in it (e.g. `C:\Users\me\myfile.txt`). This should have no impact on anybody (except future me).

Fix internal use of urlparse(x).path to strip file url schemes

---

gwpy/table/io/ligolw.py
gwpy/table/tests/test_table.py

This PR fixes #1264 by improving the way that columns are handled when reading/writing LIGO_LW XML tables.
cc @myNameIsPatrick

Improve column handling for LIGO_LW XML

---

gwpy/timeseries/tests/test_timeseries.py

Minor change to `gwpy.timeseries` tests for compatibility with hdf5-3.1.0.

Fix compatibility with h5py-3.1.0

---

gwpy/plot/axes.py
gwpy/plot/tests/test_axes.py

This PR fixes #1277 by addressing the new incompatibility with matplotlib 3.3.3. I was hoping to find a better way to do this that doesn't just rely on a different private attribute, but didn't.

Fix compatibility with matplotlib 3.3.3

---

gwpy/frequencyseries/tests/test_frequencyseries.py
gwpy/types/io/ligolw.py

This PR fixes an issue seen by @rmacas when reading `<Array>` elements from LIGO_LW files. Fundamentally the problem was just that the wrong error message was printed when multiple `<Array>` elements were found and gwpy didn't know how to pick the right one (fixed in 288c3a20b1c578f977a909e7c8ebfdc185aa4949), but users probably require a wee bit more help to understand how to modify their code to avoid the error in the first place.

Improve error reporting/handling when reading LIGO_LW Arrays

---

gwpy/signal/spectral/_scipy.py
gwpy/timeseries/timeseries.py

This PR fixes #1242 by allowing users to select generic window functions when calculating Rayleigh spectra. As with other spectral density estimation methods, any window format recognized by [`scipy.signal.get_window`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.signal.get_window.html) is acceptable.
Note, Rayleigh spectra are given a hard 0 seconds of overlap between segments by default. Users will be able to either choose their own overlap, or pass `None` to get scipy's default based on the window function. This is reflected in various docstrings.

Allow generic window control for Rayleigh spectra

---

gwpy/signal/spectral/_scipy.py

This PR is a trivial docstring typo fix that I just noticed which went in with #1285.

Minor typo fix in Rayleigh spectrum docstring

---

gwpy/utils/decorators.py
gwpy/utils/tests/test_decorators.py

This PR fixes the handling of custom messages being passed to the `gwpy.utils.decorators.deprecated_function` decorator - this was clearly never tested properly.

Fix deprecated_function decorator

---

README.md

This PR fixes a typo in the new GitHub Actions README badge introduced in #1302.

Fix Github Actions badge

---

.github/workflows/lint.yml
docs/timeseries/io.rst

This PR adds a quality checks for the RST documentation source files to the CI workflow. I will then address any lint identified.

Add RST lint to github CI workflow

---

gwpy/plot/plot.py

This PR fixes an incompatibility with the release candidate for matplotlib-3.4.0 in which it seems that `figsize=None` is actively passed a lot more to figure constructors. Luckily, it's an almost trivial fix.

Fix handling of figsize=None in matplotlib 3.4.0

---

.github/workflows/dist.yml
gwpy/segments/tests/test_flag.py
gwpy/table/tests/test_gravityspy.py
gwpy/table/tests/test_table.py
gwpy/testing/errors.py
gwpy/timeseries/tests/test_statevector.py
gwpy/timeseries/tests/test_timeseries.py
requirements-test.txt

This PR adds a new `gwpy.testing.errors` module that provides a decorator function to catch and apply `pytest.skip` when common network errors are found - we typically don't want to fail the suite because of these. This allows us to clean up a bunch of repeated usage through the test suite.

Add new gwpy.testing.errors module to provide error-handling utilities for the test suite

---

docs/references.rst
docs/table/io.rst
gwpy/table/io/root.py
gwpy/table/tests/test_table.py
requirements-dev.txt

This PR adds basic support for `uproot >=4`. It's hacky because uproot 4 doesn't support writing ROOT files yet, so there's an import hook in place to advise users to install `uproot3` to do that if they need to.

Add basic support for uproot4

---

gwpy/segments/flag.py
gwpy/segments/tests/test_flag.py

This PR fixes a minor issue in the `DataQualityFlag.from_veto_def` whereby the incoming `VetoDef` object was being modified in-place, which causes issues when you try and fake it using a `namedtuple` (see #1268).

Don't modify incoming VetoDef object when converting to DataQualityFlag

---

examples/test_examples.py
gwpy/cli/cliproduct.py
gwpy/io/ligolw.py
gwpy/plot/axes.py
gwpy/plot/colorbar.py
gwpy/timeseries/tests/test_timeseries.py
gwpy/types/array.py
gwpy/types/tests/test_array.py
requirements-dev.txt
requirements.txt
setup.py

This PR addresses several runtime warnings that arise during build-and-test:
* Do not duplicate the `'cmap'` parameter between the `mappable` and `ax.colorbar()` (see [matplotlib release notes](https://matplotlib.org/3.3.0/api/prev_api_changes/api_changes_3.3.0/deprecations.html#effectless-parameters-of-figure-colorbar-and-matplotlib-colorbar-colorbar))
* Log-scaled plot axes have deprecated kwargs (see [matplotlib release notes](https://matplotlib.org/3.3.1/api/api_changes.html#log-symlog-scale-base-ticks-and-nonpos-specification))
* The `numpy.ndarray.tostring()` method is deprecated as of 1.19, and its replacement `tobytes` has been available since 1.9 (see [numpy documentation](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.tostring.html))
* Warnings about …

Resolve various warnings during build-and-test

---

gwpy/plot/axes.py
gwpy/plot/tests/test_axes.py

This PR simplifies the overloaded `Axes.scatter` method as follows:
- handle an `s` (size) array as well, seaborn 0.11.1 expects these to be acceptable as positional arguments,
- renamed `c_sort{=True}` to `sortbycolor=False`, to have a better name and have the same default action as matplotlib's `Axes.scatter`
@alurban @eagoetz, this probably has implications for the summary pages, which I think rely upon the default sorting by colour.

Simplify Axes.scatter to better handle arguments

---

gwpy/timeseries/timeseries.py

This PR replaces `numpy.complex` with `numpy.complex128` to resolve a deprecation warning from numpy 1.20.0, see
https://numpy.org/devdocs/release/1.20.0-notes.html#using-the-aliases-of-builtin-types-like-np-int-is-deprecated.

Replace use of numpy alias type with builtin

---

.github/workflows/build.yml
gwpy/testing/utils.py
gwpy/timeseries/tests/test_statevector.py
gwpy/timeseries/tests/test_timeseries.py

This PR fixes a test suite failure introduced by #1290 that an `NDSWarning` isn't emitted when you can actually use gwdatafind. This also updates the `LOSC_` variables in the timeseries test suite to use `GWOSC_` as the prefix.

Fix NDS2Warnings in TimeSeries tests

---

docs/conf.py
setup.cfg

This PR fixes a deprecation warning in the sphinx docs build by updating to at least sphinx 1.8.0 and renaming a function.

Fix deprecation warning in sphinx

---

.github/workflows/build.yml
.github/workflows/dependencies.yml
.github/workflows/dist.yml
.github/workflows/lint.yml

This PR cherry picks e5aa21fd04544aefcc99eb0f08b1ea9eebb31c18 from the `release/2.0.x` branch (see #1316) onto `master`.

Run github actions on release branches

---

docs/overview.rst
docs/plot/colors.rst
examples/frequencyseries/percentiles.py
gwpy/cli/timeseries.py
gwpy/plot/tests/test_gps.py
gwpy/plot/tests/test_plot.py
gwpy/plot/tests/utils.py

This PR updates some internal calls to address `DeprecationWarning`s from Matplotlib 3.4.

Address DeprecationWarnings from Matplotlib 3.4

---

gwpy/testing/errors.py

This PR adds `ConnectionError` to the list of errors to `pytest.skip` gracefully if a remote network connection fails. This was seen in a local conda-build test of gwpy-2.0.4.

Add ConnectionError to  pytest network errors list

---

gwpy/table/io/root.py

The latest uproot 4.x includes `create()` and `recreate()` functions, but don't include the `newtree` function that we need to translate numpy arrays into ROOT-serialisable objects, so this PR just updates the `_import_uproot_that_can_write_root_files()` function to check for `newtree`.

Fix detection of uproot4 writing capability

---

gwpy/io/cache.py
gwpy/testing/errors.py
gwpy/timeseries/tests/test_timeseries.py

This PR adds some error-handling to skip over CVMFS-related failures in the test suite.
There's currently an issue with gwosc.osgstorage.org that is failing the tests, but since this isn't really a GWpy issue we should skip those failures.

Handle CVMFS failures more gracefully

---

gwpy/detector/channel.py
gwpy/io/nds2.py
gwpy/io/tests/test_nds2.py

This PR refactors the Enum generation in `gwpy.io.nds2` to dynamically generate the `Nds2ChannelType` and `Nds2DataType` enums if possible using the `nds2.channel` object itself. This should mean that the enums are always an accurate reflection of the underlying NDS2 interface, if present.
This does present a minor breaking change in that the enums no longer overload the `name` property, instead providing a `nds2name` property instead.

Dynamically generate NDS2 enums

---

gwpy/io/nds2.py
gwpy/io/tests/test_nds2.py

This PR fixes a bug in Nds2ChannelType.find whereby valid NDS2 channel type strings (e.g. `'reduced'`) weren't being recognised because they didn't match the enum attribute name (e.g. `'RDS'`). See https://git.ligo.org/nds/nds2-client/-/issues/118 for a short discussion of this naming choice in the NDS2 client.
This closes #1297 with the caveat that the correct NDS2 name for the channel is `'L1:DCS-CALIB_STRAIN_CLEAN_SUB60HZ_C01,reduced'` (and not `'L1:DCS-CALIB_STRAIN_CLEAN_SUB60HZ_C01,rds'`). 
Closes #1298.

Fix bug in Nds2ChannelType.find

---

gwpy/io/ligolw.py
gwpy/io/tests/test_ligolw.py
gwpy/segments/io/ligolw.py

This PR introduces some general improvements to `gwpy.io.ligolw`, including
- deprecating a couple of unused functions
- improving functionality in a couple of places
- adding more tests
There should be no API changes, other than the addition of a new function `gwpy.io.ligolw.iter_tables`.

Improve gwpy.io.ligolw

---

gwpy/plot/bode.py

Fixed the typo where argument `dB` was written as `db`, which would mislead the user when using this class. This pull request is in reference to #1332.
EDIT (@duncanmmacleod): closes #1332.

Fix Docs of class BodePlot

---

gwpy/cli/cliproduct.py
gwpy/cli/spectrogram.py
gwpy/cli/spectrum.py

This PR adds a `--average-method` command-line option for the relevant `gwpy-plot` products, which defaults to the `DEFAULT_FFT_METHOD` from `gwpy.timeseries.timeseries`. This is currently `None` (`'welch'`) but is due to change in #1282 to `'median'`.

Add --average-method command-line option for gwpy-plot products

---

gwpy/detector/units.py

This PR fixes the enabling of the `imperial` units from astropy. astropy/astropy#11204 removed `imperial` from the `astropy.units` namespace, but it's still importable if you go at it directly.

Fix enable for imperial units

---

pyproject.toml
setup.cfg

This PR migrates the pytest configuration from `setup.cfg` to `pyproject.toml`, and then adds a few warnings that aren't our problem.
This is extracted from #1331 to get it through quickly so that it can be used elsewhere.

Migrate pytest configuration to pyproject.toml

---

gwpy/signal/filter_design.py

This PR adds support for specifying the `output` keyword for the `gwpy.signal.filter_design.notch` function, allowing notches to be designed in SOS format.

Support output kwarg in gwpy.signal.filter_design.notch()

---

gwpy/io/ligolw.py

This PR fixes a `DeprecationWarning` from numpy, see https://github.com/numpy/numpy/pull/17586.

Replace numpy.typeDict with numpy.sctypeDict

---

gwpy/plot/tests/test_log.py

This PR removes a lingering `ImportError` catch relating to `unittest.mock`; we don't support python < 3 any more.

Remove unnecessary import protection for python < 3

---

.github/workflows/build.yml
.github/workflows/dependencies.yml
.github/workflows/dist.yml
.github/workflows/lint.yml

This PR reconfigures the Github Actions workflows to automatically cancel redundant workflows when a new commit is pushed to the matching reference, in an attempt to be a good citizen and speed up time-to-completion at the PR level.

Automatically cancel redundant CI workflows

---

.github/workflows/build.yml
.github/workflows/dependencies.yml
.github/workflows/dist.yml
.github/workflows/lint.yml

This PR makes two small changes to the Github Actions CI
- run all jobs on the `main` branch - this just means that if we rename `master` to `main` we don't have to update the CI again
- run the `Dependencies` workflow on a cron schedule every night - this should allow us to catch breaking changes in dependencies as early as possible, rather than 'whenever the next person submits a PR'

Update CI to run on main branch and run some jobs nightly

---

gwpy/plot/units.py

This PR addresses a warning emitted by Astropy 4.3+ relating to formatting of `<unit>.physical_type`, which used to just be a `str`, but is now a structured object that complains about using `str` methods.

Fix physical_type str formatting for astropy 4.3+

---

gwpy/astro/tests/test_range.py

This PR updates some unit test function names in `gwpy.astro` to match the upstream changes introduced in #1293. This also hardcodes the `method='welch'` used in the ASD calculations to prevent `DeprecationWarning` from `gwpy.signal`.

Update test function names in gwpy.astro

---

docs/table/io.rst
gwpy/table/io/snax.py
gwpy/table/tests/test_table.py

This modifies the `channel` argument to be optional (now `channels`) and allows for more flexible behavior for reading SNAX files. In particular, this allows reading multiple channels at once from a single hdf5 file by providing a list of channels. If `channels` is not specified, this will attempt to read in all channels from the file.
In order to preserve the uniqueness across channels, a 'channel' column is added into the `EventTable` during the read process.
Also update relevant unit tests for all modified behavior as well as the docs on "Reading and writing Table and EventTable objects" in the SNAX section.

EventTable.read(): modify API for `hdf5.snax` format

---

gwpy/cli/cliproduct.py
gwpy/cli/qtransform.py
gwpy/cli/tests/test_qtransform.py

This PR enables the FFT command-line options for the `gwpy-plot` qtransform product to allow specification of fftlength/overlap/method for the whitening ASD calculation.
This is dependent upon #1329.

Enable FFT options for gwpy-plot qtransform product

---

gwpy/table/table.py
gwpy/table/tests/test_table.py

This PR introduces a refactoring of the internal method `EventTable._get_time_column` in an attempt to simplify the logic. This method is used mainly in plotting to try and automatically detect that a column represents 'time' and to use a GPS-scaled axis for it.

Improve auto-detection of time-like columns in tables

---

gwpy/astro/range.py
gwpy/astro/tests/test_range.py
gwpy/signal/spectral/_registry.py
gwpy/timeseries/timeseries.py

This PR fixes #1228 by changing the default spectral averaging method to `'median'` across the codebase. This includes changes to reference values in the unit tests for `gwpy.astro` to reflect median averaging.

Change default spectral averaging method to 'median'

---

gwpy/signal/spectral/__init__.py
gwpy/signal/spectral/_scipy.py
gwpy/timeseries/timeseries.py

This PR closes #1328 by reimplementing `TimeSeries.coherence` to call out to `scipy.signal.coherence` rather than `mlab.cohere`.

Refactor TimeSeries.coherence to use scipy.signal.coherence

---

gwpy/conftest.py
gwpy/testing/marks.py
gwpy/timeseries/tests/test_timeseries.py

This PR adds support for custom, registered pytest marks. The only mark added at the moment is `cvmfs`, which has been applied to all of those tests that attempt to use the GWOSC CVMFS repo.

Add custom pytest marks

---

gwpy/io/ligolw.py
gwpy/io/tests/test_ligolw.py

This PR improves I/O operations and file handling in the `gwpy.io.ligolw.open_xmldoc` function to handle `Path`, and better handle compatibility issues with `glue.ligolw`.

Improve file I/O in gwpy.io.ligolw.open_xmldoc

---

gwpy/timeseries/timeseries.py

This PR fixes a trivial typo in the docstring of `TimeSeries.heterodyne` that impacts rendering the docstring with sphinx.

Fix typo in docstring of TimeSeries.heterodyne()

---

gwpy/table/io/ligolw.py
gwpy/table/tests/test_io_ligolw.py

This PR fixes #1367 by adding `username` to the list of column names for which `get_{}` doesn't do what you think it does.

Don't use ProcessTable.get_username to get the username column

---

gwpy/io/cache.py
gwpy/io/datafind.py

This PR refactors the `gwpy.io.datafind.find_frametype` function, which was a beastly monolith, and is now a little tamer. This also includes a few fixes for the following
- gracefully handle failing to read the channel list (TOC) from a GWF file (`RuntimeError`)
- add Virgo types to ranking system
- some optimisations for reading cache files
This should have zero impact on users, other than hiding errors.

Refactor datafind.find_frametype function

---

docs/cli/index.rst
docs/conf.py

This PR improves the handling/rendering of the `gwpy.cli` examples as part of the documentation. I think the changes basically boil down to:
- only run the example if it has changed or the output doesn't exist yet
- resolve a couple of sphinx warnings

Improve gwpy.cli example handling in docs

---

docs/conf.py

This PR modifies the sphinx configuration to just use `dev` as the version number when building outside of tags. This is needed since the tags aren't always synchronised to the development branch (since we use a `release/X.Y.z` branch for bug-fix releases). E.g. the current dev docs say `2.0.1` because the 2.0.2-2.0.4 tags aren't on `master`.

Use 'dev' as the version for development documentation builds

---

docs/conf.py

This PR fixes a bug in the use of `ConfigParser.get` introduced by #1378: the `fallback` argument to `ConfigParser.get` can _only_ be used as a keyword argument.

Fix a critical bug in the documentation configuration

---

.github/workflows/build.yml

This PR adds an argument to `pytest` to execute the examples as part of the full `build-and-test` suite run. This used to happen, but I think got lost during the transition to github actions.

Execute the examples as part of the test suite in CI

---

docs/index.rst

This PR reshuffles the items in the top-level documentation index, mainly to clean up the global toc sidebar.

Restructure documentation index page

---

docs/plot/colorbars.rst
examples/frequencyseries/percentiles.py
examples/miscellaneous/range-spectrogram.py
examples/miscellaneous/range-timeseries.py
examples/signal/qscan.py
gwpy/timeseries/core.py

This PR removes all usage of the deprecated `tag` keyword in calls to `TimeSeries.fetch_open_data` - this should resolve a bunch of `DeprecationWarning`s emitted when building the documentation.

Remove usage of tag keyword in calls to TimeSeries.fetch_open_data

---

gwpy/io/datafind.py
gwpy/io/tests/test_datafind.py

This PR fixes an apparently critical problem with `gwpy.io.datafind.find_frametype` that _may_ have been introduced by #1376 where trend requests weren't properly parsed, so the wrong trend type may have been selected.
This was flagged by the `test_find_best_frametype_ligo` test function, but that only runs during the cron nightly build at Caltech, which isn't part of the github CI.

Fix datafind trend discovery

---

gwpy/frequencyseries/tests/test_hist.py
gwpy/timeseries/tests/test_statevector.py
gwpy/types/array2d.py
gwpy/types/series.py
gwpy/types/tests/test_array2d.py
gwpy/types/tests/test_series.py

This PR refactors the `Series.is_compatible` method by separating internal logic into two functions, and then improve the tests. This also adds one small improvement that irregular `Series` can now be compatible if their X-index arrays match identically.

Refactor `Series.is_compatible`

---

docs/timeseries/io.rst
gwpy/segments/flag.py
gwpy/timeseries/core.py
gwpy/timeseries/io/losc.py
gwpy/timeseries/tests/test_io_losc.py
gwpy/timeseries/tests/test_timeseries.py
gwpy/timeseries/timeseries.py

This PR updates references to LOSC to use 'GWOSC', which is the newer name. This includes renaming the `hdf5.losc` I/O format to `hdf5.gwosc`, but the old name is retaining in a deprecated manner (with tests added to check the deprecation warning is emitted).

Update 'LOSC' references to 'GWOSC'

---

gwpy/timeseries/io/gwf/framecpp.py
setup.cfg

This PR fixes a failing test when running with the latest versions of `ldas-tools-framecpp`, in which `FrAdcData` structures are created with a `DEFAULT_SLOPE` of `0.`, with no way to change the slope from the Python bindings. This means that if you write a GWF from Python that contains ADC channels, the slope you read back is _always_ `0.`. The patch here is to replace a default of `0.` with `1.` if the bias is also at its default (`0.`).
See https://git.ligo.org/ldastools/LDAS_Tools/-/issues/114

Handle default ADC slope of 0. in new frameCPP versions

---

gwpy/spectrogram/tests/test_spectrogram.py
gwpy/timeseries/tests/test_statevector.py

This PR fixes a couple of instances of `assert ax.lines == []`, which doesn't work any more as of matplotlib-3.5.0b1. This is easy fixed by comparing only the lengths of the objects, which is independently defined for the `ArtistList` object.

Fix compatibility with matplotlib-3.5.0

---

gwpy/detector/io/clf.py
gwpy/detector/io/omega.py
gwpy/io/cache.py
gwpy/io/tests/test_utils.py
gwpy/io/utils.py
gwpy/segments/io/json.py
gwpy/segments/io/segwizard.py
gwpy/timeseries/io/gwf/framel.py
gwpy/timeseries/io/gwf/lalframe.py

This PR fixes up a number of functions to enable reading from `pathlib.Path` objects as well as `file` and `str`. This probably supersedes #1360.

Fix pathlib compatibility in file I/O

---

ci/parse-conda-requirements.py

This PR improves the error handling in the `parse-conda-requirements.py` script. When an UnsatisfiableError is raised by `conda install` there won't be a `'packages'` key in the JSON output, so we need to catch `KeyError` then run it again to expose the underlying problem. See build errors in #1366 for an example of why this is needed.

Catch KeyError when filtering errors from parse-conda-requirements.py

---

gwpy/cli/tests/base.py
gwpy/cli/tests/test_gwpy_plot.py
gwpy/detector/tests/test_channel.py
gwpy/frequencyseries/tests/test_frequencyseries.py
gwpy/io/tests/test_cache.py
gwpy/io/tests/test_datafind.py
gwpy/io/tests/test_gwf.py
gwpy/io/tests/test_ligolw.py
gwpy/io/tests/test_mp.py
gwpy/io/tests/test_utils.py
gwpy/plot/tests/test_plot.py
gwpy/segments/tests/test_flag.py
gwpy/segments/tests/test_segments.py
gwpy/signal/tests/test_spectral_median_mean.py
gwpy/table/tests/test_table.py
gwpy/testing/fixtures.py
gwpy/testing/utils.py
gwpy/timeseries/tests/test_io_gwf_framecpp.py
gwpy/timeseries/tests/test_io_gwf_lalframe.py
gwpy/timeseries/tests/test_timeseries.py

This PR deprecates the `gwpy.testing.utils.TemporaryFile` context manager function and the `gwpy.testing.fixtures.tmpfile` test fixture. These are basically no longer required now that we can rely properly on the [`tmp_path`](https://docs.pytest.org/en/stable/tmpdir.html?) fixture from pytest.

Deprecate TemporaryFile context manager and tmpfile test fixture

---

.github/workflows/dependencies.yml

The experimental dependencies check has been failing for a while because the check is running on Python 3.10 which doesn't have any lalsuite wheels yet. For now we need to pin back to Python 3.9. This may expose #1432.

Pin the experimental dependencies check to Python 3.9

---

gwpy/io/registry.py
gwpy/table/io/fetch.py
gwpy/timeseries/core.py
gwpy/timeseries/statevector.py

This PR fixes #1432 by updating the use of a private function from `astropy.io.registry`. This is still a hack, but is the easiest thing to do while attempting to support the old registry format and the new class-based system at the same time.

Update gwpy.io to support Astropy 5 class-based registries

---

setup.cfg

This PR removes a redundant entry from the `dev` extra spec in `setup.cfg`; this should have been removed as part of #1396.

Remove ldas-tools-framecpp from conda extra in setup.cfg

---

gwpy/io/kerberos.py
gwpy/io/tests/test_kerberos.py
gwpy/plot/tests/test_tex.py
gwpy/plot/tex.py
gwpy/utils/shell.py
gwpy/utils/tests/test_shell.py

~~This PR modifies `gwpy.utils.shell.which` to use `shutil.which` instead of `distutils.spawn.find_executable`, which doesn't work as well on windows.~~
This PR deprecates the `gwpy.utils.shell.which` function, people should use use `shutil.which` directly.

Deprecate gwpy.utils.shell.which

---

gwpy/segments/flag.py

This PR addresses a `DeprecationWarning` emitted by Python 3.10, see https://docs.python.org/3/whatsnew/3.10.html#deprecated.

Address python 3.10 deprecation warning

---

gwpy/cli/cliproduct.py
gwpy/plot/axes.py
gwpy/plot/legend.py
gwpy/plot/plot.py
gwpy/plot/tests/test_log.py

This PR addresses a number of `DeprecationWarning`s from matplotlib 3.5.0.

Update compatibility with matplotlib 3.5.0

---

gwpy/segments/flag.py
gwpy/segments/tests/test_flag.py
gwpy/testing/mocks.py

This PR closes #1350 by removing all support for querying an S6-style DB2 database using `lscsoft-glue`.
cc @rpfisher, @robertbruntz

Remove s6 segment server query support

---

examples/timeseries/public.py

This PR updates the 'public' example of the `TimeSeries` object, mainly to include use of the GWOSC python API.

Update timeseries/public example

---

.github/workflows/dist.yml
setup.cfg

This PR adds Python 3.10 to the list of versions to build in CI.

Add basic Python 3.10 builds in CI

---

gwpy/detector/__init__.py
gwpy/detector/channel.py
gwpy/detector/io/cis.py
gwpy/detector/io/clf.py
gwpy/detector/io/omega.py
gwpy/detector/tests/test_channel.py
gwpy/detector/units.py

This PR updates the `gwpy.detector` module to use [f-strings](https://www.python.org/dev/peps/pep-0498/) for all string formatting, instead of a mix of `str.format` and `%`-formatting.

Use f-strings for string formatting in gwpy.detector

---

gwpy/cli/cliproduct.py
gwpy/cli/coherence.py
gwpy/cli/coherencegram.py
gwpy/cli/gwpy_plot.py
gwpy/cli/qtransform.py
gwpy/cli/spectrogram.py
gwpy/cli/spectrum.py
gwpy/cli/tests/test_coherence.py
gwpy/cli/tests/test_coherencegram.py
gwpy/cli/tests/test_qtransform.py
gwpy/cli/tests/test_spectrogram.py
gwpy/cli/tests/test_spectrum.py
gwpy/cli/tests/test_timeseries.py
gwpy/cli/timeseries.py

This PR updates the `gwpy.cli` module to use [f-strings](https://www.python.org/dev/peps/pep-0498/) for all string formatting, instead of a mix of `str.format` and `%`-formatting.
I think f-strings are a nice, readable way to do most of this formatting, and normally result in shorter statements.

Use f-strings for string formatting in gwpy.cli

---

gwpy/io/cache.py
gwpy/io/datafind.py
gwpy/io/gwf.py
gwpy/io/hdf5.py
gwpy/io/kerberos.py
gwpy/io/ligolw.py
gwpy/io/mp.py
gwpy/io/nds2.py
gwpy/io/tests/test_cache.py
gwpy/io/tests/test_gwf.py
gwpy/io/tests/test_ligolw.py
gwpy/io/tests/test_nds2.py
gwpy/io/tests/test_utils.py
gwpy/io/utils.py

This PR updates the `gwpy.io` module to use [f-strings](https://www.python.org/dev/peps/pep-0498/) for all string formatting, instead of a mix of `str.format` and `%`-formatting.

Use f-strings for string formatting in gwpy.io

---

gwpy/signal/window.py

This PR fixes compatibility with scipy 1.8.0 by updating the usage of `scipy.signal.windows`.

Fix import of scipy.signal.windows for scipy 1.8.0

---

.github/workflows/build.yml
.github/workflows/dependencies.yml
.github/workflows/dist.yml
CONTRIBUTING.md
docs/install.rst
setup.cfg

This PR removes support for Python 3.6.
As per NEP29 this version has already been dropped by a number of upstream packages as well as the conda-forge packaging group.

Drop support for python3.6

---

docs/install.rst
setup.cfg

This PR bumps the minimum requirement on Astropy to `>= 4.0`, principally to resolve warnings from erfa relating to leap seconds for 2022. This also updates numpy since astropy will require at least 1.16 anyway.

Update minimum astropy requirement to 4.0

---

docs/references.rst
docs/table/io.rst
gwpy/table/gravityspy.py
gwpy/table/tests/test_gravityspy.py
setup.cfg

This PR refactors the `GravitySpyTable` code to simplify the methods and remove the requirement on Pandas. This has been replaced by a requirement on `requests`, which is fine since `gwosc` already requires `requests`, and `gwpy` requires `gwosc`.
cc @scottcoughlin2014

Refactor GravitySpyTable

---

gwpy/frequencyseries/_fdcommon.py
gwpy/frequencyseries/frequencyseries.py
gwpy/frequencyseries/hist.py

This PR updates the `gwpy.frequencyseries` module to use [f-strings](https://www.python.org/dev/peps/pep-0498/) for all string formatting, instead of a mix of `str.format` and `%`-formatting.

Use f-strings for string formatting in gwpy.frequencyseries

---

docs/references.rst
docs/table/io.rst
gwpy/table/io/root.py
gwpy/table/tests/test_table.py
setup.cfg

This PR updates the ROOT I/O interface to use `uproot` (v4) for writing ROOT files, rather than relying up uproot3.
Depends on #1441.

Use uproot4 for writing ROOT files as well

---

docs/conf.py
docs/install.rst
docs/segments/io.rst
docs/table/io.rst
gwpy/io/ligolw.py
gwpy/io/tests/test_ligolw.py
gwpy/segments/flag.py
gwpy/segments/io/ligolw.py
gwpy/segments/tests/test_flag.py
gwpy/table/io/ligolw.py
gwpy/table/tests/test_table.py

This PR simplifies reading LIGO_LW-format XML documents by replacing the annoying `ilwdchar_compat` system where documents are parsed twice, with a content handler-based system where `ilwdchar` types are swapped with the relevant `int`-like types on-the-fly automatically as documents are being parsed.
This allows to simplify everything else about reading LIGO_LW documents.

Simplify reading LIGO_LW documents

---

gwpy/io/cache.py
gwpy/timeseries/tests/test_timeseries.py

This PR fixes #1473 by simplifying the `gwpy.io.cache.is_cache` method in two ways
- use `float` as the GPS column type, which has more predictable error reporting (`ValueError`) and no stderr output
- catch all exceptions from `read_cache` and return `False`

Fix reading ASCII files that contain a header that is five words long

---

.github/workflows/dependencies.yml

This PR works around https://github.com/pypa/pip/issues/10851 in the 'experimental dependencies' CI job.

Avoid broken pip in CI jobs

---

gwpy/table/table.py
gwpy/table/tests/test_table.py

This PR handles a few edge cases more gracefully when calling `EventTable.cluster()`:
1. The table is empty.
2. The table is already clustered.
In both cases, the error encountered looks like:
```
>>> table.cluster('time', 'snr', 0.1)
File "<stdin>", line 1, in <module>
File "/home/patrick.godwin/workspace/projects/gwpy/gwpy/table/table.py", line 782, in cluster
padded_sublists = [numpy.append(s, numpy.array([s[-1]+1]))
File "/home/patrick.godwin/workspace/projects/gwpy/gwpy/table/table.py", line 782, in <listcomp>
padded_sublists = [numpy.append(s, numpy.array([s[-1]+1]))
IndexError: index -1 is out of bounds for axis 0 with size 0
```
In both cases, the original table is now returned as a result. I have also added a test which checks that running …

Handle cases in EventTable.cluster() where table is empty or clustered multiple times

---

examples/frequencyseries/transfer_function.py
gwpy/cli/__init__.py
gwpy/cli/tests/test_transferfunction.py
gwpy/cli/transferfunction.py
gwpy/timeseries/tests/test_timeseries.py
gwpy/timeseries/timeseries.py

Added a TimeSeries method to compute the transfer function between two TimeSeries objects; added command line functions to carry this out as well, as I thought that may be useful for, e.g., LDVW
This method follows the standard procedure to compute the unknown transfer function between two time series using the cross spectral density and power spectral density estimators. This is what DTT does [see, page 20](https://dcc.ligo.org/DocDB/0026/T990013/002/Diagnostics_Test_Software_DCC_T990013_v2.pdf)
This functionality was mentioned in #321, though perhaps not initially what Andy had in mind as he mentions ASD2, etc., and code snippet suggested by [me](https://github.com/gwpy/gwpy/issues/321#issuecomment-566669307)

Add a method to compute the transfer function between two TimeSeries objects

---

gwpy/signal/filter_design.py

This PR fixes a `DeprecationWarning` when importing `LinearTimeInvariant` with scipy 1.8.0a0.

Fix deprecationwarning from scipy 1.8.0

---

gwpy/plot/axes.py
gwpy/plot/tests/test_axes.py
pyproject.toml

This PR updates `Axes.tile()` to recognise the `sortbycolor=False` keyword, to bring it inline with `Axes.scatter`.
I also added deprecated support for the old `c_sort` variable to assist downstream users with legacy code.
cc @eagoetz.

Update Axes.tile to use sortbycolor

---

gwpy/timeseries/io/losc.py
gwpy/timeseries/tests/test_io_losc.py

This PR removes the `hdf5.losc` I/O format registration, which has been deprecated since v2.1.0 (see https://github.com/gwpy/gwpy/commit/4de83cac937136cdec35e0bdb41b1a7d6c8b380a).

Remove the deprecated hdf5.losc format

---

gwpy/detector/units.py

This PR improves the handling of the 'strain' unit by removing the equivalence with astropy's dimensionless_unscaled. This means that it won't be silently dropped during unit operations.
Before:
```python
>>> import gwpy.detector  # register the 'strain' unit
>>> from astropy import units
>>> units.Unit('strain') * units.Unit('second')
Unit("s")
```
After:
```python
>>> import gwpy.detector
>>> from astropy import units
>>> units.Unit('strain') * units.Unit('second')
Unit("s strain")
```

Remove equivalence between custom strain unit and 'dimensionless_unscaled'

---

gwpy/spectrogram/spectrogram.py

This PR removes the deprecated `Spectrogram.plot` `imshow` keyword, which has been deprecated since v0.12.0,
see 652e0cfa0f817d8651252363cf5218662b12322e.

Remove deprecated Spectrogram.plot keyword

---

gwpy/plot/axes.py
gwpy/plot/legend.py
gwpy/plot/tests/test_axes.py

This PR removes the two deprecated `gwpy.plot.Axes.legend` keyword arguments which have been deprecated since v1.0.0,
see 78675976382aec23450aeccd0c784f5496a0c6af.

Remove deprecated Axes.legend kwargs

---

gwpy/plot/axes.py

This PR fixes an issue shown up by the linter caused by merging PRs #1470 and #1483 without rebasing.

Add missing import of warnings module

---

gwpy/timeseries/io/gwf/lalframe.py
gwpy/timeseries/tests/test_timeseries.py

This PR fixes #1486 by fixing an issue with how the LALFrame API (`gwpy.timeseries.io.gwf.lalframe`) pins the 'end' time of a read request. This effectively now matches the behaviour of the framecpp and framel APIs.

Fix reading a contiguous series of files with LALFrame

---

gwpy/signal/filter_design.py

This PR simplifies the handling of `scipy.signal.LinearTimeInvariant` objects in `gwpy.signal.filter_design`; the change in #1484 doesn't actually work with scipy-1.8.0.

Simplify parsing LTI objects

---

CONTRIBUTING.md
README.md
docs/dev/release.rst
docs/timeseries/io.rst

This PR updates the few references to the old default branch (`master`) to `main`. I included a more generic update to the contributing guide as I noticed that it was out-of-date relative to my recommended workflow.

Update default branch references from master to main

---

.flake8
pyproject.toml
setup.cfg

This PR implements a minor metadata cleanup, migrating non-setuptools configurations out of `setup.cfg` into either `pyproject.toml` or their own file.

Minor metadata cleanup

---

.github/workflows/lint.yml
docs/dev/release.rst
docs/table/io.rst
docs/timeseries/datafind.rst
pyproject.toml

This PR updates `rstcheck` in the Lint CI workflow to use `>=6.0.0`, which has renamed command-line options.

Update rstcheck to 6.x

---

docs/install.rst
docs/timeseries/datafind.rst
gwpy/io/datafind.py
gwpy/io/ffldatafind.py
gwpy/io/tests/test_datafind.py
gwpy/io/tests/test_ffldatafind.py
gwpy/timeseries/core.py
gwpy/timeseries/tests/test_timeseries.py
setup.cfg

This PR updates the GWDataFind interface in `gwpy.io.datafind` to use the supported functional UI, rather than the deprecated `HTTPConnection` class-based interface.
This requires a rewrite of the custom interface for directly reading stuff from FFL files for Virgo, but that is now much cleaner anyway.
This should implicitly enable using SciTokens with GWpy to discover data.

Migrate GWDataFind interface to new UI

---

pyproject.toml

Set pytest option so that XPASSED tests are considered as failures.

Strict xfail.

---

gwpy/table/tests/test_table.py

This PR works around an issue with python-ldas-tools-framecpp 2.6.13, see [computing/ldastools/LDAS_Tools#146](https://git.ligo.org/computing/ldastools/LDAS_Tools/-/issues/146).

Workaround a bug in framecpp-swig

---

.github/workflows/build.yml
.github/workflows/dependencies.yml

This PR adds a Python 3.10 matrix entry for the full end-to-end CI test job.

Run full test suite on Python 3.10

---

examples/frequencyseries/percentiles.py
gwpy/signal/filter_design.py
gwpy/signal/tests/test_window.py
gwpy/signal/window.py
gwpy/timeseries/timeseries.py

This MR fixes #1518 (compatibility with scipy 1.9.0) by updating all references to `'hanning'` as a window name to use `'hann'` instead.

Update all usage of 'hanning' window to 'hann'

---

gwpy/signal/spectral/_pycbc.py
gwpy/timeseries/tests/test_timeseries.py
gwpy/utils/misc.py
gwpy/utils/tests/test_misc.py

This PR deprecates the `gwpy.utils.null_context` function, replacing all internals and all usage in GWpy with `contextlib.nullcontext`.
Closes #1498.

Deprecate gwpy.utils.null_context

---

docs/table/plot.rst
gwpy/plot/plot.py
gwpy/plot/tests/test_plot.py

This PR removes two methods of the `gwpy.plot.Plot` class that have been deprecated essentially forever (since e270362e6e4bec91eb9c0e5688900e6be1af8f4c).

Remove deprecated Plot methods

---

gwpy/plot/axes.py
gwpy/plot/colors.py
gwpy/plot/gps.py
gwpy/plot/log.py
gwpy/plot/plot.py
gwpy/plot/segments.py
gwpy/plot/tests/test_rc.py
gwpy/plot/tex.py
gwpy/plot/units.py

This PR updates the `gwpy.plot` module to use [f-strings](https://www.python.org/dev/peps/pep-0498/) for all string formatting, instead of a mix of `str.format` and `%`-formatting.

Use f-strings for string formatting in gwpy.plot

---

gwpy/frequencyseries/frequencyseries.py
gwpy/timeseries/core.py
gwpy/timeseries/tests/test_core.py
gwpy/timeseries/tests/test_statevector.py
gwpy/utils/lal.py
gwpy/utils/tests/test_lal.py

This PR fixes #1478 by implementing changes proposed by @jolien-creighton to improve the LAL to/from unit conversions.
This has required an API change in the `gwpy.utils.lal.to_lal_unit` function, but I believe this to be sparingly used out of GWpy, so shouldn't be heavily disruptive.

Fix bugs in LAL unit conversion

---

docs/references.rst
docs/table/filter.rst
gwpy/table/filter.py
gwpy/table/table.py
gwpy/table/tests/test_table.py

This PR modifies `gwpy.table.filter` to support slicing multiple columns out of an `EventTable` and passing it into a filter function. I also updated the tests and beefed up the documentation to demonstrate the existing and the new functionality.

Add support for filter functions to use multiple columns with `EventTable.filter`

---

gwpy/frequencyseries/frequencyseries.py
gwpy/table/tests/test_table.py
gwpy/timeseries/io/losc.py

This PR addresses some line-length issues exposed by `flake8` (see [here](https://github.com/gwpy/gwpy/runs/7608965583)).
I don't understand why flake8 is only now catching these.

Fix some line length issues

---

gwpy/plot/colorbar.py
gwpy/plot/plot.py
gwpy/plot/tests/test_axes.py

This PR finalises two deprecations of the colorbar functionality:
- remove the `log` keyword that has been deprecated for years
- implement the change to the default `fraction`, now is 0.0 which means 'don't shrink the parent axes'

Remove deprecated colorbar behaviour

---

docs/timeseries/io.rst
gwpy/timeseries/core.py
gwpy/timeseries/io/gwf/__init__.py
gwpy/timeseries/tests/test_timeseries.py

This PR removes the `resample` and `dtype` options for reading GWF files, these have been deprecated since v0.11.0,
see 84672af3c4d3c285b758736eda4487fbe40fa1a0.

Remove deprecated GWF I/O options

---

gwpy/timeseries/tests/test_io_gwf_lalframe.py

This PR fixes #1519 by updating the relevant test to use [`Path.samefile`](https://docs.python.org/3/library/pathlib.html#pathlib.Path.samefile) which unwraps symlinks properly, rather than a dumb `==`.

Use Path.samefile() to compare paths

---

gwpy/types/index.py
gwpy/types/tests/test_index.py

This PR closes #1506 by refactoring the way that `Index.define()` creates arrays to prevent precision issues. A regression test has been introduced which demonstrates the precision issues describe in #1506.

Change the way Index.define creates arrays to prevent precision issues

---

gwpy/timeseries/timeseries.py

This PR resolves an issue with `timeseries.TimeSeries.mask()` where the masked samples may be offset by 1 from the span of samples that are tapered. This results in a single sample that is not masked, as well as a tapering that is applied at the end of the segment. 
In order to reproduce the bug, one needs to set the start and end times of the mask to times that do not correspond exactly with times of samples in the timeseries. The use of `int()` then creates the off-by-one error. 
Example code to reproduce error: 
```
import numpy
from gwpy.timeseries import TimeSeries
data_ones = TimeSeries(numpy.ones(16384), sample_rate=16384)
data_masked = data_ones.mask(deadtime=[(0.35,0.45)], tpad=0.25, const=0)
import matplotlib.pyplot as plt
plt.plot(data_masked)
plt.plot(data_ones)
plt.show()
```

Fix off-by-one error in timeseries.mask

---

gwpy/frequencyseries/frequencyseries.py
gwpy/frequencyseries/tests/test_frequencyseries.py
gwpy/timeseries/core.py
gwpy/timeseries/tests/test_core.py
gwpy/timeseries/tests/test_io_gwf_lalframe.py

This PR fixes #1475 by simplifying the `{TimeSeries.FrequencySeries}.from_lal` conversion method. The LAL series object doesn't hold enough information to properly seed a `Channel` object, and supports more data types than supported by NDS2, so the solution is to just not create a Channel object in the first place.
Depends #1479.

Simplify from_lal series conversions

---

docs/spectrogram/index.rst

This PR fixes a typo in the documentation, fixes #1522.

Fix typo in spectrogram documentation

---

gwpy/astro/tests/test_range.py
gwpy/cli/tests/base.py
gwpy/cli/tests/test_gwpy_plot.py
gwpy/cli/tests/test_qtransform.py
gwpy/detector/tests/test_channel.py
gwpy/frequencyseries/tests/test_frequencyseries.py
gwpy/io/tests/test_cache.py
gwpy/io/tests/test_datafind.py
gwpy/io/tests/test_gwf.py
gwpy/io/tests/test_ligolw.py
gwpy/io/tests/test_nds2.py
gwpy/io/tests/test_utils.py
gwpy/segments/tests/test_flag.py
gwpy/signal/tests/test_spectral_median_mean.py
gwpy/signal/tests/test_spectral_ui.py
gwpy/table/tests/test_io_ligolw.py
gwpy/table/tests/test_table.py
gwpy/testing/utils.py
gwpy/time/tests/test_time.py
gwpy/timeseries/tests/test_core.py
gwpy/timeseries/tests/test_io_gwf_lalframe.py
gwpy/timeseries/tests/test_statevector.py
gwpy/timeseries/tests/test_timeseries.py
setup.cfg

This PR closes #1495 by replacing all usage of `gwpy.testing.utils.skip_missing_dependency` with `pytest.mark.requires` from pytest-requires, and deprecates the former (but doesn't remove it).

Replace skip_missing_dependency test decorator with pytest.mark.requires

---

.gitignore
gwpy/timeseries/core.py
gwpy/timeseries/io/gwf/lalframe.py
gwpy/timeseries/tests/test_io_gwf_lalframe.py
gwpy/utils/lal.py
gwpy/utils/tests/test_lal.py

In case no frames match a time segment, it would be handy if reading by LALframe of a gwf file could return an empty ndarray instead of None for the data.data attribute of the LAL timeseries.
Here is a first attempt to do so.
Currently the writing of an empty LAL series fails when it is added (add_ cython or c function) to the frame in gwpy.timeseries.io.gwf.lalframe.write:
```python
add_(frame, lalseries)
```
So I've marked the test as xfailed, I would need more pointers to fix it (where is the relevant code ?)

LALFrame handling of empty arrays.

---

gwpy/timeseries/timeseries.py

This PR splits `TimeSeries.gate()` into two functions:
* `TimeSeries.find_gates()` - find peaks in whitened timeseries and returns the segments to gate
* `TimeSeries.gate()` - now only calls `TimeSeries.find_gates()` and `TimeSeries.mask()` to find and apply gates
The motivation for this change is that it would be helpful to be able to record the segments that were gated. Users hoping to do this can now use `TimeSeries.find_gates()` and `TimeSeries.mask()` separately. 
Since this PR is only reorganizing code, the result of `TimeSeries.gate()` remains unchanged.

Split up functionality of TimeSeries.gate()

---

gwpy/frequencyseries/frequencyseries.py
gwpy/frequencyseries/tests/test_frequencyseries.py

This PR ensures that a `ValueError` is returned when the user attempts to use `frequencyseries.FrequencySeries.to_pycbc()` in cases when the starting frequency is not `0 Hz`. When a PyCBC frequency series is created with `f0 != 0 Hz`, the PyCBC frequencies are not correct (They are offset by `f0`).
Here is an example of code that now returns a `ValueError` since the starting frequency is `10 Hz`:
```
from gwpy.frequencyseries import FrequencySeries
psd = (FrequencySeries.read('O3-H1-C01_CLEAN_SUB60HZ-1262197260.0_sensitivity_strain_asd.txt')).to_pycbc()
print(psd.sample_frequencies)
```
The above example uses this file: https://dcc.ligo.org/public/0174/G2100674/001/O3-H1-C01_CLEAN_SUB60HZ-1262197260.0_sensitivity_strain_asd.txt

Add ValueError when improper starting frequency used with `to_pycbc()`

---

docs/table/io.rst
gwpy/table/io/__init__.py
gwpy/table/io/gstlal.py
gwpy/table/tests/test_io_gstlal.py

This pull request aims to add support for reading gstlal trigger files.
The rationale for a specific gstlal format is 
* A desire to calculate some useful derived quantities. This feature is available for only pycbc trigger files at present. 
* The gstlal statistic requires additional inputs beyond what is included in trigger files in order to calculate the ranking statistic. However, the comparable quantity is stored in the `coinc_event` table. Hence reading in both the `coinc_event` and `coinc_inspiral` tables at once would be a useful feature. 
Thew new proposed format heavily relies upon the current ligolw functionality, with the addition of the two features above.

Add support for reading gstlal trigger files

---

gwpy/types/array2d.py
gwpy/types/series.py
gwpy/types/tests/test_array2d.py

This PR fixes #1504 which reported an `IndexError` when attempting to create width-1 slices of `Array2D` objects.

Fix bug in width-1 slices of Array2D

---

gwpy/segments/tests/test_flag.py

This PR updates the example XML in the `gwpy.segments` tests for read/write of a Veto definer file.

Update veto-definer test example XML

---

.github/workflows/conda.yml
.github/workflows/dist.yml

This PR restructures the CI pipeline a bit to expand the `pip install` tests now that ligo-segments has wheels available for Windows.

Minor restructuring of CI pipeline

---

gwpy/io/nds2.py
gwpy/io/tests/test_nds2.py

This PR fixes compatibility issues between the enums in `gwpy.io.nds2` and updated enum functionality introduced with Python 3.11.
Fixes #1557.

Fix issues with Nds2Enum on Python 3.11

---

gwpy/cli/cliproduct.py

This PR modifies the style/layout of the argparse code in `gwpy.cli.cliproduct`, mainly to enable minimal diffs when future changes are made.
This should have zero functional impact (none of the keyword arguments _should_ have changed, just the layout of the code).

Use consistent formatting for all argparse stuff in gwpy.cli

---

gwpy/io/ligolw.py
gwpy/io/tests/test_ligolw.py

This PR fixes reading old-style LIGO_LW XML files that contain ILWD characters.
python-ligo-lw >=1.8.0 removed the ilwd char support, so we need to in-house some of that stuff.

Fix reading 'old-style' LIGO_LW files (with ILWD characters)

---

gwpy/cli/cliproduct.py
gwpy/cli/spectrum.py
gwpy/cli/timeseries.py

This PR adds a `--gwosc` option for `gwpy-plot` to support getting data from GWOSC.
Depends on #1568.

Support GWOSC as a data source for gwpy-plot

---

gwpy/timeseries/core.py
gwpy/timeseries/tests/test_timeseries.py

This PR improves the `NDSWarning` message emitted during `TimeSeriesDict.fetch` when errors in the fetch are caught so that a different NDS server can be tried.
The old warning was something like this:
```text
/home/duncan/git/gwpy/gwpy/timeseries/core.py:1142: NDSWarning: no data received from nds.ligo.caltech.edu for [1126260017 ... 1126260617)
warnings.warn(error.split('\n', 1)[0],
```
The new one includes the channels requested and the GPS interval (which isn't always in the error message emitted by the NDS2 client):
```text
/home/duncan/git/gwpy/gwpy/timeseries/core.py:1143: NDSWarning: failed to fetch data for H1:GDS-CALIB_STRAIN, H1:PEM-CS_ACC_PSL_PERISCOPE_X_DQ in interval [1126260017, 1126260617.0): no data received from nds.ligo.caltech.edu for [1126260017 ... 1126260617) …
```

Improve NDSWarning message emitted by TimeSeriesDict.fetch

---

gwpy/testing/errors.py

This PR adds `requests.exceptions.ConnectionError` to the list of network errors handled by the `gwpy.testing.errors.pytest_skip_network_error` decorator.

Gracefully skip requests.exceptions.ConnectionError in testing

---

gwpy/plot/gps.py

This PR closes #1564 by updating the usage of `matplotlib.docstrings` to account for the renamed private module, and to protect against that module disappearing entirely in the future.

Update import of matplotlib.docstrings

---

gwpy/plot/colorbar.py
gwpy/plot/tests/test_axes.py

This PR fixes incompatibilities with matplotlib 3.7.0 exposed by the 'experimental 'dependencies CI job.

Fix incompatibilities with matplotlib 3.7.0

---

examples/signal/qscan.py

This MR updates the `examples/signal/qscan` example script, mainly to address a matplotlib deprecation warning.

Update qscan example

---

gwpy/io/_framecpp.py
gwpy/io/gwf.py

This PR addresses an incompatibility between `gwpy.io` and python-ldas-tools-framecpp 3.0.0; the compression options changed compared to frameCPP 2.9.

Update GWF writing for frameCPP 3.0.0

---

docs/cli/examples.ini
docs/conf.py

This PR updates a number of CLI examples to use an event from GWTC-3, mainly to allow them to use more recent data that is easier to access.

Update a number of CLI examples to use GWTC-3 data

---

.github/workflows/lint.yml
docs/external/framecpp.rst
docs/external/framel.rst
docs/external/lalsuite.rst
docs/external/nds2.rst
docs/install.rst
docs/references.rst
docs/table/io.rst
docs/timeseries/datafind.rst
docs/timeseries/io.rst
pyproject.toml

This PR closes #1561 by improving the documentation of the optional GWF I/O libraries.
My solution is to provide our own 'external' pages for the various tools where the upstream reference doesn't do a good job of instructed users on how to install the library.
cc @jkanner

Improve documentation of GWF I/O libraries

---

.github/workflows/conda.yml
gwpy/time/_tconvert.py
gwpy/time/tests/test_time.py
pyproject.toml

This PR improves the handling and propagation of errors from `maya/dateparser` when attempting to convert times.
This also refactors the test suite for `gwpy.time` to improve the tests and make them more readable. As part of this I replace the `freezegun` requirement with `pytest-freezegun`.

Improve handling/propagation of maya/dateparser errors and refactor gwpy.time tests

---

gwpy/astro/tests/test_range.py
gwpy/detector/tests/test_channel.py
gwpy/frequencyseries/tests/test_frequencyseries.py
gwpy/frequencyseries/tests/test_hist.py
gwpy/io/tests/test_cache.py
gwpy/io/tests/test_datafind.py
gwpy/io/tests/test_gwf.py
gwpy/io/tests/test_kerberos.py
gwpy/io/tests/test_ligolw.py
gwpy/io/tests/test_mp.py
gwpy/io/tests/test_nds2.py
gwpy/io/tests/test_utils.py
gwpy/plot/tests/test_axes.py
gwpy/segments/tests/test_flag.py
gwpy/signal/tests/test_window.py
gwpy/spectrogram/tests/test_spectrogram.py
gwpy/table/tests/test_gravityspy.py
gwpy/table/tests/test_io_pycbc.py
gwpy/table/tests/test_table.py
gwpy/timeseries/tests/test_core.py
gwpy/timeseries/tests/test_io_gwf_lalframe.py
gwpy/timeseries/tests/test_statevector.py
gwpy/timeseries/tests/test_timeseries.py
gwpy/types/tests/test_array2d.py
gwpy/types/tests/test_series.py
gwpy/utils/tests/test_decorators.py
gwpy/utils/tests/test_enum.py
gwpy/utils/tests/test_lal.py
gwpy/utils/tests/test_misc.py
gwpy/utils/tests/test_mp.py

This PR closes #1541 by updating the use of `pytest.raises` throughout the codebase to use the `match` keyword. This cleans things up a wee bit, and naturally allows more flexibility in matching the error message (since pytest uses a regex, rather than simple string comparisons).

Update usage of pytest.raises throughout the codebase

---

gwpy/plot/tests/test_tex.py
gwpy/plot/tex.py

This PR enhances the `gwpy.plot.tex.has_tex` function that attempts to detect whether LaTeX can be used as a text renderer by attempting to draw (but not render) an image that actually uses latex.
This should amount to an end-to-end test such that if `has_tex` returns `True`, then the user has significant assurance that the LaTeX installation is complete enough for MPL.

Enhance LaTeX detection

---

gwpy/signal/filter_design.py
gwpy/signal/tests/test_window.py
gwpy/signal/window.py
gwpy/timeseries/timeseries.py

This PR adds a new `gwpy.signal.window.get_window()` function which wraps `scipy.signal.get_window` but also accepts pre-computed window arrays, with some validation.
This helps to simplify some repeated logic for handling different windows and allows pre-computed windows to be used in all SP functions.
Closes #1546.

Add wrapper around scipy.signal.get_window to handle pre-computed window arrays

---

gwpy/signal/qtransform.py
gwpy/timeseries/tests/test_timeseries.py

Closes #1580 
(near) drop-in replacement found at see https://gist.github.com/ev-br/8544371b40f414b7eaf3fe6217209bff
https://gwpy.github.io/docs/latest/examples/timeseries/qscan/ produces same result
unit tests seem to pass, though gwpy/timeseries/tests/test_timeseries.py maybe contains a more robust test (though it downloads data) than gwpy/signal/tests/test_qtransform.py. Not sure the latter ones passing will prove the result is the same in general.
Added another assertion to test in test_timeseries, to check not just max val but mean of vals (perhaps more sensitive to subtle changes)

replace deprecated interp2d with RectBivariateSpline

---

gwpy/types/index.py
gwpy/types/tests/test_index.py

This PR addresses #1596 and introduces a new test to confirm that this issue does not pop up again with the `Index` class.

Address floating point errors for index creation

---

gwpy/timeseries/core.py
gwpy/timeseries/io/losc.py

`TimeSeries.fetch_open_data()` reports `TypeError: get_urls() got an unexpected keyword argument 'tag'`, this PR removes `tag` from `timeseries/core.py` and `timeseries/io/losc.py`.

Fix tag error

---

docs/install.rst
gwpy/timeseries/statevector.py
gwpy/timeseries/tests/test_statevector.py
gwpy/types/io/hdf5.py
pyproject.toml

This PR adds a test for, then fixes issues with, writing `StateVector` to HDF5.
There was an issue converting `Bits` to an array that could be embedded inside an HDF5 attribute.

Fix issues writing StateVector.bits to HDF5

---

gwpy/timeseries/core.py
gwpy/timeseries/tests/test_core.py

This PR fixes #1609 by adding a special case for `separate=True`.

Fix plotting TimeSeriesDict on separate Axes

---

gwpy/plot/units.py

This PR updates the `LatexInlineDimensional` unit formatter to accommodate changes that will be introduced in Astropy 5.3.
The `_latex_escape` private method was removed from the relevant parent class, so this MR replaces that call with a manual version of the same logic, and updates some documentation.

Update LatexInlineDimensional unit formatter for Astropy 5.3

---

gwpy/frequencyseries/tests/test_hist.py
gwpy/types/series.py
gwpy/types/tests/test_series.py

This PR fixes #1601 by tweaking the way that `Series.crop` rounds floats to integers, using `floor` instead of `//`.
I also cleaned up the code and its tests a bunch.

Fix issues with Series.crop precision

---

gwpy/timeseries/core.py

This PR indirectly addresses #1516 by adding documentation of the `copy` keyword for the `TimeSeries{Base}Dict.crop` method.

Document the copy keyword for TimeSeriesBaseDict.crop

---

gwpy/timeseries/tests/test_timeseries.py

This PR improves the tests of `TimeSeries.csd`, in part to accommodate changes coming for numpy 1.25 that impact comparing complex and real-typed arrays (less magic happens).

Improve tests of TimeSeries.csd

---

.github/workflows/conda.yml
.github/workflows/dependencies.yml
.github/workflows/dist.yml
gwpy/detector/channel.py
pyproject.toml

This PR removes support for Python 3.7, which is [end-of-life at the end of June](https://devguide.python.org/versions/#supported-versions).

Drop support for Python 3.7

---

gwpy/timeseries/core.py
gwpy/timeseries/tests/test_core.py

This PR fixes #1646 by removing a rounding of `self.dt` when that is set via the `sample_rate` property. I can't remember why that was there in the first place, but it's clearly broken for very high sample rates (for which the `dt` is very small).
Closes #1646.

Don't round TimeSeries.dt when setting via sample_rate

---

gwpy/signal/filter_design.py
gwpy/signal/tests/test_filter_design.py
gwpy/timeseries/tests/test_timeseries.py
gwpy/timeseries/timeseries.py

2pi scaling happens by default inside bilinear_zpk for Hz -> rad/s. Extract that functionality so that i) bilinear transform is not also responsible for scaling (single responsibility principle) ii) it is used more explicitly where it is needed iii) the functions are more easily tested.
This MR will be followed by another MR that includes a comprehensive set of tests for filter design functionality, including zpk_transform, as well as bugfixes.

Move 2pi scaling of zpk filters for better encapsulation and more explicit use

---

gwpy/types/series.py
gwpy/utils/tests/test_misc.py

This PR fixes some lint complaints regarding exact type comparisons. It seems flake8 6.1.0 is more discerning than 6.0.0, which is probably for the best.

Fix type comparison lint

---

gwpy/plot/axes.py
gwpy/plot/plot.py
gwpy/plot/tests/test_axes.py

This PR updates the handling of the `PlotArgsProcessor` class that overrides the builtin `_process_plot_var_args` private object that does all of the low-level argument handling and line generation for `Axes.plot()`.
In matplotlib <3.8.0 the parent `Axes` object is passed to the constructor, while in >=3.8.0 that is passed to the caller.

Fix compatibility with matplotlib 3.8.0

---

.github/workflows/dependencies.yml

This PR updates the experimental dependencies CI job to use Python 3.11, which is long overdue.
Depends on #1661

Update experimental dependencies job to Python 3.11

---

gwpy/frequencyseries/_fdcommon.py
gwpy/frequencyseries/tests/test_frequencyseries.py
gwpy/spectrogram/tests/test_spectrogram.py

Fix a bug where frequency domain filtering was not returning an expected result because analog scipy methods were being used despite default analog=False args. 
Now, analog and digital filters use corresponding scipy functions (freqs_zpk and freqz_zpk) that take into account fs.
Also, two tests were added, and some test assertions, to check results of frequency domain filtering for some simple examples.
In a few places, tests have changed.

Fix a bug with frequency domain filtering

---

gwpy/signal/filter_design.py
gwpy/signal/tests/test_filter_design.py

Added an extra test to make sure complex filter dtypes are preserved
Addresses https://github.com/gwpy/gwpy/issues/1630
Using scipy's implementation we also avoid problems with old implementation casting to float as in https://github.com/gwpy/gwpy/issues/1630#issuecomment-1721674653

Replace bilinear_zpk with the scipy implementation

---

.github/workflows/conda.yml
.github/workflows/dependencies.yml
.github/workflows/dist.yml
.github/workflows/lint.yml

This PR updates the versions of actions uses in the GHA workflows to the latest stable versions, mainly for housekeeping.
This shouldn't resolve any actual issues, but will silence some warnings emitted by some jobs.

Update versions for GitHub Actions actions

---

docs/cli/examples.ini

This PR removes 2c9862e1199bb9cdd683596debb36eb79de42536 (cherry picked from ef3833224c5521b68b9e18d757e770770aaa9505) from the `release/3.0.x` branch. This is dependent on #1569 which is scheduled for inclusion first in [3.1.0](https://github.com/gwpy/gwpy/milestone/60).

Revert "docs: use GWOSC where we can in CLI examples" in 3.0.x release branch

---

gwpy/types/series.py
gwpy/types/sliceutils.py
gwpy/types/tests/test_array2d.py
gwpy/types/tests/test_series.py

See https://github.com/gwpy/gwpy/issues/1680.
When `__getitem__` is called with an int array, the xindex is not subsetted.

Fix array indexing of Series.xindex

---

.github/workflows/release.yml

This PR adds a Github Actions release workflow to automatically upload distributions to pypi, so that @duncanmmacleod doesn't mess it up like he did for 3.0.6.
See <https://docs.pypi.org/trusted-publishers/adding-a-publisher/>.

Add CI PyPI release workflow

---

gwpy/timeseries/io/losc.py

This PR fixes #1612 (closes #1664) by `sieve()`ing the list of URLs received from the GWOSC client in case they overrun the actual requested interval.

Sieve URLs from gwosc client before fetch

---

.github/workflows/dependencies.yml

This PR attempts to fix the current failures in the 'experimental' dependencies CI job that is failing to find debian packages to install.

Run apt-get update before apt-get install in CI jobs

---

pyproject.toml

This PR patches the metadata to avoid installing GWpy alongside `python-framel` 8.46.0, see https://git.ligo.org/virgo/virgoapp/Fr/-/issues/8.

Avoid python-framel 8.46.0

---

gwpy/testing/utils.py
gwpy/utils/shell.py
gwpy/utils/tests/test_shell.py

This PR excises all use of the late `distutils` Python standard library module.

Remove all use of distutils

---

docs/overview.rst

- LALSuite has been rebranded to "LVK" https://git.ligo.org/lscsoft/lalsuite/-/merge_requests/2222
(I googled to check on the old confusion between "LIGO" and "LSC" and gwpy docs came up high)

track LALSuite rebrand in docs

---

gwpy/plot/tests/test_tex.py
gwpy/plot/tex.py
gwpy/testing/fixtures.py

Hello :wave: I have noticed that a significant part of the startup time of `gwpy` comes from the execution of `has_tex` to store the result in `HAS_TEX`, which is never used later on.
In this PR, I deleted `HAX_TEX` and cached the result of `has_tex` in case it would be necessary to call it several times. It reduces the startup time by about 2 seconds which could be huge for some applications.
```console
user@host:~ $ time python -c 'from gwpy.timeseries import TimeSeries'
real	0m3,381s
user	0m2,600s
sys	0m2,091s
```
```console
user@host:~ $ time python -c 'from gwpy.timeseries import TimeSeries'
real	0m1,360s
user	0m1,430s
sys	0m1,419s
```

Drop `HAS_TEX` for faster startup time

---

.github/workflows/dist.yml
pyproject.toml

~This PR adds the `--allow-unix-socket` to the `dist` CI jobs so that `asyncio` works with 'self-sockets' (required by the latest release of `freezegun`).~
EDIT: for obvious reasons this solution doesn't work on Windows, so now...
This PR adds `--allow-hosts=127.0.0.1` to the `dist` CI jobs so that `asyncio` works with 'self-sockets' (required by the latest release of `freezegun`).

Allow localhost sockets during dist testing

---

docs/conf.py
docs/install.rst
docs/references.rst
gwpy/time/_tconvert.py
gwpy/time/tests/test_time.py
pyproject.toml

This  PR replaces all use of the `maya` module with `dateparser`.
`maya` is not actively maintained any more, while `dateparser` is, and is what `maya` calls out to anyway.

Replace maya with dateparser in gwpy.time

---

gwpy/time/_tconvert.py

This PR replaces a call to `datetime.datetime.utcnow()` with the equivalent call to `datetime.datetime.now()`; the former is [deprecated](https://docs.python.org/3/whatsnew/3.12.html#deprecated) as of Python 3.12.

Replace datetime.utcnow() with datetime.now(UTC)

---

gwpy/timeseries/tests/test_timeseries.py

This PR abstracts some reused `TimeSeries.fetch_open_data` calls to class-level fixtures for the `TestTimeSeries` tests. This should speed up test execution when `GWPY_CACHE` is not set to something truthy.

Use class fixtures to download GWOSC data that is used many times

---

gwpy/detector/tests/test_units.py
gwpy/detector/units.py
gwpy/plot/gps.py
gwpy/plot/tests/test_gps.py

This PR adds unit aliases for the common 'time'-like unit strings LIGO and Virgo like to use as the `unitX` attribute for `FrVect` structures in GWF (they should just use 's'; 'time' is a dimension, not a unit).

Add aliases for LIGO and Virgo's 'time' units

---

gwpy/timeseries/io/cache.py
gwpy/timeseries/tests/test_io_cache.py

This PR adds a test suite for the `gwpy.timeseries.io.cache` module, and fixes #1640 along the way by refactoring the contained `preformat_cache()` function.

Add tests for gwpy.timeseries.io.cache

---

gwpy/utils/sphinx/zenodo.py
gwpy/utils/tests/test_sphinx_zenodo.py

This PR fixes the `gwpy.utils.sphinx.zenodo` API interface module uses to populate the `citing` page on the online docs (e.g. [here](https://gwpy.github.io/docs/latest/citing/)), which was broken by a recent (apparently undocumented) Zenodo API change (see https://github.com/zenodo/zenodo/issues/2483).
I also took the opportunity to refactor the module to improve the layout, and added a test module.

Fix the Zenodo RST utility module

---

gwpy/timeseries/io/gwf/framecpp.py

This PR patches the frameCPP GWF timeseries reader to actually use the `unitX` attribute stored in the FrVect structure for a given channel in a GWF.
Depends on #1721.

Read the unitX from a GWF with frameCPP

---

gwpy/segments/flag.py

This PR fixes #1729 by correctly propagating the `source` keyword as the URL for DQSegDB queries.

Propagate source keyword in DataQualityDict.populate

---

gwpy/segments/flag.py
gwpy/segments/tests/test_flag.py

This PR partly addresses #1668 by hacking the LIGO_LW parser to handle missing `_ns` columns.

Handle reading LIGO_LW XML files that are missing the _ns timing columns 

---

gwpy/timeseries/io/gwf/lalframe.py
gwpy/timeseries/tests/test_io_gwf_lalframe.py

This PR patches the LALFrame GWF interface to detect and re-read a missing sample that may occur when the GPS start time requested doesn't correspond to a sample time, but the end time does.
See https://git.ligo.org/computing/helpdesk/-/issues/4774 and https://git.ligo.org/lscsoft/lalsuite/-/issues/710.

Fix missing sample when reading with non-exact sample times using LALFrame

---

gwpy/timeseries/tests/test_timeseries.py

This PR fixes compatibility with scipy 1.13.0 by using `scipy.signal.get_window` to create a `hann` window in the tests (accessing window functions as attributes of the `scipy.signal` module is deprecated).

Fix usage of hann window for scipy 1.13.0

---

.github/workflows/conda.yml

This PR patches the `conda` CI workflow to use `conda` instead of `mamba`, but with the `libmamba` solver, which means its basically the same, but without increased risk of CLI incompatibility.
Depends on #1723.

Use conda with libmamba solver in CI

---

gwpy/astro/range.py
gwpy/astro/tests/test_range.py
pyproject.toml

This PR updates `gwpy.astro` to use the `scipy.integrate.trapezoid` function; this was renamed from trapz in scipy-1.6.0 and removed in scipy-1.16.0.

Use scipy.integrate.trapezoid in gwpy.astro

---

gwpy/io/datafind.py

This PR adds `HoftOnline` as one of the `HIGH_PRIORITY_TYPE` frametypes in `gwpy.io.datafind`. 
The "standard" Virgo strain frametype has changed in O4 from `V1Online` to `HoftOnline`, but it not yet updated in `gwpy`. 
@jacobgolomb noted that this issue prevents `bilby_pipe` from automatically identifying the correct Virgo frametype to use in O4.

Add HoftOnline as a preferred frametype

---

gwpy/detector/units.py

This PR works around an upstream 'feature' of the GEO and Virgo observatories by adding support for `time (s)` as an unit alias for `s`. This is used as the 'unit' for the time axis for many `Timeseries` channels in GWF data files.

Add 'time (s)' as alias for 's'

---

gwpy/signal/filter_design.py
gwpy/signal/tests/test_filter_design.py

This PR updates the the usage of the `scipy.signal.firwin` function to remove deprecated arguments.

Update usage of scipy 'firwin' function

---

gwpy/testing/utils.py
gwpy/timeseries/io/gwf/lalframe.py
gwpy/timeseries/tests/test_timeseries.py

This PR improves the handling of invalid inputs (start and end GPS times) when attempting to read data from GWF with LALFrame to provide better error messages and avoid [inconsistent behaviour of LALFrame on non-x86_64 systems](https://git.ligo.org/lscsoft/lalsuite/-/issues/745).
The result should be no change in the GWpy UX, other than perhaps a different error class when passing invalid inputs (`ValueError` instead of `RuntimeError`).

Improve handling of invalid inputs when reading data from GWF with LALFrame
